export enum ErrorType {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  FILE_FORMAT_ERROR = 'FILE_FORMAT_ERROR',
  MODEL_PROCESSING_ERROR = 'MODEL_PROCESSING_ERROR',
  AI_SERVICE_ERROR = 'AI_SERVICE_ERROR',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',
  UNAUTHORIZED_ERROR = 'UNAUTHORIZED_ERROR',
  RATE_LIMIT_ERROR = 'RATE_LIMIT_ERROR',
}