import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { resolveInside } from "./pathSafety.js";

export type AgencyStepKind = "perception" | "desire" | "options" | "choice" | "reason" | "cost" | "consequence";
export interface AgencyChain { schemaVersion: "character-agency-chain.v1"; chainId: string; projectSlug: string; sceneId: string; characterId: string; steps: Array<{ kind: AgencyStepKind; value: string; evidenceRefs: string[] }>; status: "valid" | "broken"; breaks: string[]; keyScene: boolean; createdAt: string; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function file(root: string, id: string) { return resolveInside(root, `sessions/agency-chains/${id}.json`); }
async function read<T>(target: string): Promise<T | null> { try { return JSON.parse(await fs.readFile(target, "utf8")) as T; } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return null; throw e; } }
async function write(target: string, value: unknown) { await fs.mkdir(path.dirname(target), { recursive: true }); const tmp = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await fs.rename(tmp, target); }
function nonEmpty(value: unknown): value is string { return typeof value === "string" && value.trim().length > 0; }
export function assertAgencyChainIntegrity(chain: AgencyChain, expectedId?: string): AgencyChain {
  const { fingerprint, ...base } = chain;
  const validKinds: AgencyStepKind[] = ["perception", "desire", "options", "choice", "reason", "cost", "consequence"];
  const stepsValid = Array.isArray(chain.steps) && chain.steps.length === validKinds.length && chain.steps.every((step) => Boolean(step && validKinds.includes(step.kind) && nonEmpty(step.value) && Array.isArray(step.evidenceRefs) && step.evidenceRefs.length > 0 && step.evidenceRefs.every(nonEmpty))) && new Set(chain.steps.map((step) => step.kind)).size === validKinds.length;
  const valid = chain.schemaVersion === "character-agency-chain.v1" && (!expectedId || chain.chainId === expectedId) && [chain.chainId, chain.projectSlug, chain.sceneId, chain.characterId, chain.createdAt].every(nonEmpty) && stepsValid && ["valid", "broken"].includes(chain.status) && Array.isArray(chain.breaks) && chain.breaks.every(nonEmpty) && ((chain.status === "valid" && chain.breaks.length === 0) || (chain.status === "broken" && chain.breaks.length > 0)) && typeof chain.keyScene === "boolean" && /^[a-f0-9]{64}$/i.test(chain.fingerprint) && hash(base) === chain.fingerprint;
  if (!valid) throw new Error("AGENCY_CHAIN_INTEGRITY_FAILED");
  return chain;
}
export async function readAgencyChain(root: string, chainId: string) { const chain = await read<AgencyChain>(file(root, chainId)); return chain ? assertAgencyChainIntegrity(chain, chainId) : null; }
export function evaluateAgencyChain(chain: Pick<AgencyChain, "steps" | "keyScene">): Pick<AgencyChain, "status" | "breaks"> { const value = (kind: AgencyStepKind) => chain.steps.find((step) => step.kind === kind)?.value.trim() || ""; const options = value("options").split("|").map((option) => option.trim()).filter(Boolean); const breaks: string[] = []; if (chain.steps.some((step) => !step.evidenceRefs.length || step.evidenceRefs.some((ref) => !ref.trim()))) breaks.push("AGENCY_STEP_EVIDENCE_REQUIRED"); const kinds = chain.steps.map((step) => step.kind); if (new Set(kinds).size !== kinds.length) breaks.push("AGENCY_STEP_DUPLICATE"); if (!value("perception")) breaks.push("PERCEPTION_REQUIRED"); if (!value("desire")) breaks.push("DESIRE_REQUIRED"); if (!options.length) breaks.push("AVAILABLE_STRATEGIES_REQUIRED"); if (!value("choice")) breaks.push("CHOICE_REQUIRED"); else if (options.length && !options.includes(value("choice"))) breaks.push("CHOICE_NOT_IN_AVAILABLE_STRATEGIES"); if (!value("reason")) breaks.push("IMMEDIATE_REASON_REQUIRED"); if (!value("cost")) breaks.push("COST_REQUIRED"); if (!value("consequence")) breaks.push("CONSEQUENCE_REQUIRED"); return { status: breaks.length ? "broken" : "valid", breaks }; }
export async function createAgencyChain(input: { root: string; projectSlug: string; sceneId: string; characterId: string; perception: string; desire: string; availableStrategies: readonly string[]; actualChoice: string; immediateReason: string; cost: string; consequence: string; evidenceRefs: readonly string[]; keyScene?: boolean }): Promise<AgencyChain> { if (!input.projectSlug.trim() || !input.sceneId.trim() || !input.characterId.trim()) throw new Error("AGENCY_FIELDS_REQUIRED"); if (!input.evidenceRefs.length) throw new Error("AGENCY_EVIDENCE_REQUIRED"); const chainId = `agency-${input.sceneId}-${input.characterId}`; const existing = await readAgencyChain(input.root, chainId); if (existing) return existing; const refs = [...input.evidenceRefs]; const steps = [{ kind: "perception" as const, value: input.perception, evidenceRefs: refs }, { kind: "desire" as const, value: input.desire, evidenceRefs: refs }, { kind: "options" as const, value: input.availableStrategies.join(" | "), evidenceRefs: refs }, { kind: "choice" as const, value: input.actualChoice, evidenceRefs: refs }, { kind: "reason" as const, value: input.immediateReason, evidenceRefs: refs }, { kind: "cost" as const, value: input.cost, evidenceRefs: refs }, { kind: "consequence" as const, value: input.consequence, evidenceRefs: refs }]; const evaluated = evaluateAgencyChain({ steps, keyScene: input.keyScene !== false }); const base = { schemaVersion: "character-agency-chain.v1" as const, chainId, projectSlug: input.projectSlug, sceneId: input.sceneId, characterId: input.characterId, steps, ...evaluated, keyScene: input.keyScene !== false, createdAt: new Date().toISOString() }; const chain = { ...base, fingerprint: hash(base) }; await write(file(input.root, chainId), chain); return chain; }
