export function settleDerivedAnswer(input: { answered: readonly string[]; unresolved: readonly string[] }): { settled: string[]; remaining: string[]; confirmationsSaved: number } { return { settled: [...input.answered], remaining: [...input.unresolved], confirmationsSaved: input.answered.length }; }
export function createDecisionBundle(input: { decisions: Array<{ id: string; risk: "low" | "high"; rollback: boolean }>; revokeRequested: boolean }): { status: "bundled" | "blocked" | "revoked"; ids: string[]; atomic: boolean } { const safe = input.decisions.every((decision) => decision.risk === "low" && decision.rollback); if (!safe) return { status: "blocked", ids: [], atomic: false }; return { status: input.revokeRequested ? "revoked" : "bundled", ids: input.decisions.map((decision) => decision.id), atomic: true }; }
export function presentChoice(input: { recommendation: string; recommendationFit: string; redRisk: string; options: readonly string[]; freeAnswer: boolean }): { status: "presented" | "blocked"; recommendation: string; redRisk: string; options: string[]; freeAnswer: boolean } { return input.recommendation && input.redRisk && input.options.length >= 2 ? { status: "presented", recommendation: input.recommendation, redRisk: input.redRisk, options: [...input.options], freeAnswer: input.freeAnswer } : { status: "blocked", recommendation: "", redRisk: "", options: [], freeAnswer: false }; }
export function summarizeStoryCost(input: { arcs: readonly string[]; foreshadowing: readonly string[]; chapters: readonly string[]; reworkUnits: number; reversible: boolean }): { arcs: string[]; foreshadowing: string[]; chapters: string[]; reworkUnits: number; reversible: boolean; technicalDetailsHidden: true } { return { arcs: [...input.arcs], foreshadowing: [...input.foreshadowing], chapters: [...input.chapters], reworkUnits: input.reworkUnits, reversible: input.reversible, technicalDetailsHidden: true }; }
export function scopeDelegation(input: { issueId: string; delegated: boolean }): { delegatedIssue: string; permanent: false } { return { delegatedIssue: input.delegated ? input.issueId : "", permanent: false }; }
export function resolveContinue(input: { answered: boolean; contractCandidateAvailable: boolean; sameStateReplay: boolean }): { action: "settle-and-contract" | "noop" | "blocked" } { if (input.sameStateReplay) return { action: "settle-and-contract" }; return input.answered && input.contractCandidateAvailable ? { action: "settle-and-contract" } : { action: "blocked" }; }
export function handleOffline(input: { authorOffline: boolean; highImpactPending: boolean; candidateCreated: boolean; authorReturned: boolean }): { status: "waiting" | "briefed" | "unchanged"; autoAdopted: false } { if (!input.authorOffline && input.authorReturned) return { status: "briefed", autoAdopted: false }; if (input.highImpactPending) return { status: "waiting", autoAdopted: false }; return { status: "unchanged", autoAdopted: false }; }
export function reuseConfirmedFact(input: { confirmed: boolean; newConflict: boolean; newEvidence: readonly string[] }): { status: "reuse" | "reask"; evidence: string[] } { return input.confirmed && !input.newConflict ? { status: "reuse", evidence: [] } : { status: "reask", evidence: [...input.newEvidence] }; }
export function propagateCorrection(input: { oldUnderstanding: string; corrected: string; downstreamIds: readonly string[] }): { status: "stopped"; staleIds: string[]; current: string } { return { status: "stopped", staleIds: [...input.downstreamIds], current: input.corrected }; }
