import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { resolveInside } from "./pathSafety.js";

export type BeatFulfillmentStatus = "planned" | "attempted" | "evidenced" | "missed" | "invalidated";
export interface BeatFulfillmentLedger { schemaVersion: "beat-fulfillment-ledger.v1"; ledgerId: string; projectSlug: string; sceneId: string; sourceRefs: string[]; beats: Array<{ beatId: string; label: string; required: boolean; status: BeatFulfillmentStatus; evidenceRefs: string[]; reason: string | null; updatedAt: string }>; status: "open" | "completed" | "blocked"; createdAt: string; updatedAt: string; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function file(root: string, id: string) { return resolveInside(root, `sessions/beat-fulfillment/${id}.json`); }
async function read<T>(target: string): Promise<T | null> { try { return JSON.parse(await fs.readFile(target, "utf8")) as T; } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return null; throw e; } }
async function write(target: string, value: unknown) { await fs.mkdir(path.dirname(target), { recursive: true }); const tmp = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await fs.rename(tmp, target); }
export function assertBeatFulfillmentLedgerIntegrity(ledger: BeatFulfillmentLedger, expectedLedgerId?: string): BeatFulfillmentLedger { const { fingerprint: _fingerprint, ...base } = ledger; const ids = new Set<string>(); const validBeats = Array.isArray(ledger.beats) && ledger.beats.length > 0 && ledger.beats.every((beat) => { const valid = typeof beat.beatId === "string" && beat.beatId.trim() && !ids.has(beat.beatId) && typeof beat.label === "string" && beat.label.trim() && typeof beat.required === "boolean" && ["planned", "attempted", "evidenced", "missed", "invalidated"].includes(beat.status) && Array.isArray(beat.evidenceRefs) && beat.evidenceRefs.every((ref) => typeof ref === "string" && ref.trim()) && (beat.status !== "evidenced" || beat.evidenceRefs.length > 0) && (beat.status !== "missed" && beat.status !== "invalidated" || Boolean(beat.reason?.trim())) && typeof beat.updatedAt === "string" && beat.updatedAt.trim(); ids.add(beat.beatId); return valid; }); const required = ledger.beats?.filter((beat) => beat.required) || []; const derivedStatus = required.some((beat) => beat.status === "missed" || beat.status === "invalidated") ? "blocked" : required.length > 0 && required.every((beat) => beat.status === "evidenced") ? "completed" : "open"; const valid = ledger.schemaVersion === "beat-fulfillment-ledger.v1" && (!expectedLedgerId || ledger.ledgerId === expectedLedgerId) && Boolean(ledger.ledgerId?.trim() && ledger.projectSlug?.trim() && ledger.sceneId?.trim()) && Array.isArray(ledger.sourceRefs) && ledger.sourceRefs.length > 0 && ledger.sourceRefs.every((ref) => typeof ref === "string" && ref.trim()) && validBeats && ["open", "completed", "blocked"].includes(ledger.status) && ledger.status === derivedStatus && typeof ledger.createdAt === "string" && ledger.createdAt.trim() && typeof ledger.updatedAt === "string" && ledger.updatedAt.trim() && /^[a-f0-9]{64}$/i.test(ledger.fingerprint) && hash(base) === ledger.fingerprint; if (!valid) throw new Error("BEAT_FULFILLMENT_INTEGRITY_FAILED"); return ledger; }
export async function readBeatFulfillmentLedger(root: string, ledgerId: string) { const ledger = await read<BeatFulfillmentLedger>(file(root, ledgerId)); return ledger ? assertBeatFulfillmentLedgerIntegrity(ledger, ledgerId) : null; }
export async function createBeatFulfillmentLedger(input: { root: string; projectSlug: string; sceneId: string; sourceRefs: readonly string[]; beats: ReadonlyArray<{ beatId: string; label: string; required: boolean }> }): Promise<BeatFulfillmentLedger> { if (!input.projectSlug.trim() || !input.sceneId.trim()) throw new Error("BEAT_FIELDS_REQUIRED"); if (!input.sourceRefs.length) throw new Error("BEAT_SOURCE_REQUIRED"); if (!input.beats.length) throw new Error("BEAT_PLAN_REQUIRED"); const ledgerId = `beat-ledger-${input.sceneId}`; const existing = await readBeatFulfillmentLedger(input.root, ledgerId); if (existing) return existing; const now = new Date().toISOString(); const base = { schemaVersion: "beat-fulfillment-ledger.v1" as const, ledgerId, projectSlug: input.projectSlug, sceneId: input.sceneId, sourceRefs: [...input.sourceRefs], beats: input.beats.map((beat) => ({ ...beat, status: "planned" as const, evidenceRefs: [], reason: null, updatedAt: now })), status: "open" as const, createdAt: now, updatedAt: now }; const ledger = { ...base, fingerprint: hash(base) }; await write(file(input.root, ledgerId), ledger); return ledger; }
export async function transitionBeatFulfillment(root: string, ledgerId: string, beatId: string, input: { status: BeatFulfillmentStatus; evidenceRefs?: readonly string[]; reason?: string }): Promise<BeatFulfillmentLedger> { const ledger = await readBeatFulfillmentLedger(root, ledgerId); if (!ledger) throw new Error("BEAT_LEDGER_NOT_FOUND"); const target = ledger.beats.find((beat) => beat.beatId === beatId); if (!target) throw new Error("BEAT_NOT_FOUND"); if (input.status === "evidenced" && !input.evidenceRefs?.length) throw new Error("BEAT_EVIDENCE_REQUIRED"); if ((input.status === "missed" || input.status === "invalidated") && !input.reason?.trim()) throw new Error("BEAT_REASON_REQUIRED"); const now = new Date().toISOString(); const beats = ledger.beats.map((beat) => beat.beatId === beatId ? { ...beat, status: input.status, evidenceRefs: input.evidenceRefs ? [...input.evidenceRefs] : beat.evidenceRefs, reason: input.reason ?? beat.reason, updatedAt: now } : beat); const required = beats.filter((beat) => beat.required); const blocked = required.some((beat) => beat.status === "missed" || beat.status === "invalidated"); const complete = required.every((beat) => beat.status === "evidenced"); const base = { ...ledger, beats, status: blocked ? "blocked" as const : complete ? "completed" as const : "open" as const, updatedAt: now }; const next = { ...base, fingerprint: hash({ ...base, fingerprint: undefined }) }; await write(file(root, ledgerId), next); return next; }
