import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { resolveInside } from "./pathSafety.js";

export interface CandidateConvergence { schemaVersion: "candidate-convergence.v1"; runId: string; projectSlug: string; assetId: string; targetProblem: string; stopAfterUnimproved: number; iterations: Array<{ candidateId: string; similarityFingerprint: string; problemScore: number; preserved: string[]; regressions: string[]; authorJudgment: string; reviewVerdict: "red" | "blue" | "synthesis"; evidenceRefs: string[]; improved: boolean; }>; status: "active" | "paused" | "converged"; stopReason: string | null; sourceRefs: string[]; createdAt: string; updatedAt: string; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function file(root: string, id: string) { return resolveInside(root, `sessions/candidate-convergence/${id}.json`); }
async function read<T>(target: string): Promise<T | null> { try { return JSON.parse(await fs.readFile(target, "utf8")) as T; } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return null; throw e; } }
async function write(target: string, value: unknown) { await fs.mkdir(path.dirname(target), { recursive: true }); const tmp = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await fs.rename(tmp, target); }
export function assertCandidateConvergenceIntegrity(run: CandidateConvergence, expectedRunId?: string): CandidateConvergence { const { fingerprint: _fingerprint, ...base } = run; const ids = new Set<string>(); const validIterations = Array.isArray(run.iterations) && run.iterations.every((item) => { const valid = typeof item.candidateId === "string" && item.candidateId.trim() && !ids.has(item.candidateId) && typeof item.similarityFingerprint === "string" && item.similarityFingerprint.trim() && Number.isFinite(item.problemScore) && Array.isArray(item.preserved) && item.preserved.every((value) => typeof value === "string" && value.trim()) && Array.isArray(item.regressions) && item.regressions.every((value) => typeof value === "string" && value.trim()) && typeof item.authorJudgment === "string" && item.authorJudgment.trim() && ["red", "blue", "synthesis"].includes(item.reviewVerdict) && Array.isArray(item.evidenceRefs) && item.evidenceRefs.length > 0 && item.evidenceRefs.every((ref) => typeof ref === "string" && ref.trim()) && typeof item.improved === "boolean"; ids.add(item.candidateId); return valid; }); const validStatus = ["active", "paused", "converged"].includes(run.status) && (run.status === "active" ? run.stopReason === null : typeof run.stopReason === "string" && run.stopReason.trim().length > 0); const valid = run.schemaVersion === "candidate-convergence.v1" && (!expectedRunId || run.runId === expectedRunId) && Boolean(run.runId?.trim() && run.projectSlug?.trim() && run.assetId?.trim() && run.targetProblem?.trim()) && Number.isInteger(run.stopAfterUnimproved) && run.stopAfterUnimproved >= 2 && validIterations && validStatus && Array.isArray(run.sourceRefs) && run.sourceRefs.length > 0 && run.sourceRefs.every((ref) => typeof ref === "string" && ref.trim()) && typeof run.createdAt === "string" && run.createdAt.trim() && typeof run.updatedAt === "string" && run.updatedAt.trim() && /^[a-f0-9]{64}$/i.test(run.fingerprint) && hash(base) === run.fingerprint; if (!valid) throw new Error("CONVERGENCE_INTEGRITY_FAILED"); return run; }
export async function readCandidateConvergence(root: string, runId: string) { const run = await read<CandidateConvergence>(file(root, runId)); return run ? assertCandidateConvergenceIntegrity(run, runId) : null; }
export async function createCandidateConvergence(input: { root: string; projectSlug: string; assetId: string; targetProblem: string; stopAfterUnimproved: number; sourceRefs: readonly string[] }): Promise<CandidateConvergence> { if (!input.projectSlug.trim() || !input.assetId.trim() || !input.targetProblem.trim()) throw new Error("CONVERGENCE_FIELDS_REQUIRED"); if (!Number.isInteger(input.stopAfterUnimproved) || input.stopAfterUnimproved < 2) throw new Error("CONVERGENCE_STOP_THRESHOLD_INVALID"); if (!input.sourceRefs.length || input.sourceRefs.some((ref) => !ref.trim())) throw new Error("CONVERGENCE_SOURCE_REQUIRED"); const runId = `convergence-${input.assetId}`; const existing = await readCandidateConvergence(input.root, runId); if (existing) return existing; const base = { schemaVersion: "candidate-convergence.v1" as const, runId, projectSlug: input.projectSlug, assetId: input.assetId, targetProblem: input.targetProblem, stopAfterUnimproved: input.stopAfterUnimproved, iterations: [], status: "active" as const, stopReason: null, sourceRefs: [...input.sourceRefs], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; const run = { ...base, fingerprint: hash(base) }; await write(file(input.root, runId), run); return run; }
export async function recordCandidateIteration(root: string, runId: string, input: { candidateId: string; similarityFingerprint: string; problemScore: number; preserved: readonly string[]; regressions: readonly string[]; authorJudgment: string; reviewVerdict: "red" | "blue" | "synthesis"; evidenceRefs: readonly string[] }): Promise<CandidateConvergence> { const run = await readCandidateConvergence(root, runId); if (!run) throw new Error("CONVERGENCE_RUN_NOT_FOUND"); if (!input.candidateId.trim() || !input.authorJudgment.trim() || !input.evidenceRefs.length) throw new Error("CONVERGENCE_EVIDENCE_REQUIRED"); if (!input.similarityFingerprint.trim() || !Number.isFinite(input.problemScore) || input.evidenceRefs.some((ref) => !ref.trim())) throw new Error("CONVERGENCE_ITERATION_INVALID"); if (run.iterations.some((iteration) => iteration.candidateId === input.candidateId)) throw new Error("CONVERGENCE_CANDIDATE_DUPLICATE"); if (run.status !== "active") return run; const previous = run.iterations.at(-1); const improved = !previous || input.problemScore < previous.problemScore; const iteration = { candidateId: input.candidateId, similarityFingerprint: input.similarityFingerprint, problemScore: input.problemScore, preserved: [...input.preserved], regressions: [...input.regressions], authorJudgment: input.authorJudgment, reviewVerdict: input.reviewVerdict, evidenceRefs: [...input.evidenceRefs], improved }; const iterations = [...run.iterations, iteration]; const recent = iterations.slice(-run.stopAfterUnimproved); const unimproved = recent.length >= run.stopAfterUnimproved && recent.every((item) => !item.improved); const oscillating = iterations.length >= 3 && iterations.slice(-3).map((item) => item.reviewVerdict).join(",") === "red,blue,red" || iterations.length >= 3 && iterations.slice(-3).map((item) => item.reviewVerdict).join(",") === "blue,red,blue"; const stopReason = unimproved ? "UNIMPROVED_TARGET" : oscillating ? "REVIEW_OSCILLATION" : null; const base = { ...run, iterations, status: stopReason ? "paused" as const : "active" as const, stopReason, updatedAt: new Date().toISOString() }; const next = { ...base, fingerprint: hash({ ...base, fingerprint: undefined }) }; await write(file(root, runId), next); return next; }
