import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { resolveInside } from "./pathSafety.js";

export interface ChapterContinuationRun { schemaVersion: "chapter-continuation-run.v1"; runId: string; projectSlug: string; chapterId: string; inputManifest: { outlineVersionId: string; sceneId: string; contextFingerprint: string }; sourceRefs: string[]; checkpointIds: string[]; createdAt: string; fingerprint: string; }
export interface ContinuationCheckpoint { schemaVersion: "continuation-checkpoint.v1"; checkpointId: string; runId: string; baselineTail: string; fulfilledBeatIds: string[]; pendingBeatIds: string[]; candidateText: string; validationStatus: "passed" | "failed"; validationRefs: string[]; continuationToken: string; status: "verified" | "unverified"; createdAt: string; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function runFile(root: string, id: string) { return resolveInside(root, `sessions/chapter-continuations/${id}.json`); }
function checkpointFile(root: string, id: string) { return resolveInside(root, `sessions/continuation-checkpoints/${id}.json`); }
export function assertChapterContinuationRunIntegrity(run: ChapterContinuationRun, expectedRunId?: string): ChapterContinuationRun { const { fingerprint: _fingerprint, ...base } = run; const valid = run.schemaVersion === "chapter-continuation-run.v1" && (!expectedRunId || run.runId === expectedRunId) && Boolean(run.runId?.trim() && run.projectSlug?.trim() && run.chapterId?.trim() && run.inputManifest?.outlineVersionId?.trim() && run.inputManifest?.sceneId?.trim() && run.inputManifest?.contextFingerprint?.trim()) && Array.isArray(run.sourceRefs) && run.sourceRefs.length > 0 && run.sourceRefs.every((ref) => typeof ref === "string" && ref.trim()) && Array.isArray(run.checkpointIds) && run.checkpointIds.every((id) => typeof id === "string" && id.trim()) && typeof run.createdAt === "string" && run.createdAt.trim() && /^[a-f0-9]{64}$/i.test(run.fingerprint) && hash(base) === run.fingerprint; if (!valid) throw new Error("CONTINUATION_RUN_INTEGRITY_FAILED"); return run; }
export function assertContinuationCheckpointIntegrity(checkpoint: ContinuationCheckpoint, expectedCheckpointId?: string): ContinuationCheckpoint { const { fingerprint: _fingerprint, ...base } = checkpoint; const valid = checkpoint.schemaVersion === "continuation-checkpoint.v1" && (!expectedCheckpointId || checkpoint.checkpointId === expectedCheckpointId) && Boolean(checkpoint.checkpointId?.trim() && checkpoint.runId?.trim() && checkpoint.baselineTail?.trim() && checkpoint.candidateText?.trim() && checkpoint.continuationToken?.trim()) && Array.isArray(checkpoint.fulfilledBeatIds) && checkpoint.fulfilledBeatIds.every((id) => typeof id === "string" && id.trim()) && Array.isArray(checkpoint.pendingBeatIds) && checkpoint.pendingBeatIds.every((id) => typeof id === "string" && id.trim()) && !checkpoint.fulfilledBeatIds.some((id) => checkpoint.pendingBeatIds.includes(id)) && ["passed", "failed"].includes(checkpoint.validationStatus) && Array.isArray(checkpoint.validationRefs) && checkpoint.validationRefs.every((ref) => typeof ref === "string" && ref.trim()) && (checkpoint.validationStatus !== "passed" || checkpoint.validationRefs.length > 0) && ["verified", "unverified"].includes(checkpoint.status) && checkpoint.status === (checkpoint.validationStatus === "passed" && checkpoint.validationRefs.length > 0 ? "verified" : "unverified") && typeof checkpoint.createdAt === "string" && checkpoint.createdAt.trim() && /^[a-f0-9]{64}$/i.test(checkpoint.fingerprint) && hash(base) === checkpoint.fingerprint; if (!valid) throw new Error("CONTINUATION_CHECKPOINT_INTEGRITY_FAILED"); return checkpoint; }
async function read<T>(target: string, validator?: (value: T) => T): Promise<T | null> { try { const value = JSON.parse(await fs.readFile(target, "utf8")) as T; return validator ? validator(value) : value; } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return null; throw e; } }
async function write(target: string, value: unknown) { await fs.mkdir(path.dirname(target), { recursive: true }); const tmp = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await fs.rename(tmp, target); }
export async function readChapterContinuationRun(root: string, runId: string) { return read<ChapterContinuationRun>(runFile(root, runId), (value) => assertChapterContinuationRunIntegrity(value, runId)); }
export async function createChapterContinuationRun(input: { root: string; projectSlug: string; chapterId: string; inputManifest: { outlineVersionId: string; sceneId: string; contextFingerprint: string }; sourceRefs: readonly string[] }): Promise<ChapterContinuationRun> { if (!input.projectSlug.trim() || !input.chapterId.trim() || !input.inputManifest.outlineVersionId.trim() || !input.inputManifest.sceneId.trim() || !input.inputManifest.contextFingerprint.trim()) throw new Error("CONTINUATION_MANIFEST_REQUIRED"); if (!input.sourceRefs.length || input.sourceRefs.some((ref) => !ref.trim())) throw new Error("CONTINUATION_SOURCE_REQUIRED"); const runId = `continuation-${input.chapterId}`; const existing = await readChapterContinuationRun(input.root, runId); if (existing) return existing; const base = { schemaVersion: "chapter-continuation-run.v1" as const, runId, projectSlug: input.projectSlug, chapterId: input.chapterId, inputManifest: input.inputManifest, sourceRefs: [...input.sourceRefs], checkpointIds: [], createdAt: new Date().toISOString() }; const run = { ...base, fingerprint: hash(base) }; await write(runFile(input.root, runId), run); return run; }
export async function saveContinuationCheckpoint(root: string, runId: string, input: { baselineTail: string; fulfilledBeatIds: readonly string[]; pendingBeatIds: readonly string[]; candidateText: string; validationStatus: "passed" | "failed"; validationRefs: readonly string[]; continuationToken: string }): Promise<ContinuationCheckpoint> { const run = await readChapterContinuationRun(root, runId); if (!run) throw new Error("CONTINUATION_RUN_NOT_FOUND"); if (!input.baselineTail.trim() || !input.candidateText.trim() || !input.continuationToken.trim()) throw new Error("CONTINUATION_CHECKPOINT_FIELDS_REQUIRED"); if (input.fulfilledBeatIds.some((id) => input.pendingBeatIds.includes(id))) throw new Error("CONTINUATION_BEAT_STATE_CONFLICT"); if (input.validationRefs.some((ref) => !ref.trim())) throw new Error("CONTINUATION_VALIDATION_EVIDENCE_REQUIRED"); const checkpointId = `checkpoint-${runId}-${run.checkpointIds.length + 1}`; const base = { schemaVersion: "continuation-checkpoint.v1" as const, checkpointId, runId, baselineTail: input.baselineTail, fulfilledBeatIds: [...input.fulfilledBeatIds], pendingBeatIds: [...input.pendingBeatIds], candidateText: input.candidateText, validationStatus: input.validationStatus, validationRefs: [...input.validationRefs], continuationToken: input.continuationToken, status: input.validationStatus === "passed" && input.validationRefs.length > 0 ? "verified" as const : "unverified" as const, createdAt: new Date().toISOString() }; const checkpoint = { ...base, fingerprint: hash(base) }; await write(checkpointFile(root, checkpointId), checkpoint); const nextRun = { ...run, checkpointIds: [...run.checkpointIds, checkpointId] }; await write(runFile(root, runId), { ...nextRun, fingerprint: hash({ ...nextRun, fingerprint: undefined }) }); return checkpoint; }
export async function resumeFromVerifiedCheckpoint(root: string, runId: string): Promise<ContinuationCheckpoint> { const run = await readChapterContinuationRun(root, runId); if (!run) throw new Error("CONTINUATION_RUN_NOT_FOUND"); for (const checkpointId of [...run.checkpointIds].reverse()) { const checkpoint = await read<ContinuationCheckpoint>(checkpointFile(root, checkpointId), (value) => assertContinuationCheckpointIntegrity(value, checkpointId)); if (checkpoint?.status === "verified") return checkpoint; } throw new Error("CONTINUATION_CHECKPOINT_NOT_VERIFIED"); }
