import crypto from "node:crypto";

export type CharacterDocumentCategory = "character-entity" | "character-handbook" | "cover-plan" | "chapter" | "relationship-plan" | "source-asset" | "unknown";
export interface CharacterIdentity { schemaVersion: "character-identity.v1"; projectSlug: string; entityId: string; displayName: string; aliases: string[]; narrativeIdentity: string; sourceRefs: string[]; fingerprint: string; }
export interface CharacterDocumentClassification { schemaVersion: "character-document-classification.v1"; path: string; title: string; category: CharacterDocumentCategory; kind: "character-node" | "source-asset"; isCharacterNode: boolean; sourceRefs: string[]; fingerprint: string; }
export interface CharacterCastAdmission { schemaVersion: "character-cast-admission.v1"; status: "admitted"; entityId: string; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
export function registerCharacterIdentity(input: { projectSlug: string; entityId: string; displayName: string; aliases: readonly string[]; narrativeIdentity: string; sourceRefs: readonly string[] }): CharacterIdentity { if (!input.projectSlug.trim() || !input.entityId.trim() || !input.displayName.trim() || !input.narrativeIdentity.trim()) throw new Error("CHARACTER_IDENTITY_FIELDS_REQUIRED"); if (!input.aliases.length || !input.sourceRefs.length) throw new Error("CHARACTER_IDENTITY_SOURCE_REQUIRED"); const base = { schemaVersion: "character-identity.v1" as const, projectSlug: input.projectSlug, entityId: input.entityId, displayName: input.displayName, aliases: [...new Set(input.aliases)], narrativeIdentity: input.narrativeIdentity, sourceRefs: [...input.sourceRefs] }; return { ...base, fingerprint: hash(base) }; }
export function admitCharacterToCast(identity: Pick<CharacterIdentity, "entityId" | "displayName" | "aliases" | "narrativeIdentity" | "sourceRefs">): CharacterCastAdmission { if (!identity.entityId.trim() || !identity.displayName.trim() || !identity.narrativeIdentity.trim() || !identity.aliases.length || !identity.sourceRefs.length) throw new Error("CHARACTER_IDENTITY_INVALID"); const base = { schemaVersion: "character-cast-admission.v1" as const, status: "admitted" as const, entityId: identity.entityId }; return { ...base, fingerprint: hash({ ...base, sourceRefs: identity.sourceRefs }) }; }
export function classifyCharacterDocument(input: { path: string; title: string; category: CharacterDocumentCategory; sourceRefs: readonly string[] }): CharacterDocumentClassification { if (!input.path.trim() || !input.title.trim()) throw new Error("CHARACTER_DOCUMENT_METADATA_REQUIRED"); if (!input.sourceRefs.length) throw new Error("CHARACTER_DOCUMENT_SOURCE_REQUIRED"); const isCharacterNode = input.category === "character-entity"; const base = { schemaVersion: "character-document-classification.v1" as const, path: input.path, title: input.title, category: input.category, kind: isCharacterNode ? "character-node" as const : "source-asset" as const, isCharacterNode, sourceRefs: [...input.sourceRefs] }; return { ...base, fingerprint: hash(base) }; }
