import crypto from "node:crypto";
export type BeliefStatus = "held" | "challenged" | "resisted" | "reinforced" | "shaken" | "acknowledged" | "transformed" | "relapsed";
export type BeliefEventType = "formed" | "counterevidence" | "resisted" | "reinforced" | "shaken" | "acknowledged" | "behavioral-consequence" | "transformed" | "relapsed";
export interface BeliefEvent { eventId: string; type: BeliefEventType; description: string; evidenceRefs: string[]; pressureRefs?: string[]; costRefs?: string[]; at: string; }
export interface BeliefLifecycle { schemaVersion: "character-belief-lifecycle.v1"; beliefId: string; characterId: string; belief: string; status: BeliefStatus; sourceRefs: string[]; events: BeliefEvent[]; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
const transition: Record<BeliefStatus, BeliefEventType[]> = { held: ["counterevidence", "reinforced", "behavioral-consequence"], challenged: ["resisted", "reinforced", "shaken", "acknowledged", "behavioral-consequence"], resisted: ["counterevidence", "shaken", "reinforced", "acknowledged", "behavioral-consequence"], reinforced: ["counterevidence", "shaken", "behavioral-consequence"], shaken: ["resisted", "acknowledged", "transformed", "relapsed", "behavioral-consequence"], acknowledged: ["transformed", "relapsed", "behavioral-consequence"], transformed: ["relapsed", "behavioral-consequence"], relapsed: ["counterevidence", "shaken", "acknowledged", "behavioral-consequence"] };
const statusFor = (type: BeliefEventType, current: BeliefStatus): BeliefStatus => type === "counterevidence" ? "challenged" : type === "resisted" ? "resisted" : type === "reinforced" ? "reinforced" : type === "shaken" ? "shaken" : type === "acknowledged" ? "acknowledged" : type === "transformed" ? "transformed" : type === "relapsed" ? "relapsed" : current;
export function createBeliefLifecycle(input: { beliefId: string; characterId: string; belief: string; sourceRefs: readonly string[] }): BeliefLifecycle { if (!input.beliefId.trim() || !input.characterId.trim() || !input.belief.trim()) throw new Error("BELIEF_CONTEXT_REQUIRED"); if (!input.sourceRefs.length) throw new Error("BELIEF_SOURCE_REQUIRED"); const event: BeliefEvent = { eventId: `belief-event-${crypto.randomUUID()}`, type: "formed", description: "belief recorded", evidenceRefs: [...input.sourceRefs], at: new Date().toISOString() }; const base = { schemaVersion: "character-belief-lifecycle.v1" as const, beliefId: input.beliefId, characterId: input.characterId, belief: input.belief, status: "held" as const, sourceRefs: [...input.sourceRefs], events: [event] }; return { ...base, fingerprint: hash(base) }; }
export function recordBeliefEvent(record: BeliefLifecycle, input: { type: BeliefEventType; description: string; evidenceRefs: readonly string[]; pressureRefs?: readonly string[]; costRefs?: readonly string[] }): BeliefLifecycle { if (!input.description.trim() || !input.evidenceRefs.length) throw new Error("BELIEF_EVENT_EVIDENCE_REQUIRED"); if (!transition[record.status].includes(input.type)) throw new Error("BELIEF_EVENT_TRANSITION_INVALID"); if (input.type === "acknowledged" && !record.events.some((event) => event.type === "behavioral-consequence")) throw new Error("BELIEF_BEHAVIORAL_CONSEQUENCE_REQUIRED"); if (input.type === "relapsed" && (!input.pressureRefs?.length || !input.costRefs?.length)) throw new Error("BELIEF_RELAPSE_PRESSURE_REQUIRED"); const event: BeliefEvent = { eventId: `belief-event-${crypto.randomUUID()}`, type: input.type, description: input.description, evidenceRefs: [...input.evidenceRefs], ...(input.pressureRefs?.length ? { pressureRefs: [...input.pressureRefs] } : {}), ...(input.costRefs?.length ? { costRefs: [...input.costRefs] } : {}), at: new Date().toISOString() }; const base = { ...record, status: statusFor(input.type, record.status), events: [...record.events, event], sourceRefs: [...new Set([...record.sourceRefs, ...input.evidenceRefs])] }; return { ...base, fingerprint: hash(base) }; }
