export function scheduleClosure(input: { chaptersToEnding: number; obligations: Array<{ id: string; dependentCharacter: string; payoffChapter: number }>; climaxCapacity: number }): { status: "balanced" | "congested"; conflicts: string[]; options: string[] } {
  const climax = input.obligations.filter((item) => item.payoffChapter >= input.chaptersToEnding).length;
  const characterCounts = new Map<string, number>(); for (const item of input.obligations) characterCounts.set(item.dependentCharacter, (characterCounts.get(item.dependentCharacter) || 0) + 1);
  const conflicts = [...(climax > input.climaxCapacity ? ["CLIMAX_CAPACITY"] : []), ...([...characterCounts.values()].some((count) => count >= 5) ? ["SINGLE_CHARACTER_CONCENTRATION"] : [])];
  return { status: conflicts.length ? "congested" : "balanced", conflicts, options: conflicts.length ? ["move_earlier", "combine", "partial_payoff", "honest_neutralize"] : [] };
}

export function resolveWindowConflict(input: { reservedWindow: string; newPlotLoad: number; capacity: number; alternatives: readonly string[] }): { status: "fit" | "conflict"; options: string[] } { return input.newPlotLoad <= input.capacity ? { status: "fit", options: [] } : { status: "conflict", options: [...input.alternatives] }; }
export function adaptReminder(input: { chaptersSince: number; chapterWords: number; clueSalience: number; readerRecall: number }): { status: "reactivate" | "no_repeat"; method: string } { const risk = input.chapterWords > 15000 || input.readerRecall < 0.5; return risk && input.clueSalience < 0.8 ? { status: "reactivate", method: "new_consequence" } : { status: "no_repeat", method: "preserve" }; }
export function detectAnswerLeak(input: { repeatedEmphasis: number; competingHypotheses: number; saturationThreshold: number }): { status: "safe" | "leak_risk"; options: string[] } { return input.repeatedEmphasis >= input.saturationThreshold && input.competingHypotheses <= 1 ? { status: "leak_risk", options: ["lower_salience", "change_direction", "restore_competition"] } : { status: "safe", options: [] }; }
export function settleSharedObject(input: { subclaims: Array<{ id: string; answered: boolean }> }): { settled: string[]; open: string[] } { return { settled: input.subclaims.filter((claim) => claim.answered).map((claim) => claim.id), open: input.subclaims.filter((claim) => !claim.answered).map((claim) => claim.id) }; }
export function evaluatePayoffForm(input: { form: "choice" | "object_function" | "power_shift" | "monologue"; irreversibleConsequence: boolean; distinctFromPrior: boolean }): { status: "strong" | "weak" } { return { status: input.form !== "monologue" && input.irreversibleConsequence && input.distinctFromPrior ? "strong" : "weak" }; }
export function evaluateClosureScene(input: { answerProvided: boolean; activeChoice: boolean; consequence: boolean; relationshipChanged: boolean; goalChanged: boolean; resourceChanged: boolean }): { status: "complete" | "information_only" } { return { status: input.answerProvided && input.activeChoice && input.consequence && (input.relationshipChanged || input.goalChanged || input.resourceChanged) ? "complete" : "information_only" }; }
export function propagateClosure(input: { writes: Array<{ domain: string; succeeded: boolean }>; obligationId: string }): { status: "settled" | "pending"; rollback: boolean; failedDomains: string[] } { const failedDomains = input.writes.filter((write) => !write.succeeded).map((write) => write.domain); return { status: failedDomains.length ? "pending" : "settled", rollback: failedDomains.length > 0, failedDomains }; }
export function evaluateNarrativeInterest(input: { strongPromises: number; settledPromises: number; postponements: number; newValueAdded: number }): { status: "balanced" | "interest_due"; prioritizeNearTerm: boolean } { const due = input.strongPromises - input.settledPromises > 10 && input.postponements > input.newValueAdded; return { status: due ? "interest_due" : "balanced", prioritizeNearTerm: due }; }
