import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { resolveInside } from "./pathSafety.js";
export interface CraftPattern { schemaVersion: "craft-pattern.v1"; patternId: string; projectSlug: string; name: string; mechanism: string; narrativeFunction: string; applicability: string[]; counterexamples: string[]; sourceEnvelopeIds: string[]; evidenceRefs: string[]; lifecycle: "candidate" | "approved" | "probation" | "validated" | "rejected" | "retired"; structuralMechanism?: string; readerEffect?: string; minimalPositiveExample?: string; counterExample?: string; failureConditions?: string[]; genreBoundaries?: string[]; sourceRecordId?: string; sourceRefs?: string[]; status: "candidate"; createdAt: string; updatedAt: string; promotion?: { experimentId: string; actor: string; reason: string; promotedAt: string }; validation?: { experimentId: string; actor: string; reason: string; validatedAt: string }; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function file(root: string, id: string) { return resolveInside(root, `sessions/craft-patterns/${id}.json`); }
async function read<T>(target: string): Promise<T | null> { try { return JSON.parse(await fs.readFile(target, "utf8")) as T; } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return null; throw e; } }
async function write(target: string, value: unknown) { await fs.mkdir(path.dirname(target), { recursive: true }); const tmp = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await fs.rename(tmp, target); }
export async function readCraftPattern(root: string, patternId: string) { return read<CraftPattern>(file(root, patternId)); }
export async function listCraftPatterns(root: string, projectSlug: string): Promise<CraftPattern[]> { let names: string[]; try { names = await fs.readdir(resolveInside(root, "sessions/craft-patterns")); } catch { return []; } const values = await Promise.all(names.filter((n) => n.endsWith(".json")).map((n) => readCraftPattern(root, n.slice(0, -5)))); return values.filter((p): p is CraftPattern => Boolean(p && p.projectSlug === projectSlug)); }
export async function createCraftPattern(input: any): Promise<CraftPattern> { const modern = Boolean(input.structuralMechanism); const mechanism = modern ? input.structuralMechanism : input.mechanism; const narrativeFunction = modern ? input.readerEffect : input.narrativeFunction; const applicability = modern ? input.applicableScenes : input.applicability; const counterexamples = modern ? [input.counterExample] : input.counterexamples; const sourceEnvelopeIds = modern ? [input.sourceRecordId] : input.sourceEnvelopeIds; const evidenceRefs = modern ? input.sourceRefs : input.evidenceRefs; if (!input.projectSlug?.trim() || !input.name?.trim() || !mechanism?.trim()) throw new Error("CRAFT_FIELDS_REQUIRED"); if (!evidenceRefs?.length) throw new Error(modern ? "CRAFT_SOURCE_REQUIRED" : "CRAFT_PATTERN_EVIDENCE_REQUIRED"); if (!applicability?.length || (modern && !counterexamples?.length)) throw new Error("CRAFT_EXPLANATION_REQUIRED"); if (/像.+作者|像某作者|in the style of/i.test(input.name)) throw new Error("CRAFT_AUTHOR_IMPERSONATION_FORBIDDEN"); if (modern && (input.minimalPositiveExample.length > 1000 || input.counterExample.length > 1000)) throw new Error("CRAFT_EXAMPLE_TOO_LONG"); const patternId = `craft-pattern-${hash({ projectSlug: input.projectSlug, name: input.name }).slice(0, 20)}`; const existing = await readCraftPattern(input.root, patternId); if (existing) return existing; const now = new Date().toISOString(); const base = { schemaVersion: "craft-pattern.v1" as const, patternId, projectSlug: input.projectSlug, name: input.name, mechanism, narrativeFunction, applicability: [...applicability], counterexamples: [...counterexamples], sourceEnvelopeIds: [...sourceEnvelopeIds], evidenceRefs: [...evidenceRefs], lifecycle: "candidate" as const, ...(modern ? { structuralMechanism: mechanism, readerEffect: input.readerEffect, minimalPositiveExample: input.minimalPositiveExample, counterExample: input.counterExample, failureConditions: [...input.failureConditions], genreBoundaries: [...input.genreBoundaries], sourceRecordId: input.sourceRecordId, sourceRefs: [...input.sourceRefs] } : {}), status: "candidate" as const, createdAt: now, updatedAt: now }; const pattern = { ...base, fingerprint: hash(base) }; await write(file(input.root, patternId), pattern); return pattern; }
export async function approveCraftPattern(input: { root: string; patternId: string; actor: string; reason: string }): Promise<CraftPattern> { if (!input.actor.trim() || !input.reason.trim()) throw new Error("CRAFT_PATTERN_APPROVAL_REQUIRED"); const pattern = await readCraftPattern(input.root, input.patternId); if (!pattern) throw new Error("CRAFT_PATTERN_NOT_FOUND"); if (pattern.lifecycle !== "candidate") throw new Error("CRAFT_PATTERN_ALREADY_DECIDED"); const base = { ...pattern, lifecycle: "approved" as const, approval: { actor: input.actor, reason: input.reason, approvedAt: new Date().toISOString() }, updatedAt: new Date().toISOString() }; const next = { ...base, fingerprint: hash(base) }; await write(file(input.root, input.patternId), next); return next; }
