import crypto from "node:crypto";

export type RevocableArtifactKind = "pattern" | "context-cache" | "candidate" | "published-prose";
export type RevocableArtifactStatus = "active" | "published" | "invalidated" | "historical-source-retained";
export interface RevocableCraftArtifact { artifactId: string; kind: RevocableArtifactKind; sourceIds: string[]; status: RevocableArtifactStatus; historicalSourceFingerprint?: string; }
export interface CraftRevocationPropagationInput { sourceId: string; eventId: string; reason: string; evidenceRefs: string[]; sourceFingerprint: string; artifacts: RevocableCraftArtifact[]; sourceRefs: string[]; }
export interface CraftRevocationPropagationResult { schemaVersion: "craft-revocation-propagation.v1"; sourceId: string; eventId: string; sourceFingerprint: string; status: "propagated"; invalidatedArtifactIds: string[]; retainedHistoricalArtifactIds: string[]; artifacts: RevocableCraftArtifact[]; reason: string; evidenceRefs: string[]; sourceRefs: string[]; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
export function propagateCraftSourceRevocation(input: CraftRevocationPropagationInput): CraftRevocationPropagationResult { if (!input.sourceId.trim() || !input.eventId.trim() || !input.sourceFingerprint.trim()) throw new Error("CRAFT_REVOCATION_CONTEXT_REQUIRED"); if (!input.reason.trim() || !input.evidenceRefs.length || !input.sourceRefs.length) throw new Error("CRAFT_REVOCATION_EVIDENCE_REQUIRED"); const invalidatedArtifactIds: string[] = []; const retainedHistoricalArtifactIds: string[] = []; const artifacts = input.artifacts.map((artifact) => { if (!artifact.sourceIds.includes(input.sourceId)) return { ...artifact, sourceIds: [...artifact.sourceIds] }; if (artifact.kind === "published-prose") { retainedHistoricalArtifactIds.push(artifact.artifactId); return { ...artifact, sourceIds: [...artifact.sourceIds], status: "historical-source-retained" as const, historicalSourceFingerprint: input.sourceFingerprint }; } invalidatedArtifactIds.push(artifact.artifactId); return { ...artifact, sourceIds: [...artifact.sourceIds], status: "invalidated" as const }; }); const base = { schemaVersion: "craft-revocation-propagation.v1" as const, sourceId: input.sourceId, eventId: input.eventId, sourceFingerprint: input.sourceFingerprint, status: "propagated" as const, invalidatedArtifactIds, retainedHistoricalArtifactIds, artifacts, reason: input.reason, evidenceRefs: [...input.evidenceRefs], sourceRefs: [...input.sourceRefs] }; return { ...base, fingerprint: hash(base) }; }
