import { describe, expect, it } from "vitest";
import { assertCraftBoundaryIntegrity, createCraftBoundary, evaluateCraftBoundaryMatch } from "./craftBoundary.js";

const boundary = { patternId: "p1", genres: ["mystery"], chapterFunctions: ["investigation"], narrativeDistances: ["close"], characterStages: ["early-distrust"], targetReaders: ["adult"], forbiddenConditions: ["comedy relief"], counterexamples: ["reconciliation scene"], sourceRefs: ["pattern://p1"] };
describe("craft applicability boundary", () => {
  it("stores explicit boundaries and counterexample", () => { const result = createCraftBoundary(boundary); expect(result.counterexamples).toEqual(["reconciliation scene"]); });
  it("allows matching context and downgrades mismatch", () => { const b = createCraftBoundary(boundary); expect(evaluateCraftBoundaryMatch(b, { genre: "mystery", chapterFunction: "investigation", narrativeDistance: "close", characterStage: "early-distrust", targetReader: "adult", conditions: [] }).decision).toBe("use"); expect(evaluateCraftBoundaryMatch(b, { genre: "romance", chapterFunction: "reconciliation", narrativeDistance: "omniscient", characterStage: "late-trust", targetReader: "young", conditions: ["comedy relief"] }).decision).toBe("do-not-use"); });
  it("requires counterexample and evidence", () => { expect(() => createCraftBoundary({ ...boundary, counterexamples: [] })).toThrow("CRAFT_BOUNDARY_COUNTEREXAMPLE_REQUIRED"); expect(() => createCraftBoundary({ ...boundary, sourceRefs: [] })).toThrow("CRAFT_BOUNDARY_SOURCE_REQUIRED"); });
  it("rejects blank boundary/context values and tampering", () => { expect(() => createCraftBoundary({ ...boundary, genres: [" "] })).toThrow("CRAFT_BOUNDARY_DIMENSIONS_REQUIRED"); const b = createCraftBoundary(boundary); expect(() => evaluateCraftBoundaryMatch({ ...b, targetReaders: ["young"] }, { genre: "mystery", chapterFunction: "investigation", narrativeDistance: "close", characterStage: "early-distrust", targetReader: "adult", conditions: [] })).toThrow("CRAFT_BOUNDARY_INTEGRITY_FAILED"); expect(() => evaluateCraftBoundaryMatch(b, { genre: " ", chapterFunction: "investigation", narrativeDistance: "close", characterStage: "early-distrust", targetReader: "adult", conditions: [] })).toThrow("CRAFT_BOUNDARY_CONTEXT_REQUIRED"); expect(() => assertCraftBoundaryIntegrity({ ...b, patternId: "tampered" })).toThrow("CRAFT_BOUNDARY_INTEGRITY_FAILED"); });
});
