import crypto from "node:crypto";

export interface CraftProvenanceSource { snapshotId: string; sourceFamily: string; accessClass: "public" | "private" | "restricted" | "unknown"; fingerprint: string; independentGroup: string; }
export interface CraftProvenanceTransformation { kind: "abstract-mechanism" | "surface-rewrite" | "scope-limitation" | "anti-imitation"; description: string; evidenceRefs: string[]; }
export interface CraftProvenanceInput { candidateId: string; patternId: string; sceneId: string; sources: CraftProvenanceSource[]; transformations: CraftProvenanceTransformation[]; evaluationRefs: string[]; adoptionChangeSetRefs: string[]; proseVersionRefs: string[]; qualityReportRefs: string[]; releaseSnapshotRefs: string[]; sourceRefs: string[]; }
export interface CraftProvenanceBundle { schemaVersion: "craft-provenance.v1"; candidateId: string; patternId: string; sceneId: string; sources: CraftProvenanceSource[]; sourceFamilies: string[]; independentEvidenceGroups: string[]; transformations: CraftProvenanceTransformation[]; artifacts: { evaluationRefs: string[]; adoptionChangeSetRefs: string[]; proseVersionRefs: string[]; qualityReportRefs: string[]; releaseSnapshotRefs: string[] }; sourceRefs: string[]; fingerprint: string; }
export type CraftProvenanceProjection = Omit<CraftProvenanceBundle, "sources" | "sourceFamilies" | "sourceRefs"> & { sources: CraftProvenanceSource[]; sourceFamilies: string[]; sourceRefs: string[] };
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
function required(value: readonly unknown[], code: string) { if (!value.length) throw new Error(code); }
export function assertCraftProvenanceIntegrity(bundle: CraftProvenanceBundle): CraftProvenanceBundle { const { fingerprint, ...content } = bundle; if (bundle.schemaVersion !== "craft-provenance.v1" || hash(content) !== fingerprint) throw new Error("CRAFT_PROVENANCE_INTEGRITY_FAILED"); return bundle; }
export function createCraftProvenanceBundle(input: CraftProvenanceInput): CraftProvenanceBundle { if (!input.candidateId.trim() || !input.patternId.trim() || !input.sceneId.trim()) throw new Error("CRAFT_PROVENANCE_CONTEXT_REQUIRED"); required(input.sources, "CRAFT_PROVENANCE_SOURCE_REQUIRED"); required(input.transformations, "CRAFT_PROVENANCE_TRANSFORMATION_REQUIRED"); required(input.evaluationRefs, "CRAFT_PROVENANCE_EVALUATION_REQUIRED"); required(input.adoptionChangeSetRefs, "CRAFT_PROVENANCE_ADOPTION_REQUIRED"); required(input.proseVersionRefs, "CRAFT_PROVENANCE_PROSE_VERSION_REQUIRED"); required(input.qualityReportRefs, "CRAFT_PROVENANCE_QUALITY_REQUIRED"); required(input.releaseSnapshotRefs, "CRAFT_PROVENANCE_RELEASE_REQUIRED"); required(input.sourceRefs, "CRAFT_PROVENANCE_AUDIT_SOURCE_REQUIRED"); const refs = [...input.evaluationRefs, ...input.adoptionChangeSetRefs, ...input.proseVersionRefs, ...input.qualityReportRefs, ...input.releaseSnapshotRefs, ...input.sourceRefs]; if (refs.some((ref) => !ref.trim())) throw new Error("CRAFT_PROVENANCE_AUDIT_SOURCE_REQUIRED"); if (input.sources.some((source) => !source.snapshotId.trim() || !source.sourceFamily.trim() || !source.fingerprint.trim() || !source.independentGroup.trim() || !["public", "private", "restricted", "unknown"].includes(source.accessClass))) throw new Error("CRAFT_PROVENANCE_SOURCE_METADATA_REQUIRED"); if (input.transformations.some((item) => !item.description.trim() || !item.evidenceRefs.length || item.evidenceRefs.some((ref) => !ref.trim()))) throw new Error("CRAFT_PROVENANCE_TRANSFORMATION_EVIDENCE_REQUIRED"); const base = { schemaVersion: "craft-provenance.v1" as const, candidateId: input.candidateId, patternId: input.patternId, sceneId: input.sceneId, sources: input.sources.map((source) => ({ ...source })), sourceFamilies: [...new Set(input.sources.map((source) => source.sourceFamily))].sort(), independentEvidenceGroups: [...new Set(input.sources.map((source) => source.independentGroup))].sort(), transformations: input.transformations.map((item) => ({ ...item, evidenceRefs: [...item.evidenceRefs] })), artifacts: { evaluationRefs: [...input.evaluationRefs], adoptionChangeSetRefs: [...input.adoptionChangeSetRefs], proseVersionRefs: [...input.proseVersionRefs], qualityReportRefs: [...input.qualityReportRefs], releaseSnapshotRefs: [...input.releaseSnapshotRefs] }, sourceRefs: [...input.sourceRefs] }; return { ...base, fingerprint: hash(base) }; }
export function projectCraftProvenance(bundle: CraftProvenanceBundle, audience: "reader" | "author-audit"): CraftProvenanceProjection { assertCraftProvenanceIntegrity(bundle); if (audience === "reader") return { ...bundle, sources: [], sourceFamilies: [], sourceRefs: [], artifacts: { evaluationRefs: [], adoptionChangeSetRefs: [], proseVersionRefs: [...bundle.artifacts.proseVersionRefs], qualityReportRefs: [...bundle.artifacts.qualityReportRefs], releaseSnapshotRefs: [...bundle.artifacts.releaseSnapshotRefs] } }; return { ...bundle, sources: bundle.sources.map((source) => ({ ...source })), sourceFamilies: [...bundle.sourceFamilies], sourceRefs: [...bundle.sourceRefs], artifacts: { ...bundle.artifacts, evaluationRefs: [...bundle.artifacts.evaluationRefs], adoptionChangeSetRefs: [...bundle.artifacts.adoptionChangeSetRefs], proseVersionRefs: [...bundle.artifacts.proseVersionRefs], qualityReportRefs: [...bundle.artifacts.qualityReportRefs], releaseSnapshotRefs: [...bundle.artifacts.releaseSnapshotRefs] } }; }
