import crypto from "node:crypto";

export type CraftAuthorJudgment = "mechanism" | "surface" | "scene-fit" | "accidental";
export type CraftAttributionStatus = "adopted" | "limited" | "revoked";
export interface CraftAttributionEvent { eventId: string; from: CraftAttributionStatus | null; to: CraftAttributionStatus; actor: string; reason: string; evidenceRefs: string[]; at: string; }
export interface CraftAttribution { schemaVersion: "craft-author-attribution.v1"; attributionId: string; candidateId: string; patternId: string; projectSlug: string; authorId: string; judgment: CraftAuthorJudgment; scope: string; rationale: string; status: CraftAttributionStatus; authority: "context-only"; promotionEligible: false; evidenceRefs: string[]; events: CraftAttributionEvent[]; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
function assertInput(input: { candidateId: string; patternId: string; projectSlug: string; authorId: string; scope: string; rationale: string; evidenceRefs: string[] }) { if (!input.candidateId.trim() || !input.patternId.trim() || !input.projectSlug.trim() || !input.authorId.trim() || !input.scope.trim() || !input.rationale.trim()) throw new Error("CRAFT_ATTRIBUTION_METADATA_REQUIRED"); if (!input.evidenceRefs.length) throw new Error("CRAFT_ATTRIBUTION_EVIDENCE_REQUIRED"); }
function withFingerprint(base: Omit<CraftAttribution, "fingerprint">): CraftAttribution { return { ...base, fingerprint: hash(base) }; }
export function assertCraftAttributionIntegrity(record: CraftAttribution): CraftAttribution { const { fingerprint, ...content } = record; if (record.schemaVersion !== "craft-author-attribution.v1" || !record.attributionId.trim() || !record.candidateId.trim() || !record.patternId.trim() || !record.projectSlug.trim() || !record.authorId.trim() || !["mechanism", "surface", "scene-fit", "accidental"].includes(record.judgment) || !record.evidenceRefs.length || record.evidenceRefs.some((ref) => !ref.trim()) || !record.events.length || hash(content) !== fingerprint) throw new Error("CRAFT_ATTRIBUTION_INTEGRITY_FAILED"); return record; }
export function createCraftAttribution(input: { candidateId: string; patternId: string; projectSlug: string; authorId: string; judgment: CraftAuthorJudgment; scope: string; rationale: string; evidenceRefs: string[] }): CraftAttribution { assertInput(input); if (!input.evidenceRefs.every((ref) => ref.trim()) || !["mechanism", "surface", "scene-fit", "accidental"].includes(input.judgment)) throw new Error("CRAFT_ATTRIBUTION_EVIDENCE_REQUIRED"); const at = new Date().toISOString(); const event: CraftAttributionEvent = { eventId: `craft-attribution-${crypto.randomUUID()}`, from: null, to: "adopted", actor: input.authorId, reason: input.rationale, evidenceRefs: [...input.evidenceRefs], at }; return withFingerprint({ schemaVersion: "craft-author-attribution.v1", attributionId: `attribution-${crypto.randomUUID()}`, candidateId: input.candidateId, patternId: input.patternId, projectSlug: input.projectSlug, authorId: input.authorId, judgment: input.judgment, scope: input.scope, rationale: input.rationale, status: "adopted", authority: "context-only", promotionEligible: false, evidenceRefs: [...input.evidenceRefs], events: [event] }); }
export function transitionCraftAttribution(record: CraftAttribution, input: { target: CraftAttributionStatus | "validated"; actor: string; reason: string; evidenceRefs: string[] }): CraftAttribution { assertCraftAttributionIntegrity(record); if (input.target === "validated") throw new Error("CRAFT_ATTRIBUTION_PROMOTION_FORBIDDEN"); if (!input.actor.trim() || !input.reason.trim()) throw new Error("CRAFT_ATTRIBUTION_EVENT_AUTH_REQUIRED"); if (!input.evidenceRefs.length || input.evidenceRefs.some((ref) => !ref.trim())) throw new Error("CRAFT_ATTRIBUTION_EVENT_EVIDENCE_REQUIRED"); if (record.status === "revoked") throw new Error("CRAFT_ATTRIBUTION_REVOKED_IMMUTABLE"); if (record.status === input.target) throw new Error("CRAFT_ATTRIBUTION_DUPLICATE_EVENT"); const event: CraftAttributionEvent = { eventId: `craft-attribution-${crypto.randomUUID()}`, from: record.status, to: input.target, actor: input.actor, reason: input.reason, evidenceRefs: [...input.evidenceRefs], at: new Date().toISOString() }; const { fingerprint: _fingerprint, ...recordBase } = record; return withFingerprint({ ...recordBase, status: input.target, events: [...record.events, event], evidenceRefs: [...new Set([...record.evidenceRefs, ...input.evidenceRefs])] }); }
