import crypto from "node:crypto";

export type RevocableArtifactKind = "pattern" | "context-cache" | "candidate" | "published-prose";
export type RevocableArtifactStatus = "active" | "published" | "invalidated" | "historical-source-retained";
export interface RevocableCraftArtifact { artifactId: string; kind: RevocableArtifactKind; sourceIds: string[]; status: RevocableArtifactStatus; historicalSourceFingerprint?: string; }
export interface CraftRevocationPropagationInput { sourceId: string; eventId: string; reason: string; evidenceRefs: string[]; sourceFingerprint: string; artifacts: RevocableCraftArtifact[]; sourceRefs: string[]; }
export interface CraftRevocationPropagationResult { schemaVersion: "craft-revocation-propagation.v1"; sourceId: string; eventId: string; sourceFingerprint: string; status: "propagated"; derivativeDisposition: "invalidated" | "retained-history" | "none"; invalidatedArtifactIds: string[]; retainedHistoricalArtifactIds: string[]; artifacts: RevocableCraftArtifact[]; reason: string; evidenceRefs: string[]; sourceRefs: string[]; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
export function assertCraftRevocationPropagationIntegrity(record: CraftRevocationPropagationResult): CraftRevocationPropagationResult { const { fingerprint, ...content } = record; if (record.schemaVersion !== "craft-revocation-propagation.v1" || record.status !== "propagated" || hash(content) !== fingerprint) throw new Error("CRAFT_REVOCATION_INTEGRITY_FAILED"); return record; }
export function propagateCraftSourceRevocation(input: CraftRevocationPropagationInput): CraftRevocationPropagationResult { if (!input.sourceId.trim() || !input.eventId.trim() || !input.sourceFingerprint.trim()) throw new Error("CRAFT_REVOCATION_CONTEXT_REQUIRED"); if (!input.reason.trim() || !input.evidenceRefs.length || input.evidenceRefs.some((ref) => !ref.trim()) || !input.sourceRefs.length || input.sourceRefs.some((ref) => !ref.trim())) throw new Error("CRAFT_REVOCATION_EVIDENCE_REQUIRED"); if (input.artifacts.some((artifact) => !artifact.artifactId.trim() || !["pattern", "context-cache", "candidate", "published-prose"].includes(artifact.kind) || !["active", "published", "invalidated", "historical-source-retained"].includes(artifact.status) || artifact.sourceIds.some((sourceId) => !sourceId.trim()))) throw new Error("CRAFT_REVOCATION_ARTIFACT_INVALID"); if (new Set(input.artifacts.map((artifact) => artifact.artifactId)).size !== input.artifacts.length) throw new Error("CRAFT_REVOCATION_ARTIFACT_DUPLICATE"); const invalidatedArtifactIds: string[] = []; const retainedHistoricalArtifactIds: string[] = []; const artifacts = input.artifacts.map((artifact) => { if (!artifact.sourceIds.includes(input.sourceId)) return { ...artifact, sourceIds: [...artifact.sourceIds] }; if (artifact.kind === "published-prose") { retainedHistoricalArtifactIds.push(artifact.artifactId); return { ...artifact, sourceIds: [...artifact.sourceIds], status: "historical-source-retained" as const, historicalSourceFingerprint: input.sourceFingerprint }; } invalidatedArtifactIds.push(artifact.artifactId); return { ...artifact, sourceIds: [...artifact.sourceIds], status: "invalidated" as const }; }); const derivativeDisposition = invalidatedArtifactIds.length ? "invalidated" as const : retainedHistoricalArtifactIds.length ? "retained-history" as const : "none" as const; const base = { schemaVersion: "craft-revocation-propagation.v1" as const, sourceId: input.sourceId, eventId: input.eventId, sourceFingerprint: input.sourceFingerprint, status: "propagated" as const, derivativeDisposition, invalidatedArtifactIds, retainedHistoricalArtifactIds, artifacts, reason: input.reason, evidenceRefs: [...input.evidenceRefs], sourceRefs: [...input.sourceRefs] }; return { ...base, fingerprint: hash(base) }; }
