import crypto from "node:crypto";
export type CraftLifecycle = "candidate" | "approved" | "probation" | "validated" | "rejected" | "retired";
export type CraftUsagePermission = "review-only" | "isolated-experiment" | "author-visible-no-auto-adopt" | "default-retrieval" | "none";
export interface CraftLifecyclePattern { schemaVersion: "craft-lifecycle.v1"; patternId: string; projectSlug: string; lifecycle: CraftLifecycle; usagePermission: CraftUsagePermission; sourceRefs: string[]; history: Array<{ from: CraftLifecycle; to: CraftLifecycle; actor: string; reason: string; experimentId: string | null; at: string }>; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function usagePermission(lifecycle: CraftLifecycle): CraftUsagePermission { return lifecycle === "candidate" ? "review-only" : lifecycle === "approved" ? "isolated-experiment" : lifecycle === "probation" ? "author-visible-no-auto-adopt" : lifecycle === "validated" ? "default-retrieval" : "none"; }
function assertIntegrity(pattern: CraftLifecyclePattern): void { const { fingerprint: _fingerprint, ...base } = pattern; if (pattern.schemaVersion !== "craft-lifecycle.v1" || !pattern.patternId.trim() || !pattern.projectSlug.trim() || !pattern.sourceRefs.length || pattern.sourceRefs.some((ref) => !ref.trim()) || pattern.usagePermission !== usagePermission(pattern.lifecycle) || !/^[a-f0-9]{64}$/i.test(pattern.fingerprint) || hash(base) !== pattern.fingerprint) throw new Error("CRAFT_LIFECYCLE_INTEGRITY_FAILED"); }
export function createCraftPattern(input: { patternId: string; projectSlug: string; lifecycle: CraftLifecycle; sourceRefs: readonly string[] }): CraftLifecyclePattern { if (input.lifecycle !== "candidate") throw new Error("CRAFT_LIFECYCLE_INITIAL_INVALID"); if (!input.patternId.trim() || !input.projectSlug.trim()) throw new Error("CRAFT_LIFECYCLE_FIELDS_REQUIRED"); if (!input.sourceRefs.length || input.sourceRefs.some((ref) => !ref.trim())) throw new Error("CRAFT_LIFECYCLE_SOURCE_REQUIRED"); const base = { schemaVersion: "craft-lifecycle.v1" as const, patternId: input.patternId, projectSlug: input.projectSlug, lifecycle: input.lifecycle, usagePermission: usagePermission(input.lifecycle), sourceRefs: [...input.sourceRefs], history: [] }; return { ...base, fingerprint: hash(base) }; }
export function transitionCraftPatternLifecycle(pattern: CraftLifecyclePattern, input: { target: CraftLifecycle; actor: string; reason: string; experimentId: string | null }): CraftLifecyclePattern { assertIntegrity(pattern); if (!input.actor.trim() || !input.reason.trim()) throw new Error("CRAFT_LIFECYCLE_AUTH_REQUIRED"); const transitions: Record<CraftLifecycle, CraftLifecycle[]> = { candidate: ["approved", "rejected", "retired"], approved: ["probation", "rejected", "retired"], probation: ["validated", "rejected", "retired"], validated: ["rejected", "retired"], rejected: ["retired"], retired: [] }; if (!transitions[pattern.lifecycle].includes(input.target)) throw new Error("CRAFT_LIFECYCLE_TRANSITION_INVALID"); if (input.target === "probation" && !input.experimentId) throw new Error("CRAFT_EXPERIMENT_REQUIRED"); if (input.target === "validated" && !input.experimentId) throw new Error("CRAFT_VALIDATION_EXPERIMENT_REQUIRED"); const { fingerprint: _fingerprint, ...patternBase } = pattern; const history = [...pattern.history, { from: pattern.lifecycle, to: input.target, actor: input.actor, reason: input.reason, experimentId: input.experimentId, at: new Date().toISOString() }]; const base = { ...patternBase, lifecycle: input.target, usagePermission: usagePermission(input.target), history }; return { ...base, fingerprint: hash(base) }; }
