import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { resolveInside } from "./pathSafety.js";

export type DecisionConsumer = "story-contract" | "outline" | "prose" | "obligation" | "revision" | "completion-audit";
export interface DecisionConsumptionReceipt { schemaVersion: "decision-consumption-receipt.v1"; receiptId: string; projectSlug: string; decisionId: string; decisionVersion: number; consumer: DecisionConsumer; consumerRef: string; sourceFingerprint: string; consumedAt: string; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
const receiptPath = (root: string, receiptId: string) => resolveInside(root, path.join("sessions", "decision-consumption", `${receiptId}.json`));
export function assertDecisionConsumptionIntegrity(receipt: DecisionConsumptionReceipt, expectedId?: string): DecisionConsumptionReceipt { const { fingerprint, ...base } = receipt; const valid = receipt?.schemaVersion === "decision-consumption-receipt.v1" && (!expectedId || receipt.receiptId === expectedId) && [receipt.receiptId, receipt.projectSlug, receipt.decisionId, receipt.consumerRef, receipt.sourceFingerprint, receipt.consumedAt].every((value) => typeof value === "string" && value.trim()) && Number.isInteger(receipt.decisionVersion) && receipt.decisionVersion >= 1 && ["story-contract", "outline", "prose", "obligation", "revision", "completion-audit"].includes(receipt.consumer) && !Number.isNaN(Date.parse(receipt.consumedAt)) && /^[a-f0-9]{64}$/i.test(fingerprint) && hash(base) === fingerprint; if (!valid) throw new Error("DECISION_CONSUMPTION_INTEGRITY_FAILED"); return receipt; }
async function readJson(root: string, receiptId: string): Promise<DecisionConsumptionReceipt | null> { try { const value = JSON.parse(await fs.readFile(receiptPath(root, receiptId), "utf8")) as DecisionConsumptionReceipt; return assertDecisionConsumptionIntegrity(value, receiptId); } catch (error) { if (error instanceof Error && "code" in error && (error as { code?: string }).code === "ENOENT") return null; throw error; } }
async function writeJson(root: string, receipt: DecisionConsumptionReceipt): Promise<void> { const target = receiptPath(root, receipt.receiptId); await fs.mkdir(path.dirname(target), { recursive: true }); const temporary = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(temporary, `${JSON.stringify(receipt, null, 2)}\n`, "utf8"); await fs.rename(temporary, target); }
export function createDecisionConsumptionReceipt(input: { receiptId: string; projectSlug: string; decisionId: string; decisionVersion: number; consumer: DecisionConsumer; consumerRef: string; sourceFingerprint: string }): DecisionConsumptionReceipt { if (!input.receiptId.trim() || !input.projectSlug.trim() || !input.decisionId.trim() || !Number.isInteger(input.decisionVersion) || input.decisionVersion < 1 || !["story-contract", "outline", "prose", "obligation", "revision", "completion-audit"].includes(input.consumer) || !input.consumerRef.trim() || !input.sourceFingerprint.trim()) throw new Error("DECISION_CONSUMPTION_FIELDS_INVALID"); const base = { schemaVersion: "decision-consumption-receipt.v1" as const, ...input, consumedAt: new Date().toISOString() }; return { ...base, fingerprint: hash(base) }; }
export async function persistDecisionConsumptionReceipt(root: string, receipt: DecisionConsumptionReceipt): Promise<{ created: boolean; receipt: DecisionConsumptionReceipt }> { assertDecisionConsumptionIntegrity(receipt); const existing = await readJson(root, receipt.receiptId); if (existing) { if (existing.fingerprint === receipt.fingerprint) return { created: false, receipt: existing }; throw new Error("DECISION_CONSUMPTION_IMMUTABLE"); } await writeJson(root, receipt); return { created: true, receipt }; }
export async function readDecisionConsumptionReceipt(root: string, receiptId: string): Promise<DecisionConsumptionReceipt | null> { return readJson(root, receiptId); }
