import crypto from "node:crypto";

export interface ProjectCapabilityManifest { schemaVersion: "project-capability-manifest.v1"; projectId: string; projectSchemaVersion: string; enabledSlices: string[]; readable: string[]; writable: string[]; migrationStatus: "pending" | "verified" | "failed"; rollbackWindow: string; missingDependencies: string[]; fingerprint: string; }
export interface CapabilityDependencyProof { schemaVersion: "capability-dependency-proof.v1"; projectSlug?: string; sliceId: string; requiredKernels: Array<{ id: string; version: string; verifiedBy: string[] }>; writeAuthority: string; unmet: string[]; status: "satisfied" | "blocked"; fingerprint: string; }
export interface RequirementEvidenceLink { schemaVersion: "requirement-evidence-link.v1"; projectSlug?: string; requirementId: string; sliceId: string; contractRefs: string[]; tests: string[]; fixtures: string[]; metrics: string[]; releaseEvidence: string[]; status: "specified" | "implemented" | "verified" | "released"; fingerprint: string; }
export interface WriteAuthorityCheck { schemaVersion: "write-authority-check.v1"; semantic: string; authorities: string[]; status: "valid"; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
export function createProjectCapabilityManifest(input: (Omit<ProjectCapabilityManifest, "schemaVersion" | "fingerprint" | "projectSchemaVersion"> & { projectSchemaVersion?: string; schemaVersion?: string })): ProjectCapabilityManifest { const projectSchemaVersion = input.projectSchemaVersion ?? input.schemaVersion ?? ""; if (!input.projectId.trim() || !projectSchemaVersion.trim() || !input.enabledSlices.length || !input.migrationStatus || !input.rollbackWindow.trim()) throw new Error("CAPABILITY_MANIFEST_FIELDS_REQUIRED"); if (input.migrationStatus !== "verified" && input.writable.length) throw new Error("CAPABILITY_WRITE_REQUIRES_VERIFIED_MIGRATION"); const base = { schemaVersion: "project-capability-manifest.v1" as const, projectId: input.projectId, projectSchemaVersion, enabledSlices: [...input.enabledSlices], readable: [...input.readable], writable: [...input.writable], migrationStatus: input.migrationStatus, rollbackWindow: input.rollbackWindow, missingDependencies: [...input.missingDependencies] }; return { ...base, fingerprint: hash(base) }; }
export function createCapabilityDependencyProof(input: Omit<CapabilityDependencyProof, "schemaVersion" | "status" | "fingerprint">): CapabilityDependencyProof { if (!input.sliceId.trim() || !input.requiredKernels.length || !input.writeAuthority.trim()) throw new Error("DEPENDENCY_PROOF_FIELDS_REQUIRED"); const status = input.unmet.length ? "blocked" as const : "satisfied" as const; const base = { schemaVersion: "capability-dependency-proof.v1" as const, ...(input.projectSlug ? { projectSlug: input.projectSlug.trim() } : {}), sliceId: input.sliceId, requiredKernels: input.requiredKernels.map((kernel) => ({ ...kernel, verifiedBy: [...kernel.verifiedBy] })), writeAuthority: input.writeAuthority, unmet: [...input.unmet], status }; return { ...base, fingerprint: hash(base) }; }
export function createRequirementEvidenceLink(input: Omit<RequirementEvidenceLink, "schemaVersion" | "fingerprint">): RequirementEvidenceLink { if (!input.requirementId.trim() || !input.sliceId.trim() || !input.contractRefs.length || !input.tests.length) throw new Error("REQUIREMENT_EVIDENCE_FIELDS_REQUIRED"); if ((input.status === "verified" || input.status === "released") && (!input.fixtures.length || !input.metrics.length || !input.releaseEvidence.length)) throw new Error("REQUIREMENT_EVIDENCE_RELEASE_EVIDENCE_REQUIRED"); const base = { schemaVersion: "requirement-evidence-link.v1" as const, ...input, ...(input.projectSlug ? { projectSlug: input.projectSlug.trim() } : {}), contractRefs: [...input.contractRefs], tests: [...input.tests], fixtures: [...input.fixtures], metrics: [...input.metrics], releaseEvidence: [...input.releaseEvidence] }; return { ...base, fingerprint: hash(base) }; }
export function enforceSingleWriteAuthority(input: { semantic: string; authorities: readonly string[] }): WriteAuthorityCheck { if (!input.semantic.trim()) throw new Error("WRITE_SEMANTIC_REQUIRED"); if (input.authorities.length !== 1) throw new Error("MULTIPLE_WRITE_AUTHORITIES"); const base = { schemaVersion: "write-authority-check.v1" as const, semantic: input.semantic, authorities: [...input.authorities], status: "valid" as const }; return { ...base, fingerprint: hash(base) }; }
