import crypto from "node:crypto";

export interface BackupPolicy { schemaVersion: "backup-policy.v1"; policyId: string; rpoMinutes: number; rtoMinutes: number; retention: string[]; faultDomain: "same-workspace" | "offsite"; encryption: string; excluded: string[]; fingerprint: string; }
export interface BackupVerification { schemaVersion: "backup-verification.v1"; backupId: string; status: "verified" | "failed"; manifestHash: string; observedManifestHash: string; objectsReadable: boolean; parentChainValid: boolean; decryptionAllowed: boolean; schemaCompatible: boolean; crossReferencesValid: boolean; isolatedRestorePassed: boolean; workersStarted: false; externalMessagesSent: false; fingerprint: string; }
export interface RestorePlan { schemaVersion: "restore-plan.v1"; planId: string; backupId: string; mode: string; expectedLossWindow: string; conflicts: string[]; externalGaps: string[]; fenceWorkers: string[]; rollbackPoint: string; workerAction: "pause"; fingerprint: string; }
export interface RecoverySettlement { schemaVersion: "recovery-settlement.v1"; planId: string; status: "settled" | "blocked"; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
export function createBackupPolicy(input: Omit<BackupPolicy, "schemaVersion" | "fingerprint">): BackupPolicy { if (!input.policyId.trim() || input.rpoMinutes <= 0 || input.rtoMinutes <= 0 || !input.retention.length || !input.encryption.trim()) throw new Error("BACKUP_POLICY_FIELDS_REQUIRED"); const base = { schemaVersion: "backup-policy.v1" as const, ...input, retention: [...input.retention], excluded: [...input.excluded] }; return { ...base, fingerprint: hash(base) }; }
export function createBackupVerification(input: Omit<BackupVerification, "schemaVersion" | "status" | "fingerprint">): BackupVerification { const status = input.manifestHash === input.observedManifestHash && input.objectsReadable && input.parentChainValid && input.decryptionAllowed && input.schemaCompatible && input.crossReferencesValid && input.isolatedRestorePassed && !input.workersStarted && !input.externalMessagesSent ? "verified" as const : "failed" as const; const base = { schemaVersion: "backup-verification.v1" as const, ...input, workersStarted: false as const, externalMessagesSent: false as const, status }; return { ...base, fingerprint: hash(base) }; }
export function createRestorePlan(input: Omit<RestorePlan, "schemaVersion" | "workerAction" | "fingerprint">): RestorePlan { if (!input.planId.trim() || !input.backupId.trim() || !input.mode.trim() || !input.rollbackPoint.trim()) throw new Error("RESTORE_PLAN_FIELDS_REQUIRED"); const base = { schemaVersion: "restore-plan.v1" as const, ...input, conflicts: [...input.conflicts], externalGaps: [...input.externalGaps], fenceWorkers: [...input.fenceWorkers], workerAction: "pause" as const }; return { ...base, fingerprint: hash(base) }; }
export function settleRecovery(input: Omit<RecoverySettlement, "schemaVersion" | "status" | "fingerprint"> & { projectTreeValid: boolean; databaseValid: boolean; lineageValid: boolean; permissionsValid: boolean; projectionsFresh: boolean; obligationProofsValid: boolean; authorSampleChecked: boolean }): RecoverySettlement { const status = input.projectTreeValid && input.databaseValid && input.lineageValid && input.permissionsValid && input.projectionsFresh && input.obligationProofsValid && input.authorSampleChecked ? "settled" as const : "blocked" as const; const base = { schemaVersion: "recovery-settlement.v1" as const, planId: input.planId, status }; return { ...base, fingerprint: hash(base) }; }
