import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { resolveInside } from "./pathSafety.js";

export type EmergenceType = "character-motivation" | "conflict" | "relationship-turn" | "reveal-payoff" | "ending-possibility";
export type ChangeLevel = "L0" | "L1" | "L2";
export interface EmergenceCandidate { schemaVersion: "emergence-candidate.v1"; candidateId: string; projectSlug: string; chapterId: string; emergenceType: EmergenceType; observation: string; competingInterpretations: string[]; impactReport: { changeLevel: ChangeLevel; affectedNodeIds: string[]; protectedNodeIds: string[]; blockers: string[]; impactFingerprint: string | null; rollbackPoint: string | null }; status: "candidate" | "adopted" | "rejected"; canonWritten: false; sourceRefs: string[]; regressionFingerprint: string | null; structureValidationFingerprint: string | null; rollbackPoint: string | null; createdAt: string; updatedAt: string; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function candidatePath(root: string, id: string) { return resolveInside(root, `sessions/emergence-candidates/${id}.json`); }
async function read<T>(file: string): Promise<T | null> { try { return JSON.parse(await fs.readFile(file, "utf8")) as T; } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return null; throw e; } }
async function write(file: string, value: unknown) { await fs.mkdir(path.dirname(file), { recursive: true }); const tmp = `${file}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await fs.rename(tmp, file); }
export function assertEmergenceCandidateIntegrity(candidate: EmergenceCandidate, expectedId?: string): EmergenceCandidate {
  const { fingerprint, ...base } = candidate;
  const report = candidate.impactReport;
  const reportValid = Boolean(report && ["L0", "L1", "L2"].includes(report.changeLevel) && [report.affectedNodeIds, report.protectedNodeIds, report.blockers].every((values) => Array.isArray(values) && values.every((value) => typeof value === "string" && value.trim())) && (report.impactFingerprint === null || (typeof report.impactFingerprint === "string" && report.impactFingerprint.trim())) && (report.rollbackPoint === null || (typeof report.rollbackPoint === "string" && report.rollbackPoint.trim())));
  const valid = candidate?.schemaVersion === "emergence-candidate.v1" && (!expectedId || candidate.candidateId === expectedId) && [candidate.candidateId, candidate.projectSlug, candidate.chapterId, candidate.observation, candidate.createdAt, candidate.updatedAt].every((value) => typeof value === "string" && value.trim()) && ["character-motivation", "conflict", "relationship-turn", "reveal-payoff", "ending-possibility"].includes(candidate.emergenceType) && Array.isArray(candidate.competingInterpretations) && candidate.competingInterpretations.length >= 2 && candidate.competingInterpretations.every((value) => typeof value === "string" && value.trim()) && reportValid && ["candidate", "adopted", "rejected"].includes(candidate.status);
  const semantics = candidate?.canonWritten === false && Array.isArray(candidate.sourceRefs) && candidate.sourceRefs.length > 0 && candidate.sourceRefs.every((value) => typeof value === "string" && value.trim()) && (candidate.regressionFingerprint === null || (typeof candidate.regressionFingerprint === "string" && candidate.regressionFingerprint.trim())) && (candidate.structureValidationFingerprint === null || (typeof candidate.structureValidationFingerprint === "string" && candidate.structureValidationFingerprint.trim())) && (candidate.rollbackPoint === null || (typeof candidate.rollbackPoint === "string" && candidate.rollbackPoint.trim())) && !Number.isNaN(Date.parse(candidate.createdAt)) && !Number.isNaN(Date.parse(candidate.updatedAt)) && /^[a-f0-9]{64}$/i.test(candidate.fingerprint) && hash(base) === candidate.fingerprint;
  if (!valid || !semantics) throw new Error("EMERGENCE_CANDIDATE_INTEGRITY_FAILED");
  return candidate;
}
export async function readEmergenceCandidate(root: string, candidateId: string) { const candidate = await read<EmergenceCandidate>(candidatePath(root, candidateId)); return candidate ? assertEmergenceCandidateIntegrity(candidate, candidateId) : null; }
export async function createEmergenceCandidate(input: { root: string; projectSlug: string; chapterId: string; observation: string; emergenceType: EmergenceType; level: ChangeLevel; competingInterpretations: readonly string[]; affectedNodeIds: readonly string[]; protectedNodeIds?: readonly string[]; impactFingerprint?: string; rollbackPoint?: string; impactBlockers?: readonly string[]; sourceRefs: readonly string[] }): Promise<EmergenceCandidate> { if (!input.observation.trim() || !input.projectSlug.trim() || !input.chapterId.trim()) throw new Error("EMERGENCE_FIELDS_REQUIRED"); if (input.competingInterpretations.length < 2) throw new Error("EMERGENCE_COMPETING_INTERPRETATIONS_REQUIRED"); if (!input.sourceRefs.length) throw new Error("EMERGENCE_SOURCE_REQUIRED"); const identity = { projectSlug: input.projectSlug, chapterId: input.chapterId, observation: input.observation, emergenceType: input.emergenceType, level: input.level, competingInterpretations: [...input.competingInterpretations], affectedNodeIds: [...new Set(input.affectedNodeIds)].sort() }; const candidateId = `emergence-${hash(identity).slice(0, 20)}`; const existing = await readEmergenceCandidate(input.root, candidateId); if (existing) return existing; const protectedNodeIds = [...new Set(input.protectedNodeIds || [])].sort(); const blockers = [...new Set([...(input.impactBlockers || []), ...(protectedNodeIds.length ? ["PROTECTED_NODE_AFFECTED"] : []), ...(input.level === "L2" ? ["USER_CONFIRMATION_REQUIRED"] : [])])]; const base = { schemaVersion: "emergence-candidate.v1" as const, candidateId, projectSlug: input.projectSlug, chapterId: input.chapterId, emergenceType: input.emergenceType, observation: input.observation, competingInterpretations: [...input.competingInterpretations], impactReport: { changeLevel: input.level, affectedNodeIds: [...new Set(input.affectedNodeIds)].sort(), protectedNodeIds, blockers, impactFingerprint: input.impactFingerprint || null, rollbackPoint: input.rollbackPoint || null }, status: "candidate" as const, canonWritten: false as const, sourceRefs: [...input.sourceRefs], regressionFingerprint: null, structureValidationFingerprint: null, rollbackPoint: null, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; const result = { ...base, fingerprint: hash(base) }; await write(candidatePath(input.root, candidateId), result); return result; }
export async function adoptEmergenceCandidate(root: string, candidateId: string, input: { authorization: "author" | "none"; regressionFingerprint: string; structureValidationFingerprint?: string; rollbackPoint?: string }): Promise<EmergenceCandidate> { const candidate = await readEmergenceCandidate(root, candidateId); if (!candidate) throw new Error("EMERGENCE_CANDIDATE_NOT_FOUND"); if (candidate.impactReport.blockers.includes("PROTECTED_NODE_AFFECTED")) throw new Error("EMERGENCE_PROTECTED_IMPACT_BLOCKED"); if (candidate.impactReport.changeLevel === "L2" && input.authorization !== "author") throw new Error("EMERGENCE_CONFIRMATION_REQUIRED"); if (!input.regressionFingerprint.trim()) throw new Error("EMERGENCE_REGRESSION_REQUIRED"); if (candidate.impactReport.changeLevel !== "L0" && !input.structureValidationFingerprint?.trim()) throw new Error("EMERGENCE_STRUCTURE_VALIDATION_REQUIRED"); if (candidate.impactReport.changeLevel !== "L0" && !input.rollbackPoint?.trim()) throw new Error("EMERGENCE_ROLLBACK_REQUIRED"); const base = { ...candidate, status: "adopted" as const, regressionFingerprint: input.regressionFingerprint, structureValidationFingerprint: input.structureValidationFingerprint || null, rollbackPoint: input.rollbackPoint || null, updatedAt: new Date().toISOString() }; const result = { ...base, fingerprint: hash({ ...base, fingerprint: undefined }) }; await write(candidatePath(root, candidateId), result); return result; }
