import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { resolveInside } from "./pathSafety.js";

export type EmergenceType = "character-motivation" | "conflict" | "relationship-turn" | "reveal-payoff" | "ending-possibility";
export type ChangeLevel = "L0" | "L1" | "L2";
export interface EmergenceCandidate { schemaVersion: "emergence-candidate.v1"; candidateId: string; projectSlug: string; chapterId: string; emergenceType: EmergenceType; observation: string; competingInterpretations: string[]; impactReport: { changeLevel: ChangeLevel; affectedNodeIds: string[]; protectedNodeIds: string[]; blockers: string[] }; status: "candidate" | "adopted" | "rejected"; canonWritten: false; sourceRefs: string[]; regressionFingerprint: string | null; createdAt: string; updatedAt: string; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function candidatePath(root: string, id: string) { return resolveInside(root, `sessions/emergence-candidates/${id}.json`); }
async function read<T>(file: string): Promise<T | null> { try { return JSON.parse(await fs.readFile(file, "utf8")) as T; } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return null; throw e; } }
async function write(file: string, value: unknown) { await fs.mkdir(path.dirname(file), { recursive: true }); const tmp = `${file}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await fs.rename(tmp, file); }
export async function readEmergenceCandidate(root: string, candidateId: string) { return read<EmergenceCandidate>(candidatePath(root, candidateId)); }
export async function createEmergenceCandidate(input: { root: string; projectSlug: string; chapterId: string; observation: string; emergenceType: EmergenceType; level: ChangeLevel; competingInterpretations: readonly string[]; affectedNodeIds: readonly string[]; protectedNodeIds?: readonly string[]; sourceRefs: readonly string[] }): Promise<EmergenceCandidate> { if (!input.observation.trim() || !input.projectSlug.trim() || !input.chapterId.trim()) throw new Error("EMERGENCE_FIELDS_REQUIRED"); if (input.competingInterpretations.length < 2) throw new Error("EMERGENCE_COMPETING_INTERPRETATIONS_REQUIRED"); if (!input.sourceRefs.length) throw new Error("EMERGENCE_SOURCE_REQUIRED"); const identity = { projectSlug: input.projectSlug, chapterId: input.chapterId, observation: input.observation, emergenceType: input.emergenceType, level: input.level, competingInterpretations: [...input.competingInterpretations], affectedNodeIds: [...new Set(input.affectedNodeIds)].sort() }; const candidateId = `emergence-${hash(identity).slice(0, 20)}`; const existing = await readEmergenceCandidate(input.root, candidateId); if (existing) return existing; const base = { schemaVersion: "emergence-candidate.v1" as const, candidateId, projectSlug: input.projectSlug, chapterId: input.chapterId, emergenceType: input.emergenceType, observation: input.observation, competingInterpretations: [...input.competingInterpretations], impactReport: { changeLevel: input.level, affectedNodeIds: [...new Set(input.affectedNodeIds)].sort(), protectedNodeIds: [...new Set(input.protectedNodeIds || [])].sort(), blockers: input.level === "L2" ? ["USER_CONFIRMATION_REQUIRED"] : [] }, status: "candidate" as const, canonWritten: false as const, sourceRefs: [...input.sourceRefs], regressionFingerprint: null, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; const result = { ...base, fingerprint: hash(base) }; await write(candidatePath(input.root, candidateId), result); return result; }
export async function adoptEmergenceCandidate(root: string, candidateId: string, input: { authorization: "author" | "none"; regressionFingerprint: string }): Promise<EmergenceCandidate> { const candidate = await readEmergenceCandidate(root, candidateId); if (!candidate) throw new Error("EMERGENCE_CANDIDATE_NOT_FOUND"); if (candidate.impactReport.changeLevel === "L2" && input.authorization !== "author") throw new Error("EMERGENCE_CONFIRMATION_REQUIRED"); if (!input.regressionFingerprint.trim()) throw new Error("EMERGENCE_REGRESSION_REQUIRED"); const base = { ...candidate, status: "adopted" as const, regressionFingerprint: input.regressionFingerprint, updatedAt: new Date().toISOString() }; const result = { ...base, fingerprint: hash({ ...base, fingerprint: undefined }) }; await write(candidatePath(root, candidateId), result); return result; }
