import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { assertEvaluationSliceBudgetIntegrity, assertEvaluationSliceResultIntegrity, type EvaluationSliceBudget, type EvaluationSliceResult } from "./evaluationSliceBudget.js";
import { resolveInside } from "./pathSafety.js";
export interface PersistedEvaluationSliceBudget { schemaVersion: "persisted-evaluation-slice-budget.v1"; budgetId: string; projectSlug: string; budget: EvaluationSliceBudget; createdAt: string; fingerprint: string; }
export interface PersistedEvaluationSliceResult { schemaVersion: "persisted-evaluation-slice-result.v1"; resultId: string; projectSlug: string; budgetFingerprint: string; result: EvaluationSliceResult; createdAt: string; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
function file(root: string, kind: string, id: string): string { if (!/^[a-zA-Z0-9._-]+$/.test(id)) throw new Error("EVALUATION_SLICE_ID_INVALID"); return resolveInside(root, path.join("evaluations", "slice", kind, `${id}.json`)); }
function assertBudget(v: PersistedEvaluationSliceBudget, id: string): PersistedEvaluationSliceBudget { const { fingerprint: _fingerprint, ...base } = v; assertEvaluationSliceBudgetIntegrity(v.budget); if (v.schemaVersion !== "persisted-evaluation-slice-budget.v1" || v.budgetId !== id || !v.projectSlug.trim() || !v.createdAt.trim() || !/^[a-f0-9]{64}$/i.test(v.fingerprint) || hash(base) !== v.fingerprint) throw new Error("EVALUATION_SLICE_STORE_INTEGRITY_FAILED"); return v; }
function assertResult(v: PersistedEvaluationSliceResult, id: string): PersistedEvaluationSliceResult { const { fingerprint: _fingerprint, ...base } = v; assertEvaluationSliceResultIntegrity(v.result, v.budgetFingerprint); if (v.schemaVersion !== "persisted-evaluation-slice-result.v1" || v.resultId !== id || !v.projectSlug.trim() || !v.createdAt.trim() || !/^[a-f0-9]{64}$/i.test(v.fingerprint) || hash(base) !== v.fingerprint) throw new Error("EVALUATION_SLICE_STORE_INTEGRITY_FAILED"); return v; }
export async function readEvaluationSliceBudget(root: string, id: string): Promise<PersistedEvaluationSliceBudget | null> { try { return assertBudget(JSON.parse(await fs.readFile(file(root, "budgets", id), "utf8")) as PersistedEvaluationSliceBudget, id); } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return null; throw e; } }
export async function readEvaluationSliceResult(root: string, id: string): Promise<PersistedEvaluationSliceResult | null> { try { return assertResult(JSON.parse(await fs.readFile(file(root, "results", id), "utf8")) as PersistedEvaluationSliceResult, id); } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return null; throw e; } }
async function write(root: string, kind: string, id: string, value: unknown): Promise<void> { const target = file(root, kind, id); await fs.mkdir(path.dirname(target), { recursive: true }); const temporary = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(temporary, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await fs.rename(temporary, target); }
export async function persistEvaluationSliceBudget(root: string, input: { budgetId: string; projectSlug: string; budget: EvaluationSliceBudget }): Promise<{ created: boolean; record: PersistedEvaluationSliceBudget }> { assertEvaluationSliceBudgetIntegrity(input.budget); const existing = await readEvaluationSliceBudget(root, input.budgetId); if (existing) { if (existing.projectSlug === input.projectSlug && existing.budget.fingerprint === input.budget.fingerprint) return { created: false, record: existing }; throw new Error("EVALUATION_SLICE_BUDGET_IMMUTABLE"); } const base = { schemaVersion: "persisted-evaluation-slice-budget.v1" as const, budgetId: input.budgetId, projectSlug: input.projectSlug.trim(), budget: input.budget, createdAt: new Date().toISOString() }; const record = { ...base, fingerprint: hash(base) }; await write(root, "budgets", input.budgetId, record); return { created: true, record }; }
export async function persistEvaluationSliceResult(root: string, input: { resultId: string; projectSlug: string; budgetFingerprint: string; result: EvaluationSliceResult }): Promise<{ created: boolean; record: PersistedEvaluationSliceResult }> { assertEvaluationSliceResultIntegrity(input.result, input.budgetFingerprint); const existing = await readEvaluationSliceResult(root, input.resultId); if (existing) { if (existing.projectSlug === input.projectSlug && existing.budgetFingerprint === input.budgetFingerprint && existing.result.fingerprint === input.result.fingerprint) return { created: false, record: existing }; throw new Error("EVALUATION_SLICE_RESULT_IMMUTABLE"); } const base = { schemaVersion: "persisted-evaluation-slice-result.v1" as const, resultId: input.resultId, projectSlug: input.projectSlug.trim(), budgetFingerprint: input.budgetFingerprint, result: input.result, createdAt: new Date().toISOString() }; const record = { ...base, fingerprint: hash(base) }; await write(root, "results", input.resultId, record); return { created: true, record }; }
