import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { assertMultiScaleRegressionIntegrity, type MultiScaleRegressionResult } from "./evaluationSampling.js";
import { resolveInside } from "./pathSafety.js";

export interface PersistedEvaluationRegression { schemaVersion: "persisted-evaluation-regression.v1"; regressionId: string; projectSlug: string; result: MultiScaleRegressionResult; createdAt: string; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
function resultPath(root: string, id: string): string { if (!/^[a-zA-Z0-9._-]+$/.test(id)) throw new Error("EVALUATION_REGRESSION_ID_INVALID"); return resolveInside(root, path.join("evaluations", "regressions", `${id}.json`)); }
function assertRecord(value: PersistedEvaluationRegression, id: string): PersistedEvaluationRegression { const { fingerprint: _fingerprint, ...base } = value; assertMultiScaleRegressionIntegrity(value.result); if (value.schemaVersion !== "persisted-evaluation-regression.v1" || value.regressionId !== id || !value.projectSlug.trim() || !value.createdAt.trim() || !/^[a-f0-9]{64}$/i.test(value.fingerprint) || hash(base) !== value.fingerprint) throw new Error("EVALUATION_REGRESSION_STORE_INTEGRITY_FAILED"); return value; }
export async function readEvaluationRegression(root: string, id: string): Promise<PersistedEvaluationRegression | null> { try { return assertRecord(JSON.parse(await fs.readFile(resultPath(root, id), "utf8")) as PersistedEvaluationRegression, id); } catch (error) { if (error instanceof Error && "code" in error && (error as { code?: string }).code === "ENOENT") return null; throw error; } }
export async function persistEvaluationRegression(root: string, input: { regressionId: string; projectSlug: string; result: MultiScaleRegressionResult }): Promise<{ created: boolean; record: PersistedEvaluationRegression }> { assertMultiScaleRegressionIntegrity(input.result); if (!input.projectSlug.trim()) throw new Error("EVALUATION_REGRESSION_PROJECT_REQUIRED"); const existing = await readEvaluationRegression(root, input.regressionId); if (existing) { if (existing.projectSlug === input.projectSlug && existing.result.fingerprint === input.result.fingerprint) return { created: false, record: existing }; throw new Error("EVALUATION_REGRESSION_IMMUTABLE"); } const base = { schemaVersion: "persisted-evaluation-regression.v1" as const, regressionId: input.regressionId, projectSlug: input.projectSlug.trim(), result: input.result, createdAt: new Date().toISOString() }; const record = { ...base, fingerprint: hash(base) }; const target = resultPath(root, input.regressionId); await fs.mkdir(path.dirname(target), { recursive: true }); const temporary = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(temporary, `${JSON.stringify(record, null, 2)}\n`, "utf8"); await fs.rename(temporary, target); return { created: true, record }; }
