import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { assertEvaluationParetoIntegrity, type EvaluationParetoDecision } from "./evaluationPareto.js";
import { resolveInside } from "./pathSafety.js";
export interface PersistedEvaluationPareto { schemaVersion: "persisted-evaluation-pareto.v1"; decisionId: string; projectSlug: string; decision: EvaluationParetoDecision; createdAt: string; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
function decisionPath(root: string, id: string): string { if (!/^[a-zA-Z0-9._-]+$/.test(id)) throw new Error("EVALUATION_PARETO_ID_INVALID"); return resolveInside(root, path.join("evaluations", "pareto", `${id}.json`)); }
function assertRecord(value: PersistedEvaluationPareto, id: string): PersistedEvaluationPareto { const { fingerprint: _fingerprint, ...base } = value; assertEvaluationParetoIntegrity(value.decision); if (value.schemaVersion !== "persisted-evaluation-pareto.v1" || value.decisionId !== id || !value.projectSlug.trim() || !value.createdAt.trim() || !/^[a-f0-9]{64}$/i.test(value.fingerprint) || hash(base) !== value.fingerprint) throw new Error("EVALUATION_PARETO_STORE_INTEGRITY_FAILED"); return value; }
export async function readEvaluationPareto(root: string, id: string): Promise<PersistedEvaluationPareto | null> { try { return assertRecord(JSON.parse(await fs.readFile(decisionPath(root, id), "utf8")) as PersistedEvaluationPareto, id); } catch (error) { if (error instanceof Error && "code" in error && (error as { code?: string }).code === "ENOENT") return null; throw error; } }
export async function persistEvaluationPareto(root: string, input: { decisionId: string; projectSlug: string; decision: EvaluationParetoDecision }): Promise<{ created: boolean; record: PersistedEvaluationPareto }> { assertEvaluationParetoIntegrity(input.decision); if (!input.projectSlug.trim()) throw new Error("EVALUATION_PARETO_PROJECT_REQUIRED"); const existing = await readEvaluationPareto(root, input.decisionId); if (existing) { if (existing.projectSlug === input.projectSlug && existing.decision.fingerprint === input.decision.fingerprint) return { created: false, record: existing }; throw new Error("EVALUATION_PARETO_IMMUTABLE"); } const base = { schemaVersion: "persisted-evaluation-pareto.v1" as const, decisionId: input.decisionId, projectSlug: input.projectSlug.trim(), decision: input.decision, createdAt: new Date().toISOString() }; const record = { ...base, fingerprint: hash(base) }; const target = decisionPath(root, input.decisionId); await fs.mkdir(path.dirname(target), { recursive: true }); const temporary = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(temporary, `${JSON.stringify(record, null, 2)}\n`, "utf8"); await fs.rename(temporary, target); return { created: true, record }; }
