import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { resolveInside } from "./pathSafety.js";

export interface EvaluationSuite { schemaVersion: "evaluation-suite.v1"; suiteId: string; version: string; layers: string[]; domains: string[]; holdoutId: string; fingerprint: string; }
export interface FrozenEvaluationInput { schemaVersion: "frozen-evaluation-input.v1"; contractFingerprint: string; contextFingerprint: string; tools: string[]; outputBudget: number; sampling: { seed: number; temperature: number }; changedVariables: string[]; confounders: string[]; comparable: boolean; fingerprint: string; }
export interface BlindPair { schemaVersion: "blind-pair.v1"; comparisonId: string; target: string; blinded: true; presentedOrder: string[]; fingerprint: string; }
export interface EvaluatorCalibration { schemaVersion: "evaluator-calibration.v1"; evaluatorId: string; calibrationSamples: number; humanAgreement: number; detectsKnownFailures: string[]; status: "calibrated" | "experimental"; fingerprint: string; }
export interface ContaminationResult { schemaVersion: "evaluation-contamination.v1"; holdoutId: string; status: "valid" | "invalid"; evidence: string[]; fingerprint: string; }
export interface EvaluatorDrift { schemaVersion: "evaluator-drift.v1"; status: "stable" | "recalibrate"; agreementDelta: number; biasDelta: number; disagreementRateDelta?: number; previousVersion?: string; currentVersion?: string; scaleBreak: boolean; historyPreserved: boolean; recomputeRequired: boolean; fingerprint: string; }
export interface ReleaseDecision { schemaVersion: "release-decision.v1"; releaseId: string; status: "approved" | "blocked"; reasons: string[]; rollbackRef: string; qualityNonInferior?: boolean; costLatencyAccepted?: boolean; paretoEligible?: boolean; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
export function createEvaluationSuite(input: Omit<EvaluationSuite, "schemaVersion" | "fingerprint">): EvaluationSuite { if (!input.suiteId.trim() || !input.version.trim() || input.layers.length < 3 || !input.domains.length || !input.holdoutId.trim()) throw new Error("EVALUATION_SUITE_FIELDS_REQUIRED"); const base = { schemaVersion: "evaluation-suite.v1" as const, ...input, layers: [...input.layers], domains: [...input.domains] }; return { ...base, fingerprint: hash(base) }; }
export function freezeEvaluationInput(input: Omit<FrozenEvaluationInput, "schemaVersion" | "comparable" | "fingerprint">): FrozenEvaluationInput { const comparable = Boolean(input.contractFingerprint.trim() && input.contextFingerprint.trim() && input.tools.length && input.outputBudget > 0 && input.changedVariables.length > 0 && input.confounders.length === 0); const base = { schemaVersion: "frozen-evaluation-input.v1" as const, ...input, tools: [...input.tools], changedVariables: [...input.changedVariables], confounders: [...input.confounders], comparable }; return { ...base, fingerprint: hash(base) }; }
export function createBlindPair(input: { comparisonId: string; leftCandidate: string; rightCandidate: string; target: string; randomizationSeed: number }): BlindPair { if (!input.comparisonId.trim() || !input.leftCandidate.trim() || !input.rightCandidate.trim() || !input.target.trim()) throw new Error("BLIND_PAIR_FIELDS_REQUIRED"); const order = input.randomizationSeed % 2 === 0 ? [input.leftCandidate, input.rightCandidate] : [input.rightCandidate, input.leftCandidate]; const base = { schemaVersion: "blind-pair.v1" as const, comparisonId: input.comparisonId, target: input.target, blinded: true as const, presentedOrder: order }; return { ...base, fingerprint: hash(base) }; }
export function calibrateEvaluator(input: Omit<EvaluatorCalibration, "schemaVersion" | "status" | "fingerprint">): EvaluatorCalibration { const status = input.calibrationSamples >= 3 && input.humanAgreement >= 0.7 && input.detectsKnownFailures.length >= 3 ? "calibrated" as const : "experimental" as const; const base = { schemaVersion: "evaluator-calibration.v1" as const, ...input, detectsKnownFailures: [...input.detectsKnownFailures], status }; return { ...base, fingerprint: hash(base) }; }
export function detectEvaluationContamination(input: { holdoutId: string; visibleData: readonly string[]; output: string }): ContaminationResult { const evidence = input.visibleData.filter((item) => input.output.includes(item)); const base = { schemaVersion: "evaluation-contamination.v1" as const, holdoutId: input.holdoutId, status: evidence.length ? "invalid" as const : "valid" as const, evidence: [...evidence] }; return { ...base, fingerprint: hash(base) }; }
export function monitorEvaluatorDrift(input: { previousAgreement: number; currentAgreement: number; previousBias: number; currentBias: number; previousDisagreementRate?: number; currentDisagreementRate?: number; previousVersion?: string; currentVersion?: string; historicalScores?: Array<{ caseId: string; evaluatorVersion: string; score: number }>; recomputedScores?: Array<{ caseId: string; evaluatorVersion: string; score: number }> }): EvaluatorDrift { const agreementDelta = input.currentAgreement - input.previousAgreement; const biasDelta = input.currentBias - input.previousBias; const disagreementRateDelta = input.previousDisagreementRate === undefined || input.currentDisagreementRate === undefined ? undefined : input.currentDisagreementRate - input.previousDisagreementRate; const historyPreserved = Array.isArray(input.historicalScores) && input.historicalScores.length > 0; const paired = new Map((input.historicalScores ?? []).map((score) => [score.caseId, score.score])); const scoreDeltas = (input.recomputedScores ?? []).filter((score) => paired.has(score.caseId)).map((score) => Math.abs(score.score - paired.get(score.caseId)!)); const scaleBreak = scoreDeltas.some((delta) => delta > 0.2) || (disagreementRateDelta !== undefined && Math.abs(disagreementRateDelta) > 0.1); const versionChanged = Boolean(input.previousVersion && input.currentVersion && input.previousVersion !== input.currentVersion); const recomputeRequired = versionChanged || scaleBreak; const base = { schemaVersion: "evaluator-drift.v1" as const, status: agreementDelta < -0.1 || biasDelta > 0.1 || scaleBreak || recomputeRequired ? "recalibrate" as const : "stable" as const, agreementDelta, biasDelta, ...(disagreementRateDelta === undefined ? {} : { disagreementRateDelta }), ...(input.previousVersion ? { previousVersion: input.previousVersion } : {}), ...(input.currentVersion ? { currentVersion: input.currentVersion } : {}), scaleBreak, historyPreserved, recomputeRequired }; return { ...base, fingerprint: hash(base) }; }
export function createReleaseDecision(input: { releaseId: string; hardGatesPassed: boolean; keySliceRegressions: readonly string[]; blindPairWinRate: number; minimumWinRate: number; evidenceComplete: boolean; rollbackRef: string; shadowValidated: boolean; canaryValidated: boolean; qualityNonInferior?: boolean; actualCostCents?: number; maxCostCents?: number; actualLatencyMs?: number; maxLatencyMs?: number; criticalSlicesStable?: boolean; paretoEligible?: boolean }): ReleaseDecision {
  const reasons: string[] = [];
  if (!input.hardGatesPassed) reasons.push("hard-gate");
  if (input.keySliceRegressions.length) reasons.push("key-slice-regression");
  if (input.blindPairWinRate < input.minimumWinRate) reasons.push("blind-pair-threshold");
  if (!input.evidenceComplete) reasons.push("evidence-incomplete");
  if (!input.rollbackRef.trim()) reasons.push("rollback-missing");
  if (!input.shadowValidated || !input.canaryValidated) reasons.push("shadow-canary-missing");
  if (input.qualityNonInferior === undefined) reasons.push("quality-evidence-missing");
  const qualityNonInferior = input.qualityNonInferior ?? false;
  if (!qualityNonInferior) reasons.push("quality-not-non-inferior");
  if (input.criticalSlicesStable === undefined) reasons.push("critical-slice-evidence-missing");
  if (input.criticalSlicesStable === false) reasons.push("critical-slice-regression");
  const costEvidenceComplete = input.actualCostCents !== undefined && input.maxCostCents !== undefined;
  const latencyEvidenceComplete = input.actualLatencyMs !== undefined && input.maxLatencyMs !== undefined;
  if (!costEvidenceComplete) reasons.push("cost-envelope-missing");
  if (!latencyEvidenceComplete) reasons.push("latency-envelope-missing");
  const costLatencyAccepted = (!costEvidenceComplete || input.actualCostCents! <= input.maxCostCents!) && (!latencyEvidenceComplete || input.actualLatencyMs! <= input.maxLatencyMs!);
  if (costEvidenceComplete && input.actualCostCents! > input.maxCostCents!) reasons.push("cost-envelope");
  if (latencyEvidenceComplete && input.actualLatencyMs! > input.maxLatencyMs!) reasons.push("latency-envelope");
  if (input.paretoEligible === undefined) reasons.push("pareto-evidence-missing");
  const paretoEligible = input.paretoEligible ?? false;
  if (!paretoEligible) reasons.push("pareto-ineligible");
  const base = { schemaVersion: "release-decision.v1" as const, releaseId: input.releaseId, status: reasons.length ? "blocked" as const : "approved" as const, reasons, rollbackRef: input.rollbackRef, qualityNonInferior, costLatencyAccepted, paretoEligible };
  return { ...base, fingerprint: hash(base) };
}

export function assertReleaseDecisionIntegrity(decision: ReleaseDecision): void { const { fingerprint: _fingerprint, ...base } = decision; const optionalBooleans = [decision.qualityNonInferior, decision.costLatencyAccepted, decision.paretoEligible].every((value) => value === undefined || typeof value === "boolean"); const shapeValid = decision.schemaVersion === "release-decision.v1" && Boolean(decision.releaseId?.trim()) && (decision.status === "approved" || decision.status === "blocked") && Array.isArray(decision.reasons) && decision.reasons.every((reason) => typeof reason === "string") && optionalBooleans && (decision.status !== "approved" || decision.reasons.length === 0); if (!shapeValid || !/^[a-f0-9]{64}$/i.test(decision.fingerprint) || hash(base) !== decision.fingerprint) throw new Error("RELEASE_DECISION_INTEGRITY_FAILED"); }

function releaseDecisionPath(root: string, releaseId: string): string { if (!/^[a-zA-Z0-9._-]+$/.test(releaseId)) throw new Error("RELEASE_ID_INVALID"); return resolveInside(root, path.join("evaluations", "releases", `${releaseId}.json`)); }
export async function readReleaseDecision(root: string, releaseId: string): Promise<ReleaseDecision | null> { try { const decision = JSON.parse(await fs.readFile(releaseDecisionPath(root, releaseId), "utf8")) as ReleaseDecision; assertReleaseDecisionIntegrity(decision); return decision; } catch (error) { if (error instanceof Error && "code" in error && (error as { code?: string }).code === "ENOENT") return null; throw error; } }
export async function persistReleaseDecision(root: string, decision: ReleaseDecision): Promise<{ created: boolean; decision: ReleaseDecision }> { assertReleaseDecisionIntegrity(decision); const target = releaseDecisionPath(root, decision.releaseId); const existing = await readReleaseDecision(root, decision.releaseId); if (existing) { if (existing.fingerprint === decision.fingerprint) return { created: false, decision: existing }; throw new Error("RELEASE_DECISION_IMMUTABLE"); } await fs.mkdir(path.dirname(target), { recursive: true }); const temporary = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(temporary, `${JSON.stringify(decision, null, 2)}\n`, "utf8"); await fs.rename(temporary, target); return { created: true, decision }; }
