import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { assertEvaluationSamplingPlanIntegrity, assertEvaluationSamplingSummaryIntegrity, type EvaluationSamplingPlan, type EvaluationSamplingSummary } from "./evaluationSampling.js";
import { resolveInside } from "./pathSafety.js";

export interface PersistedEvaluationSamplingPlan { schemaVersion: "persisted-evaluation-sampling-plan.v1"; planId: string; projectSlug: string; plan: EvaluationSamplingPlan; createdAt: string; fingerprint: string; }
export interface PersistedEvaluationSamplingSummary { schemaVersion: "persisted-evaluation-sampling-summary.v1"; summaryId: string; projectSlug: string; planFingerprint: string; summary: EvaluationSamplingSummary; createdAt: string; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
function recordPath(root: string, kind: "plans" | "summaries", id: string): string { if (!/^[a-zA-Z0-9._-]+$/.test(id)) throw new Error("EVALUATION_SAMPLING_ID_INVALID"); return resolveInside(root, path.join("evaluations", "sampling", kind, `${id}.json`)); }
function assertPlanRecord(value: PersistedEvaluationSamplingPlan, id: string): PersistedEvaluationSamplingPlan { const { fingerprint: _fingerprint, ...base } = value; assertEvaluationSamplingPlanIntegrity(value.plan); if (value.schemaVersion !== "persisted-evaluation-sampling-plan.v1" || value.planId !== id || !value.projectSlug.trim() || !value.createdAt.trim() || !/^[a-f0-9]{64}$/i.test(value.fingerprint) || hash(base) !== value.fingerprint) throw new Error("EVALUATION_SAMPLING_STORE_INTEGRITY_FAILED"); return value; }
function assertSummaryRecord(value: PersistedEvaluationSamplingSummary, id: string): PersistedEvaluationSamplingSummary { const { fingerprint: _fingerprint, ...base } = value; assertEvaluationSamplingSummaryIntegrity(value.summary, value.planFingerprint); if (value.schemaVersion !== "persisted-evaluation-sampling-summary.v1" || value.summaryId !== id || !value.projectSlug.trim() || !value.planFingerprint.trim() || !value.createdAt.trim() || !/^[a-f0-9]{64}$/i.test(value.fingerprint) || hash(base) !== value.fingerprint) throw new Error("EVALUATION_SAMPLING_STORE_INTEGRITY_FAILED"); return value; }
export async function readEvaluationSamplingPlan(root: string, planId: string): Promise<PersistedEvaluationSamplingPlan | null> { try { return assertPlanRecord(JSON.parse(await fs.readFile(recordPath(root, "plans", planId), "utf8")) as PersistedEvaluationSamplingPlan, planId); } catch (error) { if (error instanceof Error && "code" in error && (error as { code?: string }).code === "ENOENT") return null; throw error; } }
export async function readEvaluationSamplingSummary(root: string, summaryId: string): Promise<PersistedEvaluationSamplingSummary | null> { try { return assertSummaryRecord(JSON.parse(await fs.readFile(recordPath(root, "summaries", summaryId), "utf8")) as PersistedEvaluationSamplingSummary, summaryId); } catch (error) { if (error instanceof Error && "code" in error && (error as { code?: string }).code === "ENOENT") return null; throw error; } }
async function persist<T extends PersistedEvaluationSamplingPlan | PersistedEvaluationSamplingSummary>(root: string, kind: "plans" | "summaries", id: string, value: T): Promise<void> { const target = recordPath(root, kind, id); await fs.mkdir(path.dirname(target), { recursive: true }); const temporary = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(temporary, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await fs.rename(temporary, target); }
export async function persistEvaluationSamplingPlan(root: string, input: { planId: string; projectSlug: string; plan: EvaluationSamplingPlan }): Promise<{ created: boolean; record: PersistedEvaluationSamplingPlan }> { assertEvaluationSamplingPlanIntegrity(input.plan); if (!input.projectSlug.trim()) throw new Error("EVALUATION_SAMPLING_PROJECT_REQUIRED"); const existing = await readEvaluationSamplingPlan(root, input.planId); if (existing) { if (existing.projectSlug === input.projectSlug && existing.plan.fingerprint === input.plan.fingerprint) return { created: false, record: existing }; throw new Error("EVALUATION_SAMPLING_IMMUTABLE"); } const base = { schemaVersion: "persisted-evaluation-sampling-plan.v1" as const, planId: input.planId, projectSlug: input.projectSlug.trim(), plan: input.plan, createdAt: new Date().toISOString() }; const record = { ...base, fingerprint: hash(base) }; await persist(root, "plans", input.planId, record); return { created: true, record }; }
export async function persistEvaluationSamplingSummary(root: string, input: { summaryId: string; projectSlug: string; planFingerprint: string; summary: EvaluationSamplingSummary }): Promise<{ created: boolean; record: PersistedEvaluationSamplingSummary }> { assertEvaluationSamplingSummaryIntegrity(input.summary, input.planFingerprint); if (!input.projectSlug.trim()) throw new Error("EVALUATION_SAMPLING_PROJECT_REQUIRED"); const existing = await readEvaluationSamplingSummary(root, input.summaryId); if (existing) { if (existing.projectSlug === input.projectSlug && existing.summary.fingerprint === input.summary.fingerprint && existing.planFingerprint === input.planFingerprint) return { created: false, record: existing }; throw new Error("EVALUATION_SAMPLING_IMMUTABLE"); } const base = { schemaVersion: "persisted-evaluation-sampling-summary.v1" as const, summaryId: input.summaryId, projectSlug: input.projectSlug.trim(), planFingerprint: input.planFingerprint, summary: input.summary, createdAt: new Date().toISOString() }; const record = { ...base, fingerprint: hash(base) }; await persist(root, "summaries", input.summaryId, record); return { created: true, record }; }
