import crypto from "node:crypto";

export interface EvaluationSuite { schemaVersion: "evaluation-suite.v1"; suiteId: string; version: string; layers: string[]; domains: string[]; holdoutId: string; fingerprint: string; }
export interface FrozenEvaluationInput { schemaVersion: "frozen-evaluation-input.v1"; contractFingerprint: string; contextFingerprint: string; tools: string[]; outputBudget: number; sampling: { seed: number; temperature: number }; changedVariables: string[]; confounders: string[]; comparable: boolean; fingerprint: string; }
export interface BlindPair { schemaVersion: "blind-pair.v1"; comparisonId: string; target: string; blinded: true; presentedOrder: string[]; fingerprint: string; }
export interface EvaluatorCalibration { schemaVersion: "evaluator-calibration.v1"; evaluatorId: string; calibrationSamples: number; humanAgreement: number; detectsKnownFailures: string[]; status: "calibrated" | "experimental"; fingerprint: string; }
export interface ContaminationResult { schemaVersion: "evaluation-contamination.v1"; holdoutId: string; status: "valid" | "invalid"; evidence: string[]; fingerprint: string; }
export interface EvaluatorDrift { schemaVersion: "evaluator-drift.v1"; status: "stable" | "recalibrate"; agreementDelta: number; biasDelta: number; fingerprint: string; }
export interface ReleaseDecision { schemaVersion: "release-decision.v1"; releaseId: string; status: "approved" | "blocked"; reasons: string[]; rollbackRef: string; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
export function createEvaluationSuite(input: Omit<EvaluationSuite, "schemaVersion" | "fingerprint">): EvaluationSuite { if (!input.suiteId.trim() || !input.version.trim() || input.layers.length < 3 || !input.domains.length || !input.holdoutId.trim()) throw new Error("EVALUATION_SUITE_FIELDS_REQUIRED"); const base = { schemaVersion: "evaluation-suite.v1" as const, ...input, layers: [...input.layers], domains: [...input.domains] }; return { ...base, fingerprint: hash(base) }; }
export function freezeEvaluationInput(input: Omit<FrozenEvaluationInput, "schemaVersion" | "comparable" | "fingerprint">): FrozenEvaluationInput { const comparable = Boolean(input.contractFingerprint.trim() && input.contextFingerprint.trim() && input.tools.length && input.outputBudget > 0 && input.changedVariables.length > 0 && input.confounders.length === 0); const base = { schemaVersion: "frozen-evaluation-input.v1" as const, ...input, tools: [...input.tools], changedVariables: [...input.changedVariables], confounders: [...input.confounders], comparable }; return { ...base, fingerprint: hash(base) }; }
export function createBlindPair(input: { comparisonId: string; leftCandidate: string; rightCandidate: string; target: string; randomizationSeed: number }): BlindPair { if (!input.comparisonId.trim() || !input.leftCandidate.trim() || !input.rightCandidate.trim() || !input.target.trim()) throw new Error("BLIND_PAIR_FIELDS_REQUIRED"); const order = input.randomizationSeed % 2 === 0 ? [input.leftCandidate, input.rightCandidate] : [input.rightCandidate, input.leftCandidate]; const base = { schemaVersion: "blind-pair.v1" as const, comparisonId: input.comparisonId, target: input.target, blinded: true as const, presentedOrder: order }; return { ...base, fingerprint: hash(base) }; }
export function calibrateEvaluator(input: Omit<EvaluatorCalibration, "schemaVersion" | "status" | "fingerprint">): EvaluatorCalibration { const status = input.calibrationSamples >= 3 && input.humanAgreement >= 0.7 && input.detectsKnownFailures.length >= 3 ? "calibrated" as const : "experimental" as const; const base = { schemaVersion: "evaluator-calibration.v1" as const, ...input, detectsKnownFailures: [...input.detectsKnownFailures], status }; return { ...base, fingerprint: hash(base) }; }
export function detectEvaluationContamination(input: { holdoutId: string; visibleData: readonly string[]; output: string }): ContaminationResult { const evidence = input.visibleData.filter((item) => input.output.includes(item)); const base = { schemaVersion: "evaluation-contamination.v1" as const, holdoutId: input.holdoutId, status: evidence.length ? "invalid" as const : "valid" as const, evidence: [...evidence] }; return { ...base, fingerprint: hash(base) }; }
export function monitorEvaluatorDrift(input: { previousAgreement: number; currentAgreement: number; previousBias: number; currentBias: number }): EvaluatorDrift { const agreementDelta = input.currentAgreement - input.previousAgreement; const biasDelta = input.currentBias - input.previousBias; const base = { schemaVersion: "evaluator-drift.v1" as const, status: agreementDelta < -0.1 || biasDelta > 0.1 ? "recalibrate" as const : "stable" as const, agreementDelta, biasDelta }; return { ...base, fingerprint: hash(base) }; }
export function createReleaseDecision(input: { releaseId: string; hardGatesPassed: boolean; keySliceRegressions: readonly string[]; blindPairWinRate: number; minimumWinRate: number; evidenceComplete: boolean; rollbackRef: string; shadowValidated: boolean; canaryValidated: boolean }): ReleaseDecision { const reasons: string[] = []; if (!input.hardGatesPassed) reasons.push("hard-gate"); if (input.keySliceRegressions.length) reasons.push("key-slice-regression"); if (input.blindPairWinRate < input.minimumWinRate) reasons.push("blind-pair-threshold"); if (!input.evidenceComplete) reasons.push("evidence-incomplete"); if (!input.rollbackRef.trim()) reasons.push("rollback-missing"); if (!input.shadowValidated || !input.canaryValidated) reasons.push("shadow-canary-missing"); const base = { schemaVersion: "release-decision.v1" as const, releaseId: input.releaseId, status: reasons.length ? "blocked" as const : "approved" as const, reasons, rollbackRef: input.rollbackRef }; return { ...base, fingerprint: hash(base) }; }
