import { describe, expect, it } from "vitest";
import { evaluateExecutionReadyGate } from "./executionReadyGate.js";

const valid = { projectSlug: "demo", outlineVersionId: "v1", nearHorizon: [{ chapterId: "ch-1", hasFunction: true, hasStateChange: true, sourceRefs: ["source://ch-1"] }, { chapterId: "ch-2", hasFunction: true, hasStateChange: true, sourceRefs: ["source://ch-2"] }, { chapterId: "ch-3", hasFunction: true, hasStateChange: true, sourceRefs: ["source://ch-3"] }], arcObligationLinks: [{ arcId: "arc-main", obligationId: "obl-1", plannedNodeId: "ch-3" }], causalReachable: true, contextComplete: true, blockingConflictsResolved: true, sourceRefs: ["outline://v1"] };
describe("execution-ready gate", () => {
  it("passes only when all near-horizon evidence is present", () => { const report = evaluateExecutionReadyGate(valid); expect(report.status).toBe("ready"); expect(report.executionReady).toBe(true); expect(report.checks).toHaveLength(7); });
  it("blocks missing state/source, arc obligation links, context, or unresolved conflicts", () => { const report = evaluateExecutionReadyGate({ ...valid, nearHorizon: [{ ...valid.nearHorizon[0], hasStateChange: false, sourceRefs: [] }, ...valid.nearHorizon.slice(1)], arcObligationLinks: [], contextComplete: false, blockingConflictsResolved: false }); expect(report.status).toBe("blocked"); expect(report.executionReady).toBe(false); expect(report.checks.filter((check) => check.status === "failed").map((check) => check.checkId)).toEqual(expect.arrayContaining(["near-horizon-evidence", "arc-obligation-coverage", "context-complete", "blocking-conflicts"])); });
  it("requires a 3-5 chapter horizon and evidence sources", () => { expect(evaluateExecutionReadyGate({ ...valid, nearHorizon: valid.nearHorizon.slice(0, 2) }).status).toBe("blocked"); expect(evaluateExecutionReadyGate({ ...valid, sourceRefs: [] }).status).toBe("blocked"); });
});
