export function assessCounterfactualScene(input: { removedFunctions: readonly string[]; uniqueTexture: boolean; repeatedInformation: boolean }): { status: "necessary" | "compressible" | "redundant"; lostFunctions: string[] } { const status = input.removedFunctions.length ? "necessary" : input.uniqueTexture ? "compressible" : input.repeatedInformation ? "redundant" : "compressible"; return { status, lostFunctions: [...input.removedFunctions] }; }
export function classifySurprise(input: { priorEvidence: number; competingHypotheses: number; introducesNewRule: boolean }): "obvious" | "fair" | "ungrounded" { if (input.introducesNewRule) return "ungrounded"; if (!input.priorEvidence) return "ungrounded"; if (input.competingHypotheses < 2) return "obvious"; return "fair"; }
export function assessLongitudinalExperience(input: { chapterScore: number; resetGoals: number; unansweredCoreQuestions: number; locationConfusion: boolean }): { pass: boolean; debt: string[]; minimumWindow: string } { const debt = [input.resetGoals ? "goal-reset" : "", input.unansweredCoreQuestions ? "unanswered-questions" : "", input.locationConfusion ? "location-confusion" : ""].filter(Boolean); return { pass: input.chapterScore >= 0.8 && debt.length === 0, debt, minimumWindow: debt.length ? "smallest-repair-window" : "none" }; }
export function preserveReaderDivergence(input: { samples: readonly { audience: string; result: string; evidence: readonly string[] }[] }): { samples: Array<{ audience: string; result: string; evidence: string[] }>; average: null } { return { samples: input.samples.map((sample) => ({ audience: sample.audience, result: sample.result, evidence: [...sample.evidence] })), average: null }; }
export function gateReviewerCalibration(input: { humanSamples: number; blind: boolean; agreementRate: number }): { status: "calibrated" | "experimental"; hardGateEligible: boolean } { const status = input.humanSamples >= 3 && input.blind && input.agreementRate >= 0.7 ? "calibrated" : "experimental"; return { status, hardGateEligible: status === "calibrated" }; }
export function invalidateAfterRevision(input: { deletedEvidence: boolean; linkedItems: readonly string[] }): { stale: boolean; items: string[]; rerunColdRead: boolean } { return { stale: input.deletedEvidence, items: [...input.linkedItems], rerunColdRead: input.deletedEvidence }; }
export function preserveRepairAdvantages(input: { targetedFix: boolean; broadExplanation: boolean; originalStrengths: readonly string[] }): { accepted: boolean; preserved: string[] } { return { accepted: input.targetedFix && !input.broadExplanation, preserved: [...input.originalStrengths] }; }
export function revokeReaderFeedback(input: { feedbackId: string; authorized: boolean; withdrawn: boolean; derived: readonly string[] }): { status: "active" | "stale" | "deleted"; derived: string[] } { const status = input.withdrawn ? "deleted" : input.authorized ? "active" : "stale"; return { status, derived: [...input.derived] }; }
export function boundExperienceDossier(input: { reviewedRange: string; coldReadFailures: number; disagreements: number; unknowns: number }): { claim: string; fullBookHealthy: false; gaps: string[] } { const gaps = [input.coldReadFailures ? "cold-read-failure" : "", input.disagreements ? "disagreement" : "", input.unknowns ? "unknown" : ""].filter(Boolean); return { claim: `supported within ${input.reviewedRange}`, fullBookHealthy: false, gaps }; }
