export function evaluateExperienceContract(input: { targeted: readonly string[]; notTargeted: readonly string[]; observed: Record<string, boolean> }): { passed: boolean; missed: string[] } { const missed = input.targeted.filter((key) => !input.observed[key]); return { passed: missed.length === 0, missed }; }
export function classifyReaderHypothesis(input: { claim: string; evidenceRefs: readonly string[]; confidence: number }): { status: "hypothesis"; canon: false; calibrated: boolean } { return { status: "hypothesis", canon: false, calibrated: input.evidenceRefs.length > 0 && input.confidence >= 0.7 }; }
export function sealColdRead(input: { visibleProgress: number; maxProgress: number; leakedFuture: boolean }): { valid: boolean; invalidated: boolean } { const valid = input.visibleProgress <= input.maxProgress && !input.leakedFuture; return { valid, invalidated: !valid }; }
export function preserveCompetingReaderQuestions(input: { questions: readonly { id: string; support: readonly string[]; counter: readonly string[] }[] }): { questions: Array<{ id: string; support: string[]; counter: string[] }> } { return { questions: input.questions.map((q) => ({ id: q.id, support: [...q.support], counter: [...q.counter] })) }; }
export function classifyAmbiguity(input: { intentionallyHidden: boolean; positionClear: boolean; actionClear: boolean; chronologyClear: boolean }): { hidden: boolean; confused: boolean; targetedFix: boolean } { const confused = !input.positionClear || !input.actionClear || !input.chronologyClear; return { hidden: input.intentionallyHidden, confused, targetedFix: confused }; }
export function assessAttachmentEvidence(input: { visibleDesire: boolean; meaningfulChoice: boolean; cost: boolean; wins: number }): { supported: boolean; reason: string } { const supported = input.visibleDesire && input.meaningfulChoice && input.cost; return { supported, reason: supported ? "desire-choice-cost" : "wins-alone-insufficient" }; }
export function separateEmotionAndReaderImpact(input: { emotionDeclared: boolean; eventEvidence: boolean; relationalAccumulation: boolean; consequentialChoice: boolean }): { characterEmotion: boolean; readerImpact: boolean } { return { characterEmotion: input.emotionDeclared, readerImpact: input.eventEvidence && input.relationalAccumulation && input.consequentialChoice }; }
export function settleCuriosity(input: { openAnswers: number; answeredLocally: boolean; changesJudgment: boolean }): { debt: number; partialSettlement: boolean } { return { debt: Math.max(0, input.openAnswers - (input.answeredLocally ? 1 : 0)), partialSettlement: input.answeredLocally && input.changesJudgment }; }
export function evaluateReaderPayoffEvidence(input: { changedKeys: readonly string[]; evidenceRef: string }): { status: "supported" | "missed" } { return { status: input.changedKeys.length > 0 && Boolean(input.evidenceRef) ? "supported" : "missed" }; }
