import crypto from "node:crypto";

export type ForeshadowingStatus = "candidate" | "approved" | "planned" | "seeded" | "reinforced" | "payoff_due" | "resolved" | "invalidated";
export interface Foreshadowing { schemaVersion: "foreshadowing.v1"; foreshadowingId: string; projectId: string; sequence: number; title: string; surfacePerception: string; meaning: string; secrecy: string; type: string; source: string; plannedWindow: string; payoffWindow: string; payoffMode: string; dependencies: string[]; affectedCharacters: string[]; status: ForeshadowingStatus; evidence: Array<{ kind: "setup" | "reinforced" | "payoff"; anchor: string; chapter: string }>; history: Array<{ from: ForeshadowingStatus; to: ForeshadowingStatus; reason: string }>; fingerprint: string; }
export interface FalseClueFairness { schemaVersion: "false-clue-fairness.v1"; foreshadowingId: string; maker: string; whyBelievable: string; counterEvidenceRefs: string[]; correctionMode: string; readerReinterpretation: string; fair: boolean; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
const id = (project: string, sequence: number) => `FS-${project}-${String(sequence).padStart(3, "0")}`;
const transitions: Record<ForeshadowingStatus, ForeshadowingStatus[]> = { candidate: ["approved", "invalidated"], approved: ["planned", "invalidated"], planned: ["seeded", "invalidated"], seeded: ["reinforced", "payoff_due", "invalidated"], reinforced: ["payoff_due", "invalidated"], payoff_due: ["resolved", "invalidated"], resolved: ["invalidated"], invalidated: [] };
export function createForeshadowing(input: Omit<Foreshadowing, "schemaVersion" | "foreshadowingId" | "status" | "evidence" | "history" | "fingerprint">): Foreshadowing { if (!input.projectId.trim() || input.sequence < 1 || !input.title.trim() || !input.surfacePerception.trim() || !input.meaning.trim() || !input.plannedWindow.trim() || !input.payoffWindow.trim()) throw new Error("FORESHADOWING_FIELDS_REQUIRED"); const base = { schemaVersion: "foreshadowing.v1" as const, ...input, foreshadowingId: id(input.projectId, input.sequence), status: "candidate" as const, dependencies: [...input.dependencies], affectedCharacters: [...input.affectedCharacters], evidence: [], history: [] }; return { ...base, fingerprint: hash(base) }; }
export function transitionForeshadowing(item: Foreshadowing, to: ForeshadowingStatus, reason: string): Foreshadowing { if (!reason.trim() || !transitions[item.status].includes(to)) throw new Error("FORESHADOWING_INVALID_TRANSITION"); const base = { ...item, status: to, history: [...item.history, { from: item.status, to, reason }] }; return { ...base, fingerprint: hash(base) }; }
export function recordForeshadowingEvidence(item: Foreshadowing, evidence: { kind: "setup" | "reinforced" | "payoff"; anchor: string; chapter: string }): Foreshadowing { if (!/^manuscript:\/\/[^\s]+$/i.test(evidence.anchor) || !evidence.chapter.trim()) throw new Error("FORESHADOWING_ANCHOR_REQUIRED"); const targetStatus = evidence.kind === "setup" ? "seeded" as const : evidence.kind === "reinforced" ? "reinforced" as const : "resolved" as const; if (evidence.kind === "setup" && item.status !== "planned") throw new Error("FORESHADOWING_SETUP_REQUIRES_PLANNED"); if (evidence.kind === "reinforced" && !["seeded", "reinforced"].includes(item.status)) throw new Error("FORESHADOWING_REINFORCE_REQUIRES_SETUP"); if (evidence.kind === "payoff" && item.status !== "payoff_due") throw new Error("FORESHADOWING_PAYOFF_WINDOW_REQUIRED"); const base = { ...item, status: targetStatus, evidence: [...item.evidence, { ...evidence }] }; return { ...base, fingerprint: hash(base) }; }
export function createFalseClueFairness(input: Omit<FalseClueFairness, "schemaVersion" | "fair" | "fingerprint">): FalseClueFairness { if (!input.foreshadowingId.trim() || !input.maker.trim() || !input.whyBelievable.trim() || !input.counterEvidenceRefs.length || input.counterEvidenceRefs.some((ref) => !/^[a-z][a-z0-9+.-]*:\/\/[^\s]+$/i.test(ref)) || !input.correctionMode.trim() || !input.readerReinterpretation.trim()) throw new Error("FALSE_CLUE_FAIRNESS_REQUIRED"); const base = { schemaVersion: "false-clue-fairness.v1" as const, ...input, counterEvidenceRefs: [...input.counterEvidenceRefs], fair: true as const }; return { ...base, fingerprint: hash(base) }; }
