import crypto from "node:crypto";

export interface ForeshadowingTransformation { schemaVersion: "foreshadowing-transformation.v1"; parentId: string; targetId: string; targetType: string; reason: string; preservedEvidence: string[]; inheritedPayoffWindow: string; fingerprint: string; }
export interface ForeshadowingConflict { schemaVersion: "foreshadowing-conflict.v1"; conflictId: string; items: Array<{ id: string; requirement: string; window: string }>; alternatives: string[]; status: "blocked"; fingerprint: string; }
export interface ForeshadowingWindow { schemaVersion: "foreshadowing-window.v1"; itemId: string; status: "within" | "risk" | "overdue" | "resolved"; fingerprint: string; }
export interface ForeshadowingRepair { schemaVersion: "foreshadowing-repair.v1"; itemId: string; recommended: { kind: string; cost: number }; alternatives: Array<{ kind: string; cost: number }>; fingerprint: string; }
export interface ForeshadowingWaiver { schemaVersion: "foreshadowing-waiver.v1"; itemId: string; status: "waived"; authorIntent: string; riskAcknowledged: boolean; readerFairness: string; keepSequelHook: boolean; fingerprint: string; }
export interface ForeshadowingPublication { schemaVersion: "foreshadowing-publication.v1"; publicationId: string; version: string; frozen: true; readerItems: Array<{ id: string; status: string }>; auditItems: Array<{ id: string; status: string; evidenceFingerprint: string }>; fingerprint: string; }
export interface LegacyForeshadowingMigration { schemaVersion: "legacy-foreshadowing-migration.v1"; candidates: Array<{ candidateId: string; source: string; legacyId: string; text: string; status: "candidate" }>; changesCanon: false; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
export function transformForeshadowing(input: (Omit<ForeshadowingTransformation, "schemaVersion" | "fingerprint" | "parentId"> & { parentId?: string; sourceId?: string })): ForeshadowingTransformation { const parentId = input.parentId ?? input.sourceId ?? ""; if (!parentId.trim() || !input.targetId.trim() || !input.targetType.trim() || !input.reason.trim() || !input.preservedEvidence.length || !input.inheritedPayoffWindow.trim()) throw new Error("FORESHADOW_TRANSFORM_FIELDS_REQUIRED"); const base = { schemaVersion: "foreshadowing-transformation.v1" as const, parentId, targetId: input.targetId, targetType: input.targetType, reason: input.reason, preservedEvidence: [...input.preservedEvidence], inheritedPayoffWindow: input.inheritedPayoffWindow }; return { ...base, fingerprint: hash(base) }; }
export function detectForeshadowingConflict(input: Omit<ForeshadowingConflict, "schemaVersion" | "status" | "fingerprint">): ForeshadowingConflict { if (!input.conflictId.trim() || input.items.length < 2 || !input.alternatives.length) throw new Error("FORESHADOW_CONFLICT_FIELDS_REQUIRED"); const base = { schemaVersion: "foreshadowing-conflict.v1" as const, ...input, items: input.items.map((item) => ({ ...item })), alternatives: [...input.alternatives], status: "blocked" as const }; return { ...base, fingerprint: hash(base) }; }
export function evaluateForeshadowingWindow(input: { itemId: string; currentMilestone: string; targetMilestone: string; hardness: "hard" | "soft"; resolved: boolean }): ForeshadowingWindow { if (!input.itemId.trim() || !input.currentMilestone.trim() || !input.targetMilestone.trim()) throw new Error("FORESHADOW_WINDOW_FIELDS_REQUIRED"); const status = input.resolved ? "resolved" as const : input.currentMilestone === input.targetMilestone ? input.hardness === "hard" ? "overdue" as const : "risk" as const : "within" as const; const base = { schemaVersion: "foreshadowing-window.v1" as const, itemId: input.itemId, status }; return { ...base, fingerprint: hash(base) }; }
export function planForeshadowingRepair(input: { itemId: string; routes: ReadonlyArray<{ kind: string; cost: number }> }): ForeshadowingRepair { if (!input.itemId.trim() || !input.routes.length) throw new Error("FORESHADOW_REPAIR_ROUTES_REQUIRED"); const alternatives = input.routes.map((route) => ({ ...route })); const recommended = [...alternatives].sort((a, b) => a.cost - b.cost)[0]; const base = { schemaVersion: "foreshadowing-repair.v1" as const, itemId: input.itemId, recommended, alternatives }; return { ...base, fingerprint: hash(base) }; }
export function authorizeForeshadowingWaiver(input: Omit<ForeshadowingWaiver, "schemaVersion" | "status" | "fingerprint">): ForeshadowingWaiver { if (!input.itemId.trim() || !input.authorIntent.trim() || !input.riskAcknowledged || !input.readerFairness.trim()) throw new Error("FORESHADOW_WAIVER_NOT_AUTHORIZED"); const base = { schemaVersion: "foreshadowing-waiver.v1" as const, ...input, status: "waived" as const }; return { ...base, fingerprint: hash(base) }; }
export function projectForeshadowingVisibility(input: { meaning: string; surface: string; label: string }, role: "author" | "collaborator" | "reader"): Record<string, string> { if (role === "author") return { meaning: input.meaning, surface: input.surface, label: input.label }; if (role === "collaborator") return { surface: input.surface, label: input.label }; return { label: input.label, surface: input.surface }; }
export function freezeForeshadowingPublication(input: { publicationId: string; version: string; items: ReadonlyArray<{ id: string; status: string; evidenceFingerprint: string }> }): ForeshadowingPublication { if (!input.publicationId.trim() || !input.version.trim() || !input.items.length) throw new Error("FORESHADOW_PUBLICATION_FIELDS_REQUIRED"); const auditItems = input.items.map((item) => ({ ...item })); const readerItems = input.items.map(({ id, status }) => ({ id, status })); const base = { schemaVersion: "foreshadowing-publication.v1" as const, publicationId: input.publicationId, version: input.version, frozen: true as const, readerItems, auditItems }; return { ...base, fingerprint: hash(base) }; }
export function migrateLegacyForeshadowing(input: { records: ReadonlyArray<{ source: string; id: string; text: string }> }): LegacyForeshadowingMigration { if (!input.records.length) throw new Error("LEGACY_FORESHADOWING_REQUIRED"); const candidates = input.records.map((record) => ({ candidateId: `legacy-fs-${hash(record).slice(0, 12)}`, source: record.source, legacyId: record.id, text: record.text, status: "candidate" as const })); const base = { schemaVersion: "legacy-foreshadowing-migration.v1" as const, candidates, changesCanon: false as const }; return { ...base, fingerprint: hash(base) }; }
