import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { listCausalityEdges } from "./causalityGraph.js";
import { listSemanticNodes } from "./semanticNodes.js";
import { resolveInside } from "./pathSafety.js";

export interface ImpactAnalysis { schemaVersion: "impact-analysis.v1"; analysisId: string; projectSlug: string; rootNodeIds: string[]; directNodeIds: string[]; transitiveNodeIds: string[]; affectedNodeIds: string[]; unknownNodeIds: string[]; unaffectedNodeIds: string[]; protectedNodeIds: string[]; protectedAffectedNodeIds: string[]; reason: string; sourceRefs: string[]; blockers: string[]; status: "ready" | "blocked"; rollbackPoint: string; createdAt: string; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function file(root: string, id: string) { return resolveInside(root, `sessions/impact-analyses/${id}.json`); }
async function read<T>(target: string): Promise<T | null> { try { return JSON.parse(await fs.readFile(target, "utf8")) as T; } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return null; throw e; } }
async function write(target: string, value: unknown) { await fs.mkdir(path.dirname(target), { recursive: true }); const tmp = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await fs.rename(tmp, target); }
export function assertImpactAnalysisIntegrity(record: ImpactAnalysis): ImpactAnalysis {
  const { fingerprint, ...content } = record;
  const arraysValid = [record.rootNodeIds, record.directNodeIds, record.transitiveNodeIds, record.affectedNodeIds, record.unknownNodeIds, record.unaffectedNodeIds, record.protectedNodeIds, record.protectedAffectedNodeIds, record.sourceRefs, record.blockers].every((values) => Array.isArray(values) && values.every((value) => typeof value === "string" && value.trim()));
  const valid = record.schemaVersion === "impact-analysis.v1" && record.analysisId.trim() && record.projectSlug.trim() && arraysValid && record.reason.trim() && ["ready", "blocked"].includes(record.status) && record.rollbackPoint.trim() && !Number.isNaN(Date.parse(record.createdAt)) && hash(content) === fingerprint;
  if (!valid) throw new Error("IMPACT_ANALYSIS_INTEGRITY_FAILED");
  return record;
}
export async function readImpactAnalysis(root: string, analysisId: string) { const record = await read<ImpactAnalysis>(file(root, analysisId)); return record ? assertImpactAnalysisIntegrity(record) : null; }
export async function createImpactAnalysis(input: { root: string; projectSlug: string; rootNodeIds: readonly string[]; protectedNodeIds: readonly string[]; reason: string; sourceRefs: readonly string[] }): Promise<ImpactAnalysis> {
  if (!input.sourceRefs.length) throw new Error("IMPACT_SOURCE_REQUIRED"); if (!input.rootNodeIds.length || !input.reason.trim()) throw new Error("IMPACT_FIELDS_REQUIRED");
  const identity = { projectSlug: input.projectSlug, rootNodeIds: [...new Set(input.rootNodeIds)].sort(), protectedNodeIds: [...new Set(input.protectedNodeIds)].sort(), reason: input.reason, sourceRefs: [...input.sourceRefs].sort() }; const analysisId = `impact-${hash(identity).slice(0, 20)}`; const existing = await readImpactAnalysis(input.root, analysisId); if (existing) return existing;
  const [edges, nodes] = await Promise.all([listCausalityEdges(input.root, input.projectSlug), listSemanticNodes(input.root, input.projectSlug)]); const known = new Set(nodes.map((node) => node.semanticId)); const adjacency = new Map<string, string[]>(); const unknown = new Set(identity.rootNodeIds.filter((id) => !known.has(id))); for (const edge of edges) { if (!known.has(edge.sourceNodeId)) unknown.add(edge.sourceNodeId); if (!known.has(edge.targetNodeId)) unknown.add(edge.targetNodeId); adjacency.set(edge.sourceNodeId, [...(adjacency.get(edge.sourceNodeId) || []), edge.targetNodeId]); }
  const direct = new Set(identity.rootNodeIds.filter((id) => known.has(id))); const affected = new Set<string>(); const queue = [...direct]; while (queue.length) { const id = queue.shift()!; if (affected.has(id)) continue; affected.add(id); for (const target of adjacency.get(id) || []) if (known.has(target)) queue.push(target); }
  const directNodeIds = [...direct].sort(); const affectedNodeIds = [...affected].sort(); const transitiveNodeIds = affectedNodeIds.filter((id) => !direct.has(id)); const unknownNodeIds = [...unknown].sort(); const unaffectedNodeIds = [...known].filter((id) => !affected.has(id)).sort(); const protectedSet = new Set(identity.protectedNodeIds); const protectedAffectedNodeIds = affectedNodeIds.filter((id) => protectedSet.has(id)); const blockers = protectedAffectedNodeIds.map(() => "PROTECTED_NODE_AFFECTED"); if (unknownNodeIds.length) blockers.push("UNKNOWN_NODE_REFERENCES"); const base = { schemaVersion: "impact-analysis.v1" as const, analysisId, projectSlug: input.projectSlug, rootNodeIds: identity.rootNodeIds, directNodeIds, transitiveNodeIds, affectedNodeIds, unknownNodeIds, unaffectedNodeIds, protectedNodeIds: identity.protectedNodeIds, protectedAffectedNodeIds, reason: input.reason, sourceRefs: [...input.sourceRefs], blockers: [...new Set(blockers)], status: blockers.length ? "blocked" as const : "ready" as const, rollbackPoint: `rollback-${analysisId}`, createdAt: new Date().toISOString() }; const result = { ...base, fingerprint: hash(base) }; await write(file(input.root, analysisId), result); return result;
}
