import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { resolveInside } from "./pathSafety.js";

export type InformationEventKind = "reveal" | "mislead" | "infer" | "inner";
export interface InformationStateTrace { schemaVersion: "information-state-trace.v1"; traceId: string; projectSlug: string; sceneId: string; povCharacterId: string; states: { authorTruth: Array<{ factId: string; value: string }>; readerKnown: string[]; povKnown: string[]; povBeliefs: Array<{ factId: string; value: string }>; otherPrivate: Array<{ characterId: string; factIds: string[] }>; }; events: Array<{ kind: InformationEventKind; factId: string; target: "reader" | "pov" | "other"; inferenceBasis: string[]; evidenceRefs: string[]; recordedAt: string }>; status: "valid" | "blocked"; issues: string[]; createdAt: string; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function file(root: string, id: string) { return resolveInside(root, `sessions/information-state/${id}.json`); }
async function read<T>(target: string): Promise<T | null> { try { return JSON.parse(await fs.readFile(target, "utf8")) as T; } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return null; throw e; } }
async function write(target: string, value: unknown) { await fs.mkdir(path.dirname(target), { recursive: true }); const tmp = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await fs.rename(tmp, target); }
export async function readInformationStateTrace(root: string, traceId: string) { return read<InformationStateTrace>(file(root, traceId)); }
export async function createInformationStateTrace(input: { root: string; projectSlug: string; sceneId: string; povCharacterId: string; authorTruth: Array<{ factId: string; value: string }>; readerKnown: string[]; povKnown: string[]; povBeliefs: Array<{ factId: string; value: string }>; otherPrivate: Array<{ characterId: string; factIds: string[] }>; sourceRefs: string[] }): Promise<InformationStateTrace> { if (!input.projectSlug.trim() || !input.sceneId.trim() || !input.povCharacterId.trim()) throw new Error("INFORMATION_FIELDS_REQUIRED"); if (!input.sourceRefs.length) throw new Error("INFORMATION_SOURCE_REQUIRED"); const traceId = `information-${input.sceneId}-${input.povCharacterId}`; const existing = await readInformationStateTrace(input.root, traceId); if (existing) return existing; const base = { schemaVersion: "information-state-trace.v1" as const, traceId, projectSlug: input.projectSlug, sceneId: input.sceneId, povCharacterId: input.povCharacterId, states: { authorTruth: input.authorTruth, readerKnown: [...new Set(input.readerKnown)], povKnown: [...new Set(input.povKnown)], povBeliefs: input.povBeliefs, otherPrivate: input.otherPrivate }, events: [], status: "valid" as const, issues: [], createdAt: new Date().toISOString() }; const trace = { ...base, fingerprint: hash(base) }; await write(file(input.root, traceId), trace); return trace; }
export async function appendInformationEvent(root: string, traceId: string, input: { kind: InformationEventKind; factId: string; target: "reader" | "pov" | "other"; inferenceBasis?: readonly string[]; evidenceRefs: readonly string[] }): Promise<InformationStateTrace> { const trace = await readInformationStateTrace(root, traceId); if (!trace) throw new Error("INFORMATION_TRACE_NOT_FOUND"); if (!input.factId.trim() || !input.evidenceRefs.length) throw new Error(input.factId.trim() ? "INFORMATION_EVIDENCE_REQUIRED" : "INFORMATION_EVENT_REQUIRED"); const truthIds = new Set(trace.states.authorTruth.map((fact) => fact.factId)); const povKnown = new Set(trace.states.povKnown); if ((input.target === "pov" && input.kind === "inner" && !povKnown.has(input.factId)) || (input.kind === "infer" && !(input.inferenceBasis || []).every((factId) => truthIds.has(factId) && povKnown.has(factId)))) throw new Error("POV_KNOWLEDGE_BOUNDARY"); const states = { ...trace.states, readerKnown: input.kind === "reveal" && input.target === "reader" ? [...new Set([...trace.states.readerKnown, input.factId])] : trace.states.readerKnown, povKnown: input.kind === "reveal" && input.target === "pov" ? [...new Set([...trace.states.povKnown, input.factId])] : trace.states.povKnown }; const event = { kind: input.kind, factId: input.factId, target: input.target, inferenceBasis: [...(input.inferenceBasis || [])], evidenceRefs: [...input.evidenceRefs], recordedAt: new Date().toISOString() }; const base = { ...trace, states, events: [...trace.events, event], status: "valid" as const, issues: [] as string[] }; const next = { ...base, fingerprint: hash({ ...base, fingerprint: undefined }) }; await write(file(root, traceId), next); return next; }
