import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { resolveInside } from "./pathSafety.js";

export type InformationEventKind = "reveal" | "mislead" | "infer" | "inner";
export interface InformationStateTrace { schemaVersion: "information-state-trace.v1"; traceId: string; projectSlug: string; sceneId: string; povCharacterId: string; states: { authorTruth: Array<{ factId: string; value: string }>; readerKnown: string[]; povKnown: string[]; povBeliefs: Array<{ factId: string; value: string }>; otherPrivate: Array<{ characterId: string; factIds: string[] }>; }; events: Array<{ kind: InformationEventKind; factId: string; target: "reader" | "pov" | "other"; inferenceBasis: string[]; evidenceRefs: string[]; recordedAt: string }>; status: "valid" | "blocked"; issues: string[]; createdAt: string; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function file(root: string, id: string) { return resolveInside(root, `sessions/information-state/${id}.json`); }
async function read<T>(target: string): Promise<T | null> { try { return JSON.parse(await fs.readFile(target, "utf8")) as T; } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return null; throw e; } }
async function write(target: string, value: unknown) { await fs.mkdir(path.dirname(target), { recursive: true }); const tmp = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await fs.rename(tmp, target); }
function nonEmpty(value: unknown): value is string { return typeof value === "string" && value.trim().length > 0; }
function stringArray(value: unknown, required = false): value is string[] { return Array.isArray(value) && (!required || value.length > 0) && value.every(nonEmpty); }
function factArray(value: unknown): value is Array<{ factId: string; value: string }> { return Array.isArray(value) && value.every((item) => Boolean(item && nonEmpty(item.factId) && nonEmpty(item.value))); }
export function assertInformationStateTraceIntegrity(trace: InformationStateTrace, expectedId?: string): InformationStateTrace {
  const { fingerprint, ...base } = trace;
  const truthIds = new Set(trace.states?.authorTruth?.map((fact) => fact.factId));
  const unique = (values: string[]) => new Set(values).size === values.length;
  const statesValid = Boolean(trace.states && factArray(trace.states.authorTruth) && factArray(trace.states.povBeliefs) && stringArray(trace.states.readerKnown) && stringArray(trace.states.povKnown) && Array.isArray(trace.states.otherPrivate) && trace.states.otherPrivate.every((item) => Boolean(item && nonEmpty(item.characterId) && stringArray(item.factIds))) && unique(trace.states.authorTruth.map((fact) => fact.factId)) && unique(trace.states.povBeliefs.map((fact) => fact.factId)) && trace.states.readerKnown.every((id) => truthIds.has(id)) && trace.states.povKnown.every((id) => truthIds.has(id)) && trace.states.povBeliefs.every((belief) => truthIds.has(belief.factId)) && trace.states.otherPrivate.every((item) => item.factIds.every((id) => truthIds.has(id))));
  const eventsValid = Array.isArray(trace.events) && trace.events.every((event) => Boolean(event && ["reveal", "mislead", "infer", "inner"].includes(event.kind) && nonEmpty(event.factId) && ["reader", "pov", "other"].includes(event.target) && stringArray(event.inferenceBasis) && stringArray(event.evidenceRefs, true) && nonEmpty(event.recordedAt) && Number.isFinite(Date.parse(event.recordedAt)) && truthIds.has(event.factId) && event.inferenceBasis.every((id) => truthIds.has(id))));
  const valid = trace.schemaVersion === "information-state-trace.v1" && (!expectedId || trace.traceId === expectedId) && [trace.traceId, trace.projectSlug, trace.sceneId, trace.povCharacterId, trace.createdAt].every(nonEmpty) && Number.isFinite(Date.parse(trace.createdAt)) && statesValid && eventsValid && ["valid", "blocked"].includes(trace.status) && stringArray(trace.issues) && ((trace.status === "valid" && trace.issues.length === 0) || (trace.status === "blocked" && trace.issues.length > 0)) && /^[a-f0-9]{64}$/i.test(trace.fingerprint) && hash(base) === trace.fingerprint;
  if (!valid) throw new Error("INFORMATION_STATE_INTEGRITY_FAILED");
  return trace;
}
export async function readInformationStateTrace(root: string, traceId: string) { const trace = await read<InformationStateTrace>(file(root, traceId)); return trace ? assertInformationStateTraceIntegrity(trace, traceId) : null; }
export async function createInformationStateTrace(input: { root: string; projectSlug: string; sceneId: string; povCharacterId: string; authorTruth: Array<{ factId: string; value: string }>; readerKnown: string[]; povKnown: string[]; povBeliefs: Array<{ factId: string; value: string }>; otherPrivate: Array<{ characterId: string; factIds: string[] }>; sourceRefs: string[] }): Promise<InformationStateTrace> { if (!input.projectSlug.trim() || !input.sceneId.trim() || !input.povCharacterId.trim()) throw new Error("INFORMATION_FIELDS_REQUIRED"); if (!input.sourceRefs.length) throw new Error("INFORMATION_SOURCE_REQUIRED"); const traceId = `information-${input.sceneId}-${input.povCharacterId}`; const existing = await readInformationStateTrace(input.root, traceId); if (existing) return existing; const base = { schemaVersion: "information-state-trace.v1" as const, traceId, projectSlug: input.projectSlug, sceneId: input.sceneId, povCharacterId: input.povCharacterId, states: { authorTruth: input.authorTruth, readerKnown: [...new Set(input.readerKnown)], povKnown: [...new Set(input.povKnown)], povBeliefs: input.povBeliefs, otherPrivate: input.otherPrivate }, events: [], status: "valid" as const, issues: [], createdAt: new Date().toISOString() }; const trace = { ...base, fingerprint: hash(base) }; await write(file(input.root, traceId), trace); return trace; }
export async function appendInformationEvent(root: string, traceId: string, input: { kind: InformationEventKind; factId: string; target: "reader" | "pov" | "other"; inferenceBasis?: readonly string[]; evidenceRefs: readonly string[] }): Promise<InformationStateTrace> { const trace = await readInformationStateTrace(root, traceId); if (!trace) throw new Error("INFORMATION_TRACE_NOT_FOUND"); if (!input.factId.trim() || !input.evidenceRefs.length) throw new Error(input.factId.trim() ? "INFORMATION_EVIDENCE_REQUIRED" : "INFORMATION_EVENT_REQUIRED"); const truthIds = new Set(trace.states.authorTruth.map((fact) => fact.factId)); const povKnown = new Set(trace.states.povKnown); if ((input.target === "pov" && input.kind === "inner" && !povKnown.has(input.factId)) || (input.kind === "infer" && !(input.inferenceBasis || []).every((factId) => truthIds.has(factId) && povKnown.has(factId)))) throw new Error("POV_KNOWLEDGE_BOUNDARY"); const states = { ...trace.states, readerKnown: input.kind === "reveal" && input.target === "reader" ? [...new Set([...trace.states.readerKnown, input.factId])] : trace.states.readerKnown, povKnown: input.kind === "reveal" && input.target === "pov" ? [...new Set([...trace.states.povKnown, input.factId])] : trace.states.povKnown }; const event = { kind: input.kind, factId: input.factId, target: input.target, inferenceBasis: [...(input.inferenceBasis || [])], evidenceRefs: [...input.evidenceRefs], recordedAt: new Date().toISOString() }; const base = { ...trace, states, events: [...trace.events, event], status: "valid" as const, issues: [] as string[] }; const next = { ...base, fingerprint: hash({ ...base, fingerprint: undefined }) }; await write(file(root, traceId), next); return next; }
