export function arbitratePrimaryAction(input: { unsaved: boolean; recapPending: boolean; qualityMissing: boolean; overdueObligations: number }): { primary: string; secondary: string[] } { const primary = input.unsaved ? "save-or-resolve-unsaved" : input.recapPending ? "confirm-recap" : input.qualityMissing ? "obtain-quality-report" : input.overdueObligations ? "settle-obligation" : "review"; const secondary = [input.recapPending && primary !== "confirm-recap" ? "confirm-recap" : "", input.qualityMissing && primary !== "obtain-quality-report" ? "obtain-quality-report" : "", input.overdueObligations && primary !== "settle-obligation" ? "settle-obligation" : ""].filter(Boolean); return { primary, secondary }; }
export function prioritizeSafety(input: { recoveryPending: boolean; l2Pending: boolean; candidateReviewable: boolean }): { action: string; candidateVisible: boolean; candidateExecutable: boolean } { return { action: input.recoveryPending ? "recover-data" : input.l2Pending ? "resolve-l2" : "review-candidate", candidateVisible: input.candidateReviewable, candidateExecutable: !input.recoveryPending && !input.l2Pending }; }
export function registerSurfaces(input: { surfaces: readonly { id: string; command: string; authority: string; phase: string }[]; expected: number }): { complete: boolean; missing: number } { return { complete: input.surfaces.length >= input.expected && input.surfaces.every((surface) => surface.id && surface.command && surface.authority && surface.phase), missing: Math.max(0, input.expected - input.surfaces.length) }; }
export function preserveStageOnViewSwitch(input: { stage: string; primaryAction: string; cursor: string; switchedView: string }): { stage: string; primaryAction: string; cursor: string; regenerateOutline: false } { return { stage: input.stage, primaryAction: input.primaryAction, cursor: input.cursor, regenerateOutline: false }; }
export function parseAuthorReceipt(input: { text: string; continueRequested: boolean; hardConstraints: readonly string[]; parseAmbiguous: boolean }): { modelCalls: 0; fileWrites: 0; corrected: boolean; authorization: boolean; constraints: string[] } { return { modelCalls: 0, fileWrites: 0, corrected: input.parseAmbiguous, authorization: input.continueRequested, constraints: [...input.hardConstraints] }; }
export function deduplicateAction(input: { actionIds: readonly string[] }): { created: number; stateKey: string } { const unique = [...new Set(input.actionIds)]; return { created: unique.length ? 1 : 0, stateKey: unique[0] || "" }; }
export function isolateTaskChapter(input: { taskChapter: string; currentChapter: string }): { inserted: false; taskChapter: string; reviewable: true } { return { inserted: false, taskChapter: input.taskChapter, reviewable: true }; }
export function reconcileWorkspace(input: { localFingerprint: string; serverFingerprint: string; choice?: "compare" | "save-candidate" | "discard" }): { conflict: boolean; action: string } { const conflict = input.localFingerprint !== input.serverFingerprint; return { conflict, action: conflict ? input.choice || "compare" : "none" }; }
export function recoverFailedCard(input: { reason: string; modelCalled: boolean; bodyWritten: boolean; sameActionId: boolean }): { resumable: boolean; reason: string; sameCard: true } { return { resumable: !input.modelCalled && !input.bodyWritten && input.sameActionId, reason: input.reason, sameCard: true }; }
export function isolateProjectContinuation(input: { projectId: string; activeProjectId: string; cursor: string }): { isolated: boolean; cursor: string } { return { isolated: input.projectId === input.activeProjectId, cursor: input.cursor }; }
export function gateShellShadow(input: { safeBlock: boolean; deepLinkVerified: boolean; keyboardVerified: boolean; recoveryVerified: boolean; legacyFixtureVerified: boolean }): { enabled: boolean; rollback: boolean } { const enabled = !input.safeBlock && input.deepLinkVerified && input.keyboardVerified && input.recoveryVerified && input.legacyFixtureVerified; return { enabled, rollback: !enabled }; }
export function assessJourneyEvidence(input: { firstScreenOnly: boolean; refreshLosesDialogue: boolean; failureNeedsHistory: boolean }): { status: "implemented" | "released"; reasons: string[] } { const reasons = [input.firstScreenOnly ? "first-screen-only" : "", input.refreshLosesDialogue ? "refresh-loss" : "", input.failureNeedsHistory ? "history-detour" : ""].filter(Boolean); return { status: reasons.length ? "implemented" : "released", reasons }; }
