import crypto from "node:crypto";

export interface KernelProof { schemaVersion: "kernel-proof.v1"; projectSlug?: string; kernelId: string; version: string; schemaRefs: string[]; runtimeValidators: string[]; generatedTypes: string[]; capabilityManifestRef: string; readWriteMatrixRef: string; negotiatedVersions: string[]; unknownVersionPolicy: "read-only"; status: "verified"; fingerprint: string; }
export interface MutationValidation { schemaVersion: "mutation-validation.v1"; commandId: string; valid: boolean; fingerprint: string; }
export interface CandidateBoundary { schemaVersion: "candidate-boundary.v1"; candidateId: string; parentFingerprint: string; semanticId: string; evidenceAnchors: string[]; stalePropagation: string[]; authorLocks: string[]; rollbackRef: string; canonWrite: false; fingerprint: string; }
export interface ObligationCoreProof { schemaVersion: "obligation-core-proof.v1"; obligationId: string; type: string; setupEvidence: string[]; payoffContract: string; windows: string[]; eventGuard: string; planFactSeparated: true; status: "verified"; fingerprint: string; }
export interface AISafetyGate { schemaVersion: "ai-safety-gate.v1"; taskId: string; riskLevel: string; capabilityFloor: string; contextManifest: string; budgetReserved: true; callFingerprint: string; retryPolicy: string; dataBoundary: string; sourceRightsVerified: true; status: "allowed"; fingerprint: string; }
export interface LongMemoryProof { schemaVersion: "long-memory-proof.v1"; projectId: string; claimEventAuthority: string; entityIds: string[]; temporalDomain: string; knowledgeDomain: string; conflictSet: string; settlementProjection: string; eligibilityFirst: true; rebuildable: true; status: "verified"; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
export function createKernelProof(input: Omit<KernelProof, "schemaVersion" | "status" | "fingerprint">): KernelProof { if (!input.kernelId.trim() || !input.version.trim() || !input.schemaRefs.length || !input.runtimeValidators.length || !input.generatedTypes.length || !input.capabilityManifestRef.trim() || !input.readWriteMatrixRef.trim() || !input.negotiatedVersions.length || input.unknownVersionPolicy !== "read-only") throw new Error("KERNEL_PROOF_FIELDS_REQUIRED"); const base = { schemaVersion: "kernel-proof.v1" as const, ...(input.projectSlug ? { projectSlug: input.projectSlug.trim() } : {}), kernelId: input.kernelId, version: input.version, schemaRefs: [...input.schemaRefs], runtimeValidators: [...input.runtimeValidators], generatedTypes: [...input.generatedTypes], capabilityManifestRef: input.capabilityManifestRef, readWriteMatrixRef: input.readWriteMatrixRef, negotiatedVersions: [...input.negotiatedVersions], unknownVersionPolicy: "read-only" as const, status: "verified" as const }; return { ...base, fingerprint: hash(base) }; }
export function validateMutationPlan(input: { commandId: string; idempotencyKey: string; expectedFingerprint: string; writes: Array<{ semantic: string; authority: string }>; eventTypes: string[]; recoveryAction: string }): MutationValidation { const valid = Boolean(input.commandId.trim() && input.idempotencyKey.trim() && input.expectedFingerprint.trim() && input.writes.length && input.writes.every((write) => write.authority.trim()) && input.eventTypes.length && input.recoveryAction.trim()); const base = { schemaVersion: "mutation-validation.v1" as const, commandId: input.commandId, valid }; return { ...base, fingerprint: hash(base) }; }
export function createCandidateBoundary(input: Omit<CandidateBoundary, "schemaVersion" | "fingerprint">): CandidateBoundary { if (!input.candidateId.trim() || !input.parentFingerprint.trim() || !input.semanticId.trim() || !input.evidenceAnchors.length || !input.rollbackRef.trim() || input.canonWrite) throw new Error("CANDIDATE_BOUNDARY_INVALID"); const base = { schemaVersion: "candidate-boundary.v1" as const, ...input, evidenceAnchors: [...input.evidenceAnchors], stalePropagation: [...input.stalePropagation], authorLocks: [...input.authorLocks], canonWrite: false as const }; return { ...base, fingerprint: hash(base) }; }
export function createObligationCoreProof(input: Omit<ObligationCoreProof, "schemaVersion" | "status" | "fingerprint">): ObligationCoreProof { if (!input.obligationId.trim() || !input.type.trim() || !input.setupEvidence.length || !input.payoffContract.trim() || !input.windows.length || !input.eventGuard.trim() || !input.planFactSeparated) throw new Error("OBLIGATION_CORE_PROOF_INVALID"); const base = { schemaVersion: "obligation-core-proof.v1" as const, ...input, setupEvidence: [...input.setupEvidence], windows: [...input.windows], planFactSeparated: true as const, status: "verified" as const }; return { ...base, fingerprint: hash(base) }; }
export function createAISafetyGate(input: Omit<AISafetyGate, "schemaVersion" | "status" | "fingerprint">): AISafetyGate { if (!input.taskId.trim() || !input.riskLevel.trim() || !input.capabilityFloor.trim() || !input.contextManifest.trim() || !input.budgetReserved || !input.callFingerprint.trim() || !input.retryPolicy.trim() || !input.dataBoundary.trim() || !input.sourceRightsVerified) throw new Error("AI_SAFETY_GATE_BLOCKED"); const base = { schemaVersion: "ai-safety-gate.v1" as const, ...input, budgetReserved: true as const, sourceRightsVerified: true as const, status: "allowed" as const }; return { ...base, fingerprint: hash(base) }; }
export function createLongMemoryProof(input: Omit<LongMemoryProof, "schemaVersion" | "status" | "fingerprint">): LongMemoryProof { if (!input.projectId.trim() || !input.claimEventAuthority.trim() || !input.entityIds.length || !input.temporalDomain.trim() || !input.knowledgeDomain.trim() || !input.conflictSet.trim() || !input.settlementProjection.trim() || !input.eligibilityFirst || !input.rebuildable) throw new Error("LONG_MEMORY_PROOF_INVALID"); const base = { schemaVersion: "long-memory-proof.v1" as const, ...input, entityIds: [...input.entityIds], eligibilityFirst: true as const, rebuildable: true as const, status: "verified" as const }; return { ...base, fingerprint: hash(base) }; }
