export function applyQualityStrategy(input: { strategy: "quality" | "balanced" | "speed"; candidateCount: number; reviewDepth: number; chapterThreshold: number; schemaFingerprint: string }): { candidateCount: number; reviewDepth: number; chapterThreshold: number; schemaFingerprint: string } {
  const scale = input.strategy === "quality" ? 1.5 : input.strategy === "speed" ? 0.6 : 1;
  return { candidateCount: Math.max(1, Math.round(input.candidateCount * scale)), reviewDepth: Math.max(1, Math.round(input.reviewDepth * scale)), chapterThreshold: input.chapterThreshold, schemaFingerprint: input.schemaFingerprint };
}
export function advanceEvidenceStatus(input: { hasType: boolean; hasTest: boolean; hasScreenshot: boolean; immutableEvidence: boolean; requiredRuntimeEvidence: boolean; deletedTest: boolean }): "implemented" | "verified" | "released" {
  if (input.deletedTest || !input.hasType || !input.hasTest || !input.hasScreenshot) return "implemented";
  if (!input.immutableEvidence || !input.requiredRuntimeEvidence) return "implemented";
  return "released";
}
export function classifyClaimAuthority(input: { source: "plan" | "candidate" | "canon"; adopted: boolean }): "plan" | "candidate" | "canon" { return input.source === "canon" && input.adopted ? "canon" : input.source; }
export function enforceCharacterVisibility(input: { authorTruth: boolean; characterHasEvidence: boolean; leaksTruth: boolean }): { authorVisible: boolean; characterVisible: boolean; rejected: boolean } { return { authorVisible: input.authorTruth, characterVisible: input.characterHasEvidence, rejected: input.leaksTruth && input.authorTruth && !input.characterHasEvidence }; }
export function resolveTemporalKnowledge(input: { currentChapter: number; injuryChapter: number; recoveryChapter: number }): "injured" | "recovered" | "unknown" { if (input.currentChapter >= input.recoveryChapter) return "recovered"; if (input.currentChapter >= input.injuryChapter) return "injured"; return "unknown"; }
export function keepSameNameSeparate(input: { sameName: boolean; aliasAssertion: boolean; identityEvidence: boolean }): { merged: boolean; needsEvidence: boolean } { const merged = !input.sameName || input.aliasAssertion || input.identityEvidence; return { merged, needsEvidence: input.sameName && !merged }; }
export function preserveContradiction(input: { claims: readonly string[]; resolved: boolean }): { status: "resolved" | "open"; claims: string[] } { return { status: input.resolved ? "resolved" : "open", claims: [...input.claims] }; }
export function supersedeClaim(input: { current: string; superseded: readonly string[]; replacement: string }): { current: string; excluded: string[]; history: string[] } { return { current: input.replacement, excluded: [...input.superseded, input.current], history: [...input.superseded, input.current] }; }
export function transferCharacterKnowledge(input: { evidenceChapter: number; targetChapter: number; evidencePresent: boolean }): { known: boolean; stale: boolean } { return { known: input.evidencePresent && input.targetChapter >= input.evidenceChapter, stale: !input.evidencePresent }; }
export function preserveCharacterBelief(input: { belief: string; canonFact: string; isTrue: boolean }): { belief: string; canonFact: string; factEligible: boolean } { return { belief: input.belief, canonFact: input.canonFact, factEligible: input.isTrue }; }
export function separateReaderAndPov(input: { readerKnows: boolean; povKnows: boolean; avoidsWithoutCause: boolean }): { readerKnows: boolean; povKnows: boolean; rejected: boolean } { return { readerKnows: input.readerKnows, povKnows: input.povKnows, rejected: input.avoidsWithoutCause && input.readerKnows && !input.povKnows }; }
export function filterEligibility(input: { claims: readonly { id: string; obsolete: boolean; visible: boolean }[] }): string[] { return input.claims.filter((claim) => !claim.obsolete && claim.visible).map((claim) => claim.id); }
export function buildRetconImpactReport(input: { impacted: Record<string, readonly string[]>; adopted: boolean }): { impacted: Record<string, string[]>; authorityChanged: boolean; recompute: string[] } { const impacted = Object.fromEntries(Object.entries(input.impacted).map(([key, values]) => [key, [...values]])); return { impacted, authorityChanged: input.adopted, recompute: input.adopted ? Object.values(impacted).flat() : [] }; }
export function propagateEvidenceDeletion(input: { descendants: readonly string[]; propagationComplete: boolean }): { status: "stale" | "invalidated" | "blocked"; blocked: boolean; affected: string[] } { const status = input.propagationComplete ? "invalidated" : "blocked"; return { status, blocked: !input.propagationComplete, affected: [...input.descendants] }; }
export function preserveBodyTruthOverSummary(input: { bodyClaim: string; summaryClaim: string; summaryCorrected: boolean }): { canon: string; summary: string } { return { canon: input.bodyClaim, summary: input.summaryCorrected ? input.bodyClaim : input.summaryClaim }; }
export function validateLossyCompression(input: { inputRefs: readonly string[]; omitted: readonly string[]; requiredFields: readonly string[]; retainedFields: readonly string[]; target: string; strategyVersion: string; inputTokens: number; outputTokens: number; knownLosses: readonly string[]; reconstructionPointer: string }): { valid: boolean; inputRefs: string[]; omitted: string[]; retainedFields: string[]; target: string; strategyVersion: string; inputTokens: number; outputTokens: number; tokenSavings: number; knownLosses: string[]; reconstructionPointer: string; rollback: boolean } {
  const tokenSavings = input.inputTokens - input.outputTokens;
  const valid = input.inputRefs.length > 0 && input.requiredFields.every((field) => input.retainedFields.includes(field)) && Boolean(input.target.trim() && input.strategyVersion.trim() && input.reconstructionPointer.trim()) && Number.isInteger(input.inputTokens) && input.inputTokens >= 0 && Number.isInteger(input.outputTokens) && input.outputTokens >= 0 && input.outputTokens <= input.inputTokens && tokenSavings >= 0 && Array.isArray(input.knownLosses);
  return { valid, inputRefs: [...input.inputRefs], omitted: [...input.omitted], retainedFields: [...input.retainedFields], target: input.target, strategyVersion: input.strategyVersion, inputTokens: input.inputTokens, outputTokens: input.outputTokens, tokenSavings, knownLosses: [...input.knownLosses], reconstructionPointer: input.reconstructionPointer, rollback: !valid };
}
export function rankEligibleClaims(input: { claims: readonly { id: string; score: number; obsolete: boolean; visible: boolean }[] }): string[] { return input.claims.filter((claim) => !claim.obsolete && claim.visible).sort((a, b) => b.score - a.score).map((claim) => claim.id); }
export function constrainKnowledgeQuery(input: { targetChapter?: number; pov?: string; readerProgress?: number; claims: readonly { id: string; chapter: number; pov: string; progress: number }[] }): { status: "bounded" | "insufficient-boundary"; ids: string[] } { if (input.targetChapter === undefined || !input.pov) return { status: "insufficient-boundary", ids: [] }; return { status: "bounded", ids: input.claims.filter((claim) => claim.chapter <= input.targetChapter! && claim.pov === input.pov && claim.progress <= (input.readerProgress ?? Number.MAX_SAFE_INTEGER)).map((claim) => claim.id) }; }
export function groupEvidenceFamily(input: { sources: readonly { family: string; independent: boolean }[] }): { families: string[]; diversity: number } { const families = [...new Set(input.sources.map((source) => source.family))]; return { families, diversity: input.sources.filter((source) => source.independent).length }; }
export function reportEvidenceGap(input: { planOnly: boolean; extractionFailed: boolean; contradictionKnown: boolean }): { states: string[]; saysNoContradiction: boolean } { const states = [input.planOnly ? "plan-only" : "", input.extractionFailed ? "extraction_failed" : ""].filter(Boolean); return { states, saysNoContradiction: !input.contradictionKnown && !input.planOnly && !input.extractionFailed }; }
export function gateGenerationOnConflict(input: { highRiskConflict: boolean; proposedPlan: string; redEvidence: readonly string[]; blueEvidence: readonly string[] }): { allowed: boolean; clarification: string; red: string[]; blue: string[] } { return { allowed: !input.highRiskConflict, clarification: input.highRiskConflict ? input.proposedPlan : "", red: [...input.redEvidence], blue: [...input.blueEvidence] }; }
export function keepNewFactsCandidate(input: { adopted: boolean; worldRuleConfirmed: boolean; settled: boolean; claimId: string }): { status: "candidate" | "canon"; claimId: string } { const canon = input.adopted && input.worldRuleConfirmed && input.settled; return { status: canon ? "canon" : "candidate", claimId: input.claimId }; }
export function assessMemoryHealth(input: { chapterCoverage: number; identityConflicts: number; staleProjections: number }): { coverage: number; risks: string[]; healthy: boolean } { const risks = [input.chapterCoverage < 1 ? "coverage" : "", input.identityConflicts ? "identity-conflict" : "", input.staleProjections ? "stale-projection" : ""].filter(Boolean); return { coverage: input.chapterCoverage, risks, healthy: risks.length === 0 }; }
export function deterministicRebuild(input: { eventFingerprint: string; schema: string; rebuiltFingerprint: string; emitsNewTruthEvent: boolean }): { identical: boolean; emitsNewTruthEvent: boolean } { return { identical: input.eventFingerprint === input.rebuiltFingerprint && Boolean(input.schema), emitsNewTruthEvent: input.emitsNewTruthEvent }; }
export function preserveEligibilityOnEmbeddingFallback(input: { primaryFailed: boolean; primaryIds: readonly string[]; fallbackIds: readonly string[]; excluded: readonly string[] }): { mode: "primary" | "fallback"; ids: string[]; excluded: string[] } { return { mode: input.primaryFailed ? "fallback" : "primary", ids: [...(input.primaryFailed ? input.fallbackIds : input.primaryIds)].filter((id) => !input.excluded.includes(id)), excluded: [...input.excluded] }; }
export function auditContinuity(input: { unknowns: number; earlyKnowledge: number; mergedIdentities: number; scannedRatio: number }): { passed: boolean; issues: string[]; coverage: number } { const issues = [input.earlyKnowledge ? "early-knowledge" : "", input.mergedIdentities ? "merged-identity" : "", input.scannedRatio < 1 ? "unscanned" : "", input.unknowns ? "unknown-boundary" : ""].filter(Boolean); return { passed: issues.length === 0, issues, coverage: input.scannedRatio }; }
export function activateK5(input: { shadowVerified: boolean; secretBoundaryVerified: boolean; retconVerified: boolean; deletionVerified: boolean; fallbackVerified: boolean }): { active: boolean; missing: string[] } { const checks = { shadow: input.shadowVerified, secret: input.secretBoundaryVerified, retcon: input.retconVerified, deletion: input.deletionVerified, fallback: input.fallbackVerified }; const missing = Object.entries(checks).filter(([, value]) => !value).map(([key]) => key); return { active: missing.length === 0, missing }; }
