import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { resolveInside } from "./pathSafety.js";
export interface NegativePreferenceException { scope: string; rationale: string; evidenceRefs: string[]; }
export interface NegativePreference { schemaVersion: "negative-preference.v1"; preferenceId: string; projectSlug: string; scope: string; rejectedPattern: string; rationale: string; confidence: number; rawTextBlacklist: string[]; sourceRefs: string[]; triggerConditions: string[]; counterexamples: string[]; rejectedMechanism?: string; exceptions: NegativePreferenceException[]; createdAt: string; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function file(root: string, id: string) { return resolveInside(root, `sessions/negative-preferences/${id}.json`); }
async function read<T>(target: string): Promise<T | null> { try { return JSON.parse(await fs.readFile(target, "utf8")) as T; } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return null; throw e; } }
async function write(target: string, value: unknown) { await fs.mkdir(path.dirname(target), { recursive: true }); const tmp = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await fs.rename(tmp, target); }
export async function readNegativePreference(root: string, preferenceId: string) { return read<NegativePreference>(file(root, preferenceId)); }
export async function createNegativePreference(input: { root: string; projectSlug: string; preferenceId: string; scope: string; rejectedPattern: string; rationale: string; confidence: number; sourceRefs: readonly string[]; triggerConditions?: readonly string[]; counterexamples?: readonly string[]; rejectedMechanism?: string; exceptions?: readonly NegativePreferenceException[] }): Promise<NegativePreference> { if (!input.projectSlug.trim() || !input.preferenceId.trim() || !input.scope.trim() || !input.rejectedPattern.trim() || !input.rationale.trim()) throw new Error("NEGATIVE_PREFERENCE_FIELDS_REQUIRED"); if (input.confidence <= 0 || input.confidence > 1) throw new Error("NEGATIVE_PREFERENCE_CONFIDENCE_REQUIRED"); if (!input.sourceRefs.length) throw new Error("NEGATIVE_PREFERENCE_SOURCE_REQUIRED"); const existing = await readNegativePreference(input.root, input.preferenceId); if (existing) return existing; const base = { schemaVersion: "negative-preference.v1" as const, preferenceId: input.preferenceId, projectSlug: input.projectSlug, scope: input.scope, rejectedPattern: input.rejectedPattern, rationale: input.rationale, confidence: input.confidence, rawTextBlacklist: [], sourceRefs: [...input.sourceRefs], triggerConditions: [...(input.triggerConditions || [])], counterexamples: [...(input.counterexamples || [])], rejectedMechanism: input.rejectedMechanism?.trim() || undefined, exceptions: [...(input.exceptions || [])], createdAt: new Date().toISOString() }; const preference = { ...base, fingerprint: hash(base) }; await write(file(input.root, input.preferenceId), preference); return preference; }
function normalizeMechanism(value: string): string { const aliases: Record<string, string> = { state: "summarize", states: "summarize", feeling: "emotion", feelings: "emotion", directly: "direct", explain: "summarize", explains: "summarize" }; const ignored = new Set(["the", "a", "an"]); return [...new Set(value.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]+/g, " ").trim().split(/\s+/).filter(Boolean).filter((token) => !ignored.has(token)).map((token) => aliases[token] || token))].sort().join(" "); }
export function evaluateNegativePreferenceSuggestion(preference: NegativePreference, input: { proposedPattern: string; proposedMechanism?: string; newScene: string; differenceExplanation: string; evidenceRefs?: readonly string[] }): { status: "allowed" | "blocked"; reason: string | null } { const exception = preference.exceptions.find((item) => item.scope === input.newScene && item.evidenceRefs.every((ref) => input.evidenceRefs?.includes(ref))); if (exception) return { status: "allowed", reason: "SCOPED_EXCEPTION" }; if (input.newScene !== preference.scope && preference.scope.includes(":")) return { status: "allowed", reason: "SCOPE_NOT_APPLICABLE" }; const mechanismMatch = Boolean(preference.rejectedMechanism && input.proposedMechanism && normalizeMechanism(preference.rejectedMechanism) === normalizeMechanism(input.proposedMechanism)); if (mechanismMatch) return { status: "blocked", reason: "NEGATIVE_MECHANISM_RECURRING" }; const similar = input.proposedPattern.includes(preference.rejectedPattern) || preference.rejectedPattern.includes(input.proposedPattern); if (similar && (!input.differenceExplanation.trim() || !input.evidenceRefs?.length)) return { status: "blocked", reason: "DIFFERENCE_EXPLANATION_REQUIRED" }; return { status: "allowed", reason: null }; }
