import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { resolveInside } from "./pathSafety.js";

export interface ProseSegment { schemaVersion: "prose-segment.v1"; semanticId: string; projectSlug: string; sceneId: string; beatId: string; text: string; beforeBoundaryFingerprint: string; afterBoundaryFingerprint: string; sourceCandidateId: string; sourceRefs: string[]; status: "candidate" | "adopted" | "stale"; createdAt: string; updatedAt: string; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function segmentId(sceneId: string, beatId: string) { return `segment-${sceneId}-${beatId}`.replace(/[^a-zA-Z0-9_-]/g, "-"); }
function file(root: string, id: string) { return resolveInside(root, `sessions/prose-segments/${id}.json`); }
async function read<T>(target: string): Promise<T | null> { try { return JSON.parse(await fs.readFile(target, "utf8")) as T; } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return null; throw e; } }
async function write(target: string, value: unknown) { await fs.mkdir(path.dirname(target), { recursive: true }); const tmp = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await fs.rename(tmp, target); }
export function assertProseSegmentIntegrity(segment: ProseSegment, expectedSemanticId?: string): ProseSegment { const { fingerprint: _fingerprint, ...base } = segment; const valid = segment.schemaVersion === "prose-segment.v1" && (!expectedSemanticId || segment.semanticId === expectedSemanticId) && Boolean(segment.semanticId?.trim() && segment.projectSlug?.trim() && segment.sceneId?.trim() && segment.beatId?.trim() && segment.text?.trim() && segment.beforeBoundaryFingerprint?.trim() && segment.afterBoundaryFingerprint?.trim() && segment.sourceCandidateId?.trim()) && Array.isArray(segment.sourceRefs) && segment.sourceRefs.length > 0 && segment.sourceRefs.every((ref) => typeof ref === "string" && ref.trim()) && ["candidate", "adopted", "stale"].includes(segment.status) && typeof segment.createdAt === "string" && segment.createdAt.trim() && typeof segment.updatedAt === "string" && segment.updatedAt.trim() && /^[a-f0-9]{64}$/i.test(segment.fingerprint) && hash(base) === segment.fingerprint; if (!valid) throw new Error("PROSE_SEGMENT_INTEGRITY_FAILED"); return segment; }
export async function readProseSegment(root: string, semanticId: string) { const segment = await read<ProseSegment>(file(root, semanticId)); return segment ? assertProseSegmentIntegrity(segment, semanticId) : null; }
export async function createProseSegment(input: { root: string; projectSlug: string; sceneId: string; beatId: string; text: string; beforeText: string; afterText: string; sourceCandidateId: string; sourceRefs: readonly string[] }): Promise<ProseSegment> { if (!input.projectSlug.trim() || !input.sceneId.trim() || !input.beatId.trim() || !input.text.trim() || !input.sourceCandidateId.trim()) throw new Error("PROSE_SEGMENT_FIELDS_REQUIRED"); if (!input.sourceRefs.length) throw new Error("PROSE_SEGMENT_SOURCE_REQUIRED"); const semanticId = segmentId(input.sceneId, input.beatId); const existing = await readProseSegment(input.root, semanticId); if (existing) return existing; const base = { schemaVersion: "prose-segment.v1" as const, semanticId, projectSlug: input.projectSlug, sceneId: input.sceneId, beatId: input.beatId, text: input.text, beforeBoundaryFingerprint: hash(input.beforeText), afterBoundaryFingerprint: hash(input.afterText), sourceCandidateId: input.sourceCandidateId, sourceRefs: [...input.sourceRefs], status: "candidate" as const, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; const segment = { ...base, fingerprint: hash(base) }; await write(file(input.root, semanticId), segment); return segment; }
export async function applyProseSegmentPatch(root: string, semanticId: string, input: { beforeBoundaryFingerprint: string; afterBoundaryFingerprint: string; replacementText: string; sourceRefs: readonly string[] }): Promise<ProseSegment> { const segment = await readProseSegment(root, semanticId); if (!segment) throw new Error("PROSE_SEGMENT_NOT_FOUND"); if (segment.beforeBoundaryFingerprint !== input.beforeBoundaryFingerprint || segment.afterBoundaryFingerprint !== input.afterBoundaryFingerprint) throw new Error("PROSE_SEGMENT_ANCHOR_MISMATCH"); if (!input.replacementText.trim() || !input.sourceRefs.length) throw new Error("PROSE_SEGMENT_PATCH_EVIDENCE_REQUIRED"); const base = { ...segment, text: input.replacementText, sourceRefs: [...input.sourceRefs], updatedAt: new Date().toISOString() }; const next = { ...base, fingerprint: hash({ ...base, fingerprint: undefined }) }; await write(file(root, semanticId), next); return next; }
