import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { resolveInside } from "./pathSafety.js";
export type ProseMaturityTx = "planned" | "candidate_generated" | "validated" | "author_accepted" | "settled" | "publication_ready";
export interface ProseCanon { schemaVersion: "prose-canon.v1"; projectSlug: string; segmentId: string; text: string; baselineFingerprint: string; maturity: ProseMaturityTx; updatedAt: string; fingerprint: string; }
export interface ProseAdoptionTransaction { schemaVersion: "prose-adoption-transaction.v1"; transactionId: string; segmentId: string; expectedBaselineFingerprint: string; maturity: ProseMaturityTx; authority: "author" | "autonomous"; lockCheckPassed: boolean; validationFingerprint: string; derivedCandidates: string[]; rollbackVersion: string; committedAt: string; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function canonFile(root: string, id: string) { return resolveInside(root, `sessions/prose-canon/${id}.json`); }
function txFile(root: string, id: string) { return resolveInside(root, `sessions/prose-adoption-transactions/${id}.json`); }
async function read<T>(file: string): Promise<T | null> { try { return JSON.parse(await fs.readFile(file, "utf8")) as T; } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return null; throw e; } }
async function write(file: string, value: unknown) { await fs.mkdir(path.dirname(file), { recursive: true }); const temp = `${file}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(temp, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await fs.rename(temp, file); }
export async function readProseCanon(root: string, segmentId: string) { return read<ProseCanon>(canonFile(root, segmentId)); }
export async function createProseCanon(input: { root: string; projectSlug: string; segmentId: string; baselineFingerprint: string; currentText: string; maturity: ProseMaturityTx; authorLockIds: readonly string[]; sourceRefs: readonly string[] }, tx: { expectedBaselineFingerprint: string; replacementText: string; authority: "author" | "autonomous"; lockCheckPassed: boolean; validationFingerprint: string; derivedCandidates: readonly string[] }): Promise<{ status: "committed"; canon: ProseCanon; transaction: ProseAdoptionTransaction }> { if (!tx.replacementText.trim() || !tx.validationFingerprint.trim() || !input.sourceRefs.length) throw new Error("PROSE_TRANSACTION_VALIDATION_REQUIRED"); if (tx.expectedBaselineFingerprint !== input.baselineFingerprint) throw new Error("PROSE_BASELINE_STALE"); if (!tx.lockCheckPassed || !input.authorLockIds.length) throw new Error("PROSE_LOCK_CHECK_FAILED"); if (["author_accepted", "settled", "publication_ready"].includes(input.maturity) && tx.authority !== "author") throw new Error("PROSE_AUTHOR_AUTHORITY_REQUIRED"); const existing = await readProseCanon(input.root, input.segmentId); const rollbackVersion = existing?.text || input.currentText; const transactionId = `prose-tx-${input.segmentId}-${hash({ baseline: input.baselineFingerprint, replacement: tx.replacementText }).slice(0, 12)}`; const canonBase = { schemaVersion: "prose-canon.v1" as const, projectSlug: input.projectSlug, segmentId: input.segmentId, text: tx.replacementText, baselineFingerprint: tx.expectedBaselineFingerprint, maturity: input.maturity, updatedAt: new Date().toISOString() }; const canon = { ...canonBase, fingerprint: hash(canonBase) }; const transactionBase = { schemaVersion: "prose-adoption-transaction.v1" as const, transactionId, segmentId: input.segmentId, expectedBaselineFingerprint: tx.expectedBaselineFingerprint, maturity: input.maturity, authority: tx.authority, lockCheckPassed: tx.lockCheckPassed, validationFingerprint: tx.validationFingerprint, derivedCandidates: [...tx.derivedCandidates], rollbackVersion, committedAt: new Date().toISOString() }; const transaction = { ...transactionBase, fingerprint: hash(transactionBase) }; await write(canonFile(input.root, input.segmentId), canon); try { await write(txFile(input.root, transactionId), transaction); } catch (error) { await fs.rm(canonFile(input.root, input.segmentId), { force: true }); throw error; } return { status: "committed", canon, transaction }; }
