import crypto from "node:crypto";
export type ProseMaturityStatus = "planned" | "candidate_generated" | "validated" | "author_accepted" | "settled" | "publication_ready";
export type ProseWriteAuthority = "autonomous" | "author";
export interface ProseMaturity { schemaVersion: "prose-maturity.v1"; projectSlug: string; chapterId: string; status: ProseMaturityStatus; writeAuthority: ProseWriteAuthority; history: Array<{ event: string; from: ProseMaturityStatus; to: ProseMaturityStatus; sourceRefs: string[]; at: string }>; sourceRefs: string[]; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function authority(status: ProseMaturityStatus): ProseWriteAuthority { return ["author_accepted", "settled", "publication_ready"].includes(status) ? "author" : "autonomous"; }
function assertIntegrity(state: ProseMaturity): void { const { fingerprint: _fingerprint, ...base } = state; if (state.schemaVersion !== "prose-maturity.v1" || !state.projectSlug.trim() || !state.chapterId.trim() || !/^[a-f0-9]{64}$/i.test(state.fingerprint) || hash(base) !== state.fingerprint) throw new Error("MATURITY_INTEGRITY_FAILED"); }
export function createProseMaturity(input: { projectSlug: string; chapterId: string; sourceRefs: readonly string[] }): ProseMaturity { if (!input.projectSlug.trim() || !input.chapterId.trim() || !input.sourceRefs.length || input.sourceRefs.some((ref) => !ref.trim())) throw new Error("MATURITY_SOURCE_REQUIRED"); const base = { schemaVersion: "prose-maturity.v1" as const, projectSlug: input.projectSlug, chapterId: input.chapterId, status: "planned" as const, writeAuthority: "autonomous" as const, history: [], sourceRefs: [...input.sourceRefs] }; return { ...base, fingerprint: hash(base) }; }
export function advanceProseMaturity(state: ProseMaturity, input: { event: string; target: ProseMaturityStatus; sourceRefs: readonly string[]; gates: { validation?: boolean; obligationsSettled?: boolean; factsSettled?: boolean; unresolvedBlocks?: boolean; canonFingerprint?: string } }): ProseMaturity { assertIntegrity(state); if (!input.event.trim()) throw new Error("MATURITY_EVENT_REQUIRED"); if (!input.sourceRefs.length || input.sourceRefs.some((ref) => !ref.trim())) throw new Error("MATURITY_EVENT_SOURCE_REQUIRED"); const { fingerprint: _oldFingerprint, ...stateBase } = state; const allowed: Record<ProseMaturityStatus, ProseMaturityStatus[]> = { planned: ["candidate_generated"], candidate_generated: ["validated", "planned"], validated: ["author_accepted", "planned"], author_accepted: ["settled", "planned"], settled: ["publication_ready", "planned"], publication_ready: ["planned"] }; if (input.event === "reopen" && input.target === "planned") { const history = [...state.history, { event: input.event, from: state.status, to: "planned" as const, sourceRefs: [...input.sourceRefs], at: new Date().toISOString() }]; const base = { ...stateBase, status: "planned" as const, writeAuthority: "autonomous" as const, history }; return { ...base, fingerprint: hash(base) }; } if (!allowed[state.status].includes(input.target)) throw new Error("MATURITY_TRANSITION_INVALID"); if (input.target === "validated" && !input.gates.validation) throw new Error("MATURITY_GATE_FAILED"); if (input.target === "settled" && (!input.gates.validation || !input.gates.obligationsSettled || !input.gates.factsSettled || input.gates.unresolvedBlocks)) throw new Error("MATURITY_GATE_FAILED"); if (input.target === "settled" && !/^[a-f0-9]{64}$/i.test(input.gates.canonFingerprint || "")) throw new Error("MATURITY_CANON_FINGERPRINT_INVALID"); const nextAuthority = authority(input.target); const history = [...state.history, { event: input.event, from: state.status, to: input.target, sourceRefs: [...input.sourceRefs], at: new Date().toISOString() }]; const base = { ...stateBase, status: input.target, writeAuthority: nextAuthority, history }; return { ...base, fingerprint: hash(base) }; }
