import { describe, expect, it } from "vitest";
import { createProseMaturity, advanceProseMaturity } from "./proseMaturity.js";

describe("prose maturity state", () => {
  it("advances through sourced events with required gates", () => { let state = createProseMaturity({ projectSlug: "demo", chapterId: "ch-1", sourceRefs: ["chapter://ch-1"] }); expect(state.status).toBe("planned"); state = advanceProseMaturity(state, { event: "candidate-generated", target: "candidate_generated", sourceRefs: ["event://1"], gates: {} }); state = advanceProseMaturity(state, { event: "validated", target: "validated", sourceRefs: ["validation://1"], gates: { validation: true } }); state = advanceProseMaturity(state, { event: "author-accepted", target: "author_accepted", sourceRefs: ["decision://1"], gates: { validation: true } }); state = advanceProseMaturity(state, { event: "settled", target: "settled", sourceRefs: ["settlement://1"], gates: { validation: true, obligationsSettled: true, factsSettled: true, unresolvedBlocks: false, canonFingerprint: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef" } }); expect(state.status).toBe("settled"); });
  it("blocks invalid transition or settlement gates", () => { const state = createProseMaturity({ projectSlug: "demo", chapterId: "ch-1", sourceRefs: ["chapter://ch-1"] }); expect(() => advanceProseMaturity(state, { event: "settled", target: "settled", sourceRefs: ["x"], gates: {} })).toThrow("MATURITY_TRANSITION_INVALID"); const candidate = advanceProseMaturity(state, { event: "candidate", target: "candidate_generated", sourceRefs: ["x"], gates: {} }); const validated = advanceProseMaturity(candidate, { event: "validated", target: "validated", sourceRefs: ["x"], gates: { validation: true } }); const accepted = advanceProseMaturity(validated, { event: "accepted", target: "author_accepted", sourceRefs: ["x"], gates: { validation: true } }); expect(() => advanceProseMaturity(accepted, { event: "settled", target: "settled", sourceRefs: ["x"], gates: { validation: true } })).toThrow("MATURITY_GATE_FAILED"); });
  it("supports explicit reopen with evidence and preserves history", () => { const state = createProseMaturity({ projectSlug: "demo", chapterId: "ch-1", sourceRefs: ["chapter://ch-1"] }); const reopened = advanceProseMaturity(state, { event: "reopen", target: "planned", sourceRefs: ["decision://reopen"], gates: {} }); expect(reopened.status).toBe("planned"); expect(reopened.history).toHaveLength(1); });
  it("rejects tampered state, blank event evidence, and invalid canon fingerprints", () => {
    const state = createProseMaturity({ projectSlug: "demo", chapterId: "ch-1", sourceRefs: ["chapter://ch-1"] });
    expect(state.writeAuthority).toBe("autonomous");
    expect(() => advanceProseMaturity({ ...state, status: "settled" }, { event: "x", target: "candidate_generated", sourceRefs: ["x"], gates: {} })).toThrow("MATURITY_INTEGRITY_FAILED");
    expect(() => advanceProseMaturity(state, { event: " ", target: "candidate_generated", sourceRefs: ["x"], gates: {} })).toThrow("MATURITY_EVENT_REQUIRED");
    const candidate = advanceProseMaturity(state, { event: "candidate", target: "candidate_generated", sourceRefs: ["x"], gates: {} });
    const validated = advanceProseMaturity(candidate, { event: "validated", target: "validated", sourceRefs: ["x"], gates: { validation: true } });
    const accepted = advanceProseMaturity(validated, { event: "accepted", target: "author_accepted", sourceRefs: ["x"], gates: { validation: true } });
    expect(accepted.writeAuthority).toBe("author");
    expect(() => advanceProseMaturity(accepted, { event: "settled", target: "settled", sourceRefs: ["x"], gates: { validation: true, obligationsSettled: true, factsSettled: true, unresolvedBlocks: false, canonFingerprint: "not-a-sha256" } })).toThrow("MATURITY_CANON_FINGERPRINT_INVALID");
  });
});
