import crypto from "node:crypto";

export type DossierDomain = "hard-guards" | "chapter-function" | "scene-execution" | "character-agency" | "pov-information" | "obligation-beats" | "seams" | "author-goal" | "language-craft";
export type BlockingLevel = "none" | "soft" | "hard";
export interface DossierDomainResult { domain: DossierDomain; applicable: boolean; evidence: string[]; counterEvidence: string[]; confidence: number; blockingLevel: BlockingLevel; status: "evaluated" | "unevaluated"; }
export interface ProseDossierInput { projectSlug: string; candidateId: string; baselineFingerprint: string; domains: DossierDomainResult[]; overallScore: number; sourceRefs: string[]; }
export interface ProseValidationDossier { schemaVersion: "prose-validation-dossier.v1"; projectSlug: string; candidateId: string; baselineFingerprint: string; domains: DossierDomainResult[]; overallScore: number; status: "passed" | "blocked"; issues: string[]; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
export function buildProseValidationDossier(input: ProseDossierInput): ProseValidationDossier { const issues: string[] = []; const expected: DossierDomain[] = ["hard-guards", "chapter-function", "scene-execution", "character-agency", "pov-information", "obligation-beats", "seams", "author-goal", "language-craft"]; if (!input.projectSlug.trim() || !input.candidateId.trim() || !input.baselineFingerprint.trim()) issues.push("DOSSIER_FIELDS_REQUIRED"); if (!input.sourceRefs.length || input.sourceRefs.some((ref) => !ref.trim())) issues.push("DOSSIER_SOURCE_REQUIRED"); if (!Number.isFinite(input.overallScore) || input.overallScore < 0 || input.overallScore > 1) issues.push("DOSSIER_SCORE_INVALID"); const domainIds = input.domains.map((domain) => domain.domain); if (new Set(domainIds).size !== domainIds.length) issues.push("DOMAIN_DUPLICATE"); if (input.domains.some((domain) => domain.applicable && (!Number.isFinite(domain.confidence) || domain.confidence < 0 || domain.confidence > 1 || !domain.evidence.length || domain.evidence.some((ref) => !ref.trim())))) issues.push("DOMAIN_EVIDENCE_REQUIRED"); const byDomain = new Map(input.domains.map((domain) => [domain.domain, domain])); for (const domain of expected) { const result = byDomain.get(domain); if (!result || (result.applicable && result.status !== "evaluated")) issues.push("DOMAIN_UNEVALUATED"); if (result?.blockingLevel === "hard" || (domain === "hard-guards" && result?.counterEvidence.length)) issues.push("HARD_GUARD_FAILED"); } const base = { schemaVersion: "prose-validation-dossier.v1" as const, projectSlug: input.projectSlug, candidateId: input.candidateId, baselineFingerprint: input.baselineFingerprint, domains: input.domains, overallScore: input.overallScore, status: issues.length ? "blocked" as const : "passed" as const, issues: [...new Set(issues)] }; return { ...base, fingerprint: hash(base) }; }
