import crypto from "node:crypto";

export interface ReaderExperienceContract { schemaVersion: "reader-experience-contract.v1"; contractId: string; target: string; direction: Record<string, string>; evidenceConditions: string[]; intentionallyQuiet: string[]; fingerprint: string; }
export interface ReaderExperienceHypothesis { schemaVersion: "reader-experience-hypothesis.v1"; hypothesisId: string; targetReader: string; claim: string; evidenceRefs: string[]; counterExamples: string[]; confidence: number; calibrationStatus: "uncalibrated" | "calibrated"; isCanonReaction: false; fingerprint: string; }
export interface ColdReadSnapshot { schemaVersion: "cold-read-snapshot.v1"; snapshotId: string; publicationVersion: string; progress: string; visibleText: string; visibleTitles: string[]; leakedFields: string[]; valid: boolean; fingerprint: string; }
export interface ReaderKnowledgeState { schemaVersion: "reader-knowledge-state.v1"; snapshotId: string; questions: string[]; beliefs: string[]; doubts: string[]; predictions: string[]; evidenceRefs: string[]; fingerprint: string; }
export interface ReaderCognitiveLoad { schemaVersion: "reader-cognitive-load.v1"; budget: number; used: number; status: "within-budget" | "over-budget"; fingerprint: string; }
export interface ReaderPayoff { schemaVersion: "reader-payoff.v1"; payoffId: string; status: "changed" | "unchanged"; changedKeys: string[]; evidenceRef: string; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
export function createReaderExperienceContract(input: Omit<ReaderExperienceContract, "schemaVersion" | "fingerprint">): ReaderExperienceContract { if (!input.contractId.trim() || !input.target.trim() || !input.evidenceConditions.length) throw new Error("READER_CONTRACT_FIELDS_REQUIRED"); const base = { schemaVersion: "reader-experience-contract.v1" as const, ...input, direction: { ...input.direction }, evidenceConditions: [...input.evidenceConditions], intentionallyQuiet: [...input.intentionallyQuiet] }; return { ...base, fingerprint: hash(base) }; }
export function createReaderExperienceHypothesis(input: Omit<ReaderExperienceHypothesis, "schemaVersion" | "isCanonReaction" | "fingerprint">): ReaderExperienceHypothesis { if (!input.hypothesisId.trim() || !input.targetReader.trim() || !input.claim.trim() || !input.evidenceRefs.length || input.confidence < 0 || input.confidence > 1) throw new Error("READER_HYPOTHESIS_FIELDS_REQUIRED"); const base = { schemaVersion: "reader-experience-hypothesis.v1" as const, ...input, evidenceRefs: [...input.evidenceRefs], counterExamples: [...input.counterExamples], isCanonReaction: false as const }; return { ...base, fingerprint: hash(base) }; }
export function createColdReadSnapshot(input: Omit<ColdReadSnapshot, "schemaVersion" | "valid" | "fingerprint">): ColdReadSnapshot { if (!input.snapshotId.trim() || !input.publicationVersion.trim() || !input.progress.trim() || !input.visibleText.trim()) throw new Error("COLD_READ_FIELDS_REQUIRED"); if (input.leakedFields.length) throw new Error("COLD_READ_LEAK"); const base = { schemaVersion: "cold-read-snapshot.v1" as const, ...input, visibleTitles: [...input.visibleTitles], leakedFields: [], valid: true as const }; return { ...base, fingerprint: hash(base) }; }
export function createReaderKnowledgeState(input: Omit<ReaderKnowledgeState, "schemaVersion" | "fingerprint">): ReaderKnowledgeState { if (!input.snapshotId.trim() || !input.evidenceRefs.length) throw new Error("READER_STATE_FIELDS_REQUIRED"); const base = { schemaVersion: "reader-knowledge-state.v1" as const, ...input, questions: [...input.questions], beliefs: [...input.beliefs], doubts: [...input.doubts], predictions: [...input.predictions], evidenceRefs: [...input.evidenceRefs] }; return { ...base, fingerprint: hash(base) }; }
export function assessReaderCognitiveLoad(input: { budget: number; newCharacters: number; newTerms: number; newRules: number; timeJumps: number; povSwitches: number; recalledClues: number }): ReaderCognitiveLoad { const used = input.newCharacters + input.newTerms + input.newRules + input.timeJumps + input.povSwitches + input.recalledClues; const base = { schemaVersion: "reader-cognitive-load.v1" as const, budget: input.budget, used, status: used > input.budget ? "over-budget" as const : "within-budget" as const }; return { ...base, fingerprint: hash(base) }; }
export function evaluateReaderPayoff(input: { payoffId: string; before: Record<string, unknown>; after: Record<string, unknown>; evidenceRef: string }): ReaderPayoff { if (!input.payoffId.trim() || !input.evidenceRef.trim()) throw new Error("READER_PAYOFF_FIELDS_REQUIRED"); const changedKeys = Object.keys(input.after).filter((key) => JSON.stringify(input.before[key]) !== JSON.stringify(input.after[key])); const base = { schemaVersion: "reader-payoff.v1" as const, payoffId: input.payoffId, status: changedKeys.length ? "changed" as const : "unchanged" as const, changedKeys, evidenceRef: input.evidenceRef }; return { ...base, fingerprint: hash(base) }; }
