import crypto from "node:crypto";

export interface SceneNecessity { schemaVersion: "scene-necessity.v1"; sceneId: string; status: "necessary" | "compressible" | "redundant"; lostFunctions: Record<string, string[]>; alternatives: string[]; fingerprint: string; }
export interface SurpriseFairness { schemaVersion: "surprise-fairness.v1"; revealId: string; status: "obvious" | "fair" | "ungrounded"; priorEvidence: string[]; viableAlternativeCount: number; answerSalience: number; causalConsequence: string; newRuleIntroduced: boolean; fingerprint: string; }
export interface ExperienceTimeline { schemaVersion: "experience-timeline.v1"; projectId: string; windows: Array<{ scale: string; label: string; state: string }>; fingerprint: string; }
export interface ReaderDivergence { schemaVersion: "reader-divergence.v1"; claims: Array<{ audience: string; result: string; evidence: string[] }>; fingerprint: string; }
export interface ReaderReviewer { schemaVersion: "reader-reviewer.v1"; reviewerId: string; status: "calibrated" | "experimental"; humanSamples: number; blind: boolean; agreementRate: number; fingerprint: string; }
export interface ReaderExperienceDossier { schemaVersion: "reader-experience-dossier.v1"; dossierId: string; reviewedRange: string; progress: string; targetReaders: string[]; evidenceCoverage: string[]; disagreements: string[]; failures: string[]; unknowns: string[]; staleItems: string[]; claimBoundary: string; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
export function assessSceneNecessity(input: { sceneId: string; functions: Record<string, string[]>; alternatives: readonly string[] }): SceneNecessity { if (!input.sceneId.trim()) throw new Error("SCENE_NECESSITY_FIELDS_REQUIRED"); const lostFunctions = Object.fromEntries(Object.entries(input.functions).filter(([, values]) => values.length)); const status = Object.keys(lostFunctions).length ? "necessary" as const : input.alternatives.length ? "compressible" as const : "redundant" as const; const base = { schemaVersion: "scene-necessity.v1" as const, sceneId: input.sceneId, status, lostFunctions, alternatives: [...input.alternatives] }; return { ...base, fingerprint: hash(base) }; }
export function evaluateSurpriseFairness(input: Omit<SurpriseFairness, "schemaVersion" | "status" | "fingerprint">): SurpriseFairness { const status = input.newRuleIntroduced ? "ungrounded" as const : input.priorEvidence.length === 0 ? "ungrounded" as const : input.answerSalience > 0.85 ? "obvious" as const : "fair" as const; const base = { schemaVersion: "surprise-fairness.v1" as const, ...input, priorEvidence: [...input.priorEvidence], status }; return { ...base, fingerprint: hash(base) }; }
export function createExperienceTimeline(input: { projectId: string; windows: ReadonlyArray<{ scale: string; label: string; state: string }> }): ExperienceTimeline { if (!input.projectId.trim() || !input.windows.length) throw new Error("EXPERIENCE_TIMELINE_REQUIRED"); const base = { schemaVersion: "experience-timeline.v1" as const, projectId: input.projectId, windows: input.windows.map((window) => ({ ...window })) }; return { ...base, fingerprint: hash(base) }; }
export function preserveReaderDivergence(input: { claims: ReadonlyArray<{ audience: string; result: string; evidence: readonly string[] }> }): ReaderDivergence { if (!input.claims.length) throw new Error("READER_DIVERGENCE_REQUIRED"); const base = { schemaVersion: "reader-divergence.v1" as const, claims: input.claims.map((claim) => ({ ...claim, evidence: [...claim.evidence] })) }; return { ...base, fingerprint: hash(base) }; }
export function calibrateReaderReviewer(input: Omit<ReaderReviewer, "schemaVersion" | "status" | "fingerprint">): ReaderReviewer { const status = input.humanSamples >= 3 && input.blind && input.agreementRate >= 0.7 ? "calibrated" as const : "experimental" as const; const base = { schemaVersion: "reader-reviewer.v1" as const, ...input, status }; return { ...base, fingerprint: hash(base) }; }
export function createReaderExperienceDossier(input: Omit<ReaderExperienceDossier, "schemaVersion" | "claimBoundary" | "fingerprint">): ReaderExperienceDossier { if (!input.dossierId.trim() || !input.reviewedRange.trim() || !input.progress.trim()) throw new Error("READER_DOSSIER_FIELDS_REQUIRED"); const base = { schemaVersion: "reader-experience-dossier.v1" as const, ...input, targetReaders: [...input.targetReaders], evidenceCoverage: [...input.evidenceCoverage], disagreements: [...input.disagreements], failures: [...input.failures], unknowns: [...input.unknowns], staleItems: [...input.staleItems], claimBoundary: "supported only within reviewed range" }; return { ...base, fingerprint: hash(base) }; }
