export function assessMisunderstandingRepair(input: { factCorrected: boolean; harmAcknowledged: boolean; restitution: boolean; newChoice: boolean }): { factUpdated: boolean; relationshipRepaired: boolean; remainingDebt: string[] } { const remainingDebt = [input.harmAcknowledged ? "" : "harm", input.restitution ? "" : "restitution", input.newChoice ? "" : "new-choice"].filter(Boolean); return { factUpdated: input.factCorrected, relationshipRepaired: input.factCorrected && remainingDebt.length === 0, remainingDebt }; }
export function assessIndependentOpponent(input: { absentActions: number; goal: boolean; constraints: boolean; changedOutcome: boolean }): { independent: boolean; toolRisk: boolean } { const independent = input.absentActions > 0 && input.goal && input.constraints && input.changedOutcome; return { independent, toolRisk: !independent }; }
export function validateOffscreenAction(input: { goal: string; actions: readonly string[]; costs: readonly string[]; anchors: readonly string[] }): { valid: boolean; missing: string[] } { const missing = [input.goal ? "" : "goal", input.actions.length ? "" : "action", input.costs.length ? "" : "cost", input.anchors.length ? "" : "anchor"].filter(Boolean); return { valid: missing.length === 0, missing }; }
export function assessCharacterFunction(input: { appearances: number; independentChoices: number; consequences: number; repeatedInformation: number }): { healthy: boolean; redundant: boolean } { return { healthy: input.independentChoices > 0 && input.consequences > 0, redundant: input.appearances > 0 && input.repeatedInformation >= input.appearances }; }
export function assessEnsembleAttention(input: { members: readonly { goal: boolean; choice: boolean; consequence: boolean }[] }): { sufficient: boolean; missingMembers: number[] } { const missingMembers = input.members.map((m, i) => m.goal && m.choice && m.consequence ? -1 : i).filter((i) => i >= 0); return { sufficient: missingMembers.length === 0, missingMembers }; }
export function validateRelationalVoice(input: { relationStage: string; changedMarkers: readonly string[]; milestoneEvidence: readonly string[]; personalityFlip: boolean }): { valid: boolean; variant: boolean } { return { valid: !input.personalityFlip && (input.changedMarkers.length === 0 || input.milestoneEvidence.length > 0), variant: input.changedMarkers.length > 0 }; }
export function preserveRelapseProgress(input: { relapse: boolean; residualSkill: boolean; newCost: boolean }): { status: "relapse" | "progress"; reset: false } { return { status: input.relapse ? "relapse" : input.residualSkill && input.newCost ? "progress" : "relapse", reset: false }; }
export function buildIdentityBreakImpact(input: { domains: readonly string[]; oldCosts: readonly string[]; amnesia: boolean }): { domains: string[]; costsPreserved: string[]; retroactiveKnowledgeDeletion: false } { return { domains: [...input.domains], costsPreserved: [...input.oldCosts], retroactiveKnowledgeDeletion: false }; }
export function scopeCharacterChange(input: { changedNodes: readonly string[]; affectedNodes: readonly string[]; protectedNodes: readonly string[] }): { recompute: string[]; protectedNodes: string[] } { const recompute = [...new Set([...input.changedNodes, ...input.affectedNodes])].filter((node) => !input.protectedNodes.includes(node)); return { recompute, protectedNodes: [...input.protectedNodes] }; }
export function issueArcCertificate(input: { milestones: readonly { id: string; evidence: readonly string[]; openAuthorized: boolean }[]; complete: boolean }): { status: "audited_complete" | "blocked"; missing: string[] } { const missing = input.milestones.filter((m) => !m.evidence.length && !m.openAuthorized).map((m) => m.id); return { status: input.complete && missing.length === 0 ? "audited_complete" : "blocked", missing }; }
