import crypto from "node:crypto";

export interface ResearchObligation { schemaVersion: "research-obligation.v1"; obligationId: string; assertion: string; domain: string; truthBoundary: "strictly-real" | "reasonable-approximation" | "fictionalized"; risk: "low" | "medium" | "high"; affectedAssets: string[]; requiresSource: boolean; fingerprint: string; }
export interface ResearchSourceSnapshot { schemaVersion: "research-source-snapshot.v1"; sourceId: string; sourceType: string; author: string; title: string; publishedAt: string; retrievedAt: string; region: string; locator: string; contentHash: string; acquisition: string; rights: string; reliabilitySignals: string[]; expiry: string; sanitizedContent: string; fingerprint: string; }
export interface ResearchClaim { schemaVersion: "research-claim.v1"; claimId: string; sourceSnapshotId: string; sourceText: string; paraphrase: string; status: "supported" | "contested" | "unknown"; anchor: string; region: string; asOf: string; conditions: string[]; counterEvidence: string[]; independentSourceIds: string[]; fingerprint: string; }
export interface ResearchConsumptionReceipt { schemaVersion: "research-consumption-receipt.v1"; receiptId: string; claimId: string; sourceSnapshotId: string; assetRef: string; usage: string; adaptation: string; risk: string; span: { start: number; end: number }; status: "pending"; fingerprint: string; }
export interface ResearchSettlement { schemaVersion: "research-settlement.v1"; receiptId: string; status: "current" | "stale" | "waived"; decision: string; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
export function identifyResearchObligation(input: Omit<ResearchObligation, "schemaVersion" | "requiresSource" | "fingerprint">): ResearchObligation { if (!input.obligationId.trim() || !input.assertion.trim() || !input.domain.trim() || !input.affectedAssets.length) throw new Error("RESEARCH_OBLIGATION_FIELDS_REQUIRED"); const base = { schemaVersion: "research-obligation.v1" as const, ...input, affectedAssets: [...input.affectedAssets], requiresSource: input.truthBoundary === "strictly-real" || input.risk === "high" }; return { ...base, fingerprint: hash(base) }; }
export function createResearchSourceSnapshot(input: Omit<ResearchSourceSnapshot, "schemaVersion" | "sanitizedContent" | "fingerprint"> & { rawContent: string }): ResearchSourceSnapshot { if (!input.sourceId.trim() || !input.author.trim() || !input.title.trim() || !input.locator.trim() || !input.contentHash.trim() || !input.rights.trim()) throw new Error("RESEARCH_SOURCE_FIELDS_REQUIRED"); const sanitizedContent = input.rawContent.replace(/<script[\s\S]*?<\/script>/gi, "").replace(/ignore previous instructions/gi, "").replace(/\b(system|developer|user)\s*:/gi, ""); const { rawContent, ...rest } = input; const base = { schemaVersion: "research-source-snapshot.v1" as const, ...rest, reliabilitySignals: [...input.reliabilitySignals], sanitizedContent }; return { ...base, fingerprint: hash(base) }; }
export function createResearchClaim(input: Omit<ResearchClaim, "schemaVersion" | "fingerprint">): ResearchClaim { if (!input.claimId.trim() || !input.sourceSnapshotId.trim() || !input.sourceText.trim() || !input.paraphrase.trim() || !input.anchor.trim() || !input.region.trim() || !input.asOf.trim() || !input.independentSourceIds.length) throw new Error("RESEARCH_CLAIM_FIELDS_REQUIRED"); const base = { schemaVersion: "research-claim.v1" as const, ...input, conditions: [...input.conditions], counterEvidence: [...input.counterEvidence], independentSourceIds: [...input.independentSourceIds] }; return { ...base, fingerprint: hash(base) }; }
export function createResearchConsumptionReceipt(input: Omit<ResearchConsumptionReceipt, "schemaVersion" | "status" | "fingerprint">): ResearchConsumptionReceipt { if (!input.receiptId.trim() || !input.claimId.trim() || !input.sourceSnapshotId.trim() || !input.assetRef.trim() || !input.usage.trim() || input.span.end <= input.span.start) throw new Error("RESEARCH_RECEIPT_FIELDS_REQUIRED"); const base = { schemaVersion: "research-consumption-receipt.v1" as const, ...input, status: "pending" as const }; return { ...base, fingerprint: hash(base) }; }
export function settleResearchClaim(input: { receipt: ResearchConsumptionReceipt; currentClaimFingerprint: string; consumedClaimFingerprint: string; decision: "current" | "rewrite" | "waive" }): ResearchSettlement { const status = input.decision === "waive" ? "waived" as const : input.currentClaimFingerprint !== input.consumedClaimFingerprint ? "stale" as const : "current" as const; const base = { schemaVersion: "research-settlement.v1" as const, receiptId: input.receipt.receiptId, status, decision: input.decision }; return { ...base, fingerprint: hash(base) }; }
