import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { resolveInside } from "./pathSafety.js";

export interface ReviewIsolationSession { schemaVersion: "review-isolation-session.v1"; sessionId: string; projectSlug: string; candidateId: string; baselineFingerprint: string; generatedSelfClaims: string[]; reviews: Array<{ side: "blue" | "red"; verdict: string; findings: string[]; evidenceRefs: string[]; baselineFingerprint: string }>; status: "awaiting-reviews" | "ready-to-synthesize" | "synthesized"; synthesis: { decision: string; evidenceRefs: string[] } | null; sourceRefs: string[]; createdAt: string; updatedAt: string; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function file(root: string, id: string) { return resolveInside(root, `sessions/review-isolation/${id}.json`); }
async function read<T>(target: string): Promise<T | null> { try { return JSON.parse(await fs.readFile(target, "utf8")) as T; } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return null; throw e; } }
async function write(target: string, value: unknown) { await fs.mkdir(path.dirname(target), { recursive: true }); const tmp = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await fs.rename(tmp, target); }
export function assertReviewIsolationIntegrity(session: ReviewIsolationSession, expectedSessionId?: string): ReviewIsolationSession { const { fingerprint: _fingerprint, ...base } = session; const sides = new Set<string>(); const validReviews = Array.isArray(session.reviews) && session.reviews.every((review) => { const valid = ["blue", "red"].includes(review.side) && !sides.has(review.side) && typeof review.verdict === "string" && review.verdict.trim() && Array.isArray(review.findings) && review.findings.every((finding) => typeof finding === "string" && finding.trim()) && Array.isArray(review.evidenceRefs) && review.evidenceRefs.length > 0 && review.evidenceRefs.every((ref) => typeof ref === "string" && ref.trim()) && review.baselineFingerprint === session.baselineFingerprint; sides.add(review.side); return valid; }); const hasBlue = sides.has("blue"); const hasRed = sides.has("red"); const validSynthesis = session.synthesis === null || (typeof session.synthesis.decision === "string" && session.synthesis.decision.trim() && Array.isArray(session.synthesis.evidenceRefs) && session.synthesis.evidenceRefs.length > 0 && session.synthesis.evidenceRefs.every((ref) => typeof ref === "string" && ref.trim())); const expectedStatus = session.synthesis ? "synthesized" : hasBlue && hasRed ? "ready-to-synthesize" : "awaiting-reviews"; const valid = session.schemaVersion === "review-isolation-session.v1" && (!expectedSessionId || session.sessionId === expectedSessionId) && Boolean(session.sessionId?.trim() && session.projectSlug?.trim() && session.candidateId?.trim() && session.baselineFingerprint?.trim()) && Array.isArray(session.generatedSelfClaims) && session.generatedSelfClaims.every((claim) => typeof claim === "string" && claim.trim()) && validReviews && validSynthesis && session.status === expectedStatus && Array.isArray(session.sourceRefs) && session.sourceRefs.length > 0 && session.sourceRefs.every((ref) => typeof ref === "string" && ref.trim()) && typeof session.createdAt === "string" && session.createdAt.trim() && typeof session.updatedAt === "string" && session.updatedAt.trim() && /^[a-f0-9]{64}$/i.test(session.fingerprint) && hash(base) === session.fingerprint; if (!valid) throw new Error("REVIEW_ISOLATION_INTEGRITY_FAILED"); return session; }
export async function readReviewIsolationSession(root: string, sessionId: string) { const session = await read<ReviewIsolationSession>(file(root, sessionId)); return session ? assertReviewIsolationIntegrity(session, sessionId) : null; }
export async function createReviewIsolationSession(input: { root: string; projectSlug: string; candidateId: string; baselineFingerprint: string; generatedSelfClaims: readonly string[]; sourceRefs: readonly string[] }): Promise<ReviewIsolationSession> { if (!input.baselineFingerprint.trim()) throw new Error("REVIEW_BASELINE_REQUIRED"); if (!input.projectSlug.trim() || !input.candidateId.trim()) throw new Error("REVIEW_FIELDS_REQUIRED"); if (!input.sourceRefs.length) throw new Error("REVIEW_SOURCE_REQUIRED"); const sessionId = `review-isolation-${input.candidateId}`; const existing = await readReviewIsolationSession(input.root, sessionId); if (existing) return existing; const base = { schemaVersion: "review-isolation-session.v1" as const, sessionId, projectSlug: input.projectSlug, candidateId: input.candidateId, baselineFingerprint: input.baselineFingerprint, generatedSelfClaims: [...input.generatedSelfClaims], reviews: [], status: "awaiting-reviews" as const, synthesis: null, sourceRefs: [...input.sourceRefs], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; const session = { ...base, fingerprint: hash(base) }; await write(file(input.root, sessionId), session); return session; }
export async function submitReview(root: string, sessionId: string, input: { side: "blue" | "red"; verdict: string; findings: readonly string[]; evidenceRefs: readonly string[] }): Promise<ReviewIsolationSession> { const session = await readReviewIsolationSession(root, sessionId); if (!session) throw new Error("REVIEW_SESSION_NOT_FOUND"); if (!input.verdict.trim() || !input.evidenceRefs.length) throw new Error("REVIEW_EVIDENCE_REQUIRED"); const review = { side: input.side, verdict: input.verdict, findings: [...input.findings], evidenceRefs: [...input.evidenceRefs], baselineFingerprint: session.baselineFingerprint }; const reviews = [...session.reviews.filter((item) => item.side !== input.side), review]; const base = { ...session, reviews, status: reviews.some((item) => item.side === "blue") && reviews.some((item) => item.side === "red") ? "ready-to-synthesize" as const : "awaiting-reviews" as const, updatedAt: new Date().toISOString() }; const next = { ...base, fingerprint: hash({ ...base, fingerprint: undefined }) }; await write(file(root, sessionId), next); return next; }
export async function synthesizeReview(root: string, sessionId: string, input: { decision: string; evidenceRefs: readonly string[] }): Promise<ReviewIsolationSession> { const session = await readReviewIsolationSession(root, sessionId); if (!session) throw new Error("REVIEW_SESSION_NOT_FOUND"); if (!session.reviews.some((review) => review.side === "blue") || !session.reviews.some((review) => review.side === "red")) throw new Error("INDEPENDENT_REVIEWS_REQUIRED"); if (!input.decision.trim() || !input.evidenceRefs.length) throw new Error("SYNTHESIS_EVIDENCE_REQUIRED"); const base = { ...session, status: "synthesized" as const, synthesis: { decision: input.decision, evidenceRefs: [...input.evidenceRefs] }, updatedAt: new Date().toISOString() }; const next = { ...base, fingerprint: hash({ ...base, fingerprint: undefined }) }; await write(file(root, sessionId), next); return next; }
