import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { resolveInside } from "./pathSafety.js";

export type ReviewRisk = "low" | "medium" | "high";
export type ReviewItemStatus = "pending" | "accepted" | "withdrawn";
export interface ReviewBatchItem { itemId: string; risk: ReviewRisk; summary: string; status: ReviewItemStatus; evidenceRefs: string[]; }
export interface ReviewBatch { schemaVersion: "review-batch.v1"; batchId: string; projectSlug: string; status: "pending" | "accepted" | "partially_withdrawn"; items: ReviewBatchItem[]; createdAt: string; updatedAt: string; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
const batchPath = (root: string, batchId: string) => resolveInside(root, path.join("sessions", "review-batches", `${batchId}.json`));
export function assertReviewBatchIntegrity(batch: ReviewBatch, expectedId?: string): ReviewBatch { const { fingerprint, ...base } = batch; const itemsValid = Array.isArray(batch.items) && batch.items.length > 0 && new Set(batch.items.map((item) => item.itemId)).size === batch.items.length && batch.items.every((item) => item && typeof item.itemId === "string" && item.itemId.trim() && typeof item.summary === "string" && item.summary.trim() && ["low", "medium", "high"].includes(item.risk) && ["pending", "accepted", "withdrawn"].includes(item.status) && Array.isArray(item.evidenceRefs) && item.evidenceRefs.length > 0 && item.evidenceRefs.every((ref) => typeof ref === "string" && ref.trim())); const derivedStatus = batch.items.every((item) => item.status === "accepted") ? "accepted" : batch.items.some((item) => item.status === "withdrawn") ? "partially_withdrawn" : "pending"; const valid = batch.schemaVersion === "review-batch.v1" && (!expectedId || batch.batchId === expectedId) && [batch.batchId, batch.projectSlug, batch.createdAt, batch.updatedAt].every((value) => typeof value === "string" && value.trim()) && itemsValid && batch.status === derivedStatus && !Number.isNaN(Date.parse(batch.createdAt)) && !Number.isNaN(Date.parse(batch.updatedAt)) && /^[a-f0-9]{64}$/i.test(fingerprint) && hash(base) === fingerprint; if (!valid) throw new Error("REVIEW_BATCH_INTEGRITY_FAILED"); return batch; }
async function readJson(root: string, batchId: string): Promise<ReviewBatch | null> { try { const batch = JSON.parse(await fs.readFile(batchPath(root, batchId), "utf8")) as ReviewBatch; return assertReviewBatchIntegrity(batch, batchId); } catch (error) { if (error instanceof Error && "code" in error && (error as { code?: string }).code === "ENOENT") return null; throw error; } }
async function writeJson(root: string, batch: ReviewBatch): Promise<void> { const target = batchPath(root, batch.batchId); await fs.mkdir(path.dirname(target), { recursive: true }); const temporary = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(temporary, `${JSON.stringify(batch, null, 2)}\n`, "utf8"); await fs.rename(temporary, target); }
export function createReviewBatch(input: { batchId: string; projectSlug: string; items: Array<{ itemId: string; risk: ReviewRisk; summary: string; evidenceRefs: string[] }> }): ReviewBatch { if (!input.batchId.trim() || !input.projectSlug.trim() || !input.items.length) throw new Error("REVIEW_BATCH_FIELDS_INVALID"); if (input.items.some((item) => item.risk !== "low")) throw new Error("REVIEW_BATCH_HIGH_RISK_ITEM"); if (input.items.some((item) => !item.itemId.trim() || !item.summary.trim() || !item.evidenceRefs.length)) throw new Error("REVIEW_BATCH_ITEM_INVALID"); const base = { schemaVersion: "review-batch.v1" as const, batchId: input.batchId.trim(), projectSlug: input.projectSlug.trim(), status: "pending" as const, items: input.items.map((item) => ({ ...item, evidenceRefs: [...item.evidenceRefs], status: "pending" as const })), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; return { ...base, fingerprint: hash(base) }; }
export async function persistReviewBatch(root: string, batch: ReviewBatch): Promise<ReviewBatch> { assertReviewBatchIntegrity(batch); const existing = await readJson(root, batch.batchId); if (existing) { if (existing.fingerprint === batch.fingerprint) return existing; throw new Error("REVIEW_BATCH_IMMUTABLE"); } await writeJson(root, batch); return batch; }
export async function readReviewBatch(root: string, batchId: string): Promise<ReviewBatch | null> { return readJson(root, batchId); }
async function transition(root: string, batchId: string, itemId: string, status: ReviewItemStatus): Promise<ReviewBatch> { const current = await readJson(root, batchId); if (!current) throw new Error("REVIEW_BATCH_NOT_FOUND"); const item = current.items.find((candidate) => candidate.itemId === itemId); if (!item) throw new Error("REVIEW_BATCH_ITEM_NOT_FOUND"); if (item.status === "withdrawn") return current; const { fingerprint: _old, ...oldBase } = current; const items = current.items.map((candidate) => candidate.itemId === itemId ? { ...candidate, status } : candidate); const base = { ...oldBase, status: items.every((candidate) => candidate.status === "accepted") ? "accepted" as const : items.some((candidate) => candidate.status === "withdrawn") ? "partially_withdrawn" as const : current.status, items, updatedAt: new Date().toISOString() }; const next = { ...base, fingerprint: hash(base) }; await writeJson(root, next); return next; }
export async function withdrawReviewItem(root: string, batchId: string, itemId: string): Promise<ReviewBatch> { return transition(root, batchId, itemId, "withdrawn"); }
export async function acceptReviewItem(root: string, batchId: string, itemId: string): Promise<ReviewBatch> { return transition(root, batchId, itemId, "accepted"); }
