import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { resolveInside } from "./pathSafety.js";
import type { SceneCardContract } from "./sceneCard.js";

export type SceneEvidenceKind = "trigger" | "pov-goal" | "obstacle" | "strategy" | "turning-point" | "choice" | "cost" | "information-change" | "character-change" | "relationship-change" | "resource-change" | "obligation-action" | "next-hook";
export interface SceneExecutionLedger { schemaVersion: "scene-execution-ledger.v1"; ledgerId: string; projectSlug: string; sceneId: string; chapterId: string; sceneCardFingerprint: string; obligationIds: string[]; plan: Pick<SceneCardContract, "trigger" | "povCharacterId" | "roleGoal" | "conflictStrategy" | "turningPoint" | "informationChange" | "emotionChange" | "relationshipChange" | "resourceChange" | "entryState" | "exitState" | "nextSceneHook">; evidence: Array<{ kind: SceneEvidenceKind; value: string; evidenceRefs: string[]; recordedAt: string }>; status: "planned" | "in_progress" | "completed" | "blocked"; createdAt: string; updatedAt: string; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function file(root: string, id: string) { return resolveInside(root, `sessions/scene-execution-ledgers/${id}.json`); }
async function read<T>(target: string): Promise<T | null> { try { return JSON.parse(await fs.readFile(target, "utf8")) as T; } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return null; throw e; } }
async function write(target: string, value: unknown) { await fs.mkdir(path.dirname(target), { recursive: true }); const tmp = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await fs.rename(tmp, target); }
const requiredKinds: SceneEvidenceKind[] = ["trigger", "pov-goal", "obstacle", "strategy", "turning-point", "choice", "cost", "information-change", "character-change", "relationship-change", "resource-change", "obligation-action", "next-hook"];
export async function readSceneExecutionLedger(root: string, ledgerId: string) { return read<SceneExecutionLedger>(file(root, ledgerId)); }
export async function createSceneExecutionLedger(input: { root: string; sceneCard: SceneCardContract; obligationIds: readonly string[] }): Promise<SceneExecutionLedger> { const ledgerId = `ledger-${input.sceneCard.sceneId}`; const existing = await readSceneExecutionLedger(input.root, ledgerId); if (existing) return existing; const { fingerprint, ...plan } = input.sceneCard; const base = { schemaVersion: "scene-execution-ledger.v1" as const, ledgerId, projectSlug: input.sceneCard.projectSlug, sceneId: input.sceneCard.sceneId, chapterId: input.sceneCard.chapterId, sceneCardFingerprint: fingerprint, obligationIds: [...input.obligationIds], plan: { trigger: plan.trigger, povCharacterId: plan.povCharacterId, roleGoal: plan.roleGoal, conflictStrategy: plan.conflictStrategy, turningPoint: plan.turningPoint, informationChange: plan.informationChange, emotionChange: plan.emotionChange, relationshipChange: plan.relationshipChange, resourceChange: plan.resourceChange, entryState: plan.entryState, exitState: plan.exitState, nextSceneHook: plan.nextSceneHook }, evidence: [], status: "planned" as const, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; const ledger = { ...base, fingerprint: hash(base) }; await write(file(input.root, ledgerId), ledger); return ledger; }
export async function appendSceneExecutionEvidence(root: string, ledgerId: string, input: { kind: SceneEvidenceKind; value: string; evidenceRefs: readonly string[] }): Promise<SceneExecutionLedger> { const ledger = await readSceneExecutionLedger(root, ledgerId); if (!ledger) throw new Error("SCENE_LEDGER_NOT_FOUND"); if (!input.value.trim() || !input.evidenceRefs.length) throw new Error("SCENE_LEDGER_EVIDENCE_REQUIRED"); const evidence = [...ledger.evidence.filter((item) => item.kind !== input.kind), { kind: input.kind, value: input.value, evidenceRefs: [...input.evidenceRefs], recordedAt: new Date().toISOString() }]; const complete = requiredKinds.every((kind) => evidence.some((item) => item.kind === kind)); const base = { ...ledger, evidence, status: complete ? "completed" as const : "in_progress" as const, updatedAt: new Date().toISOString() }; const next = { ...base, fingerprint: hash({ ...base, fingerprint: undefined }) }; await write(file(root, ledgerId), next); return next; }
