export function captureSeed(input: { messageId: string; text: string; persisted: boolean; modelStarted: boolean }): { status: "seed_captured" | "capture_required"; modelCalls: 0; idempotent: boolean } { const ok = Boolean(input.persisted && input.text && input.messageId); return { status: ok ? "seed_captured" : "capture_required", modelCalls: 0, idempotent: !input.modelStarted }; }
export function extractSeedFields(input: { text: string }): { fields: Record<string, string>; unknown: string[] } { return { fields: { situation: input.text }, unknown: ["coreDesire", "cause", "theme", "ending"] }; }
export function requireProvenance(input: { claim: string; spans: readonly string[] }): { status: "supported" | "provisional"; claim: string; spans: string[] } { return { status: input.spans.length ? "supported" : "provisional", claim: input.claim, spans: [...input.spans] }; }
export function blockGenreInference(input: { explicit: readonly string[]; inferred: readonly string[] }): { confirmed: string[]; proposals: string[] } { return { confirmed: [...input.explicit], proposals: [...input.inferred] }; }
export function preserveInterpretations(input: { shared: readonly string[]; branches: readonly string[]; decided: boolean }): { shared: string[]; branches: string[]; canonBranch?: string } { return { shared: [...input.shared], branches: [...input.branches], ...(input.decided ? { canonBranch: input.branches[0] } : {}) }; }
export function allowCompatibleExploration(input: { branches: readonly string[]; candidateSupports: readonly string[] }): { allowed: boolean; hiddenCanon: boolean } { return { allowed: input.branches.every((branch) => input.candidateSupports.includes(branch)), hiddenCanon: true }; }
export function assessReadinessScope(input: { product: "probe" | "outline"; sufficient: boolean; missing: readonly string[] }): { status: "ready_for_scope" | "clarification_required"; missing: string[] } { return { status: input.sufficient && input.product === "probe" ? "ready_for_scope" : "clarification_required", missing: [...input.missing] }; }
export function recommendEvidenceCandidate(input: { candidates: readonly { id: string; coverage: number; evidence: number }[] }): string { return [...input.candidates].sort((a, b) => b.evidence - a.evidence || b.coverage - a.coverage)[0]?.id || ""; }
export function applyScopedDefault(input: { scope: string; field: string; confirmed: readonly string[]; retract: boolean }): { scope: string; field: string; active: boolean; confirmed: string[] } { return { scope: input.scope, field: input.field, active: !input.retract, confirmed: [...input.confirmed] }; }
export function prioritizeQuestion(input: { questions: readonly { id: string; branchImpact: number }[] }): string { return [...input.questions].sort((a, b) => b.branchImpact - a.branchImpact)[0]?.id || ""; }
export function dedupeCandidates(input: { candidates: readonly { id: string; seed: string; fingerprint: string; hardValid: boolean }[] }): { kept: string[]; dropped: string[] } { const seen = new Set<string>(); const kept: string[] = []; const dropped: string[] = []; for (const c of input.candidates) { if (!c.hardValid || seen.has(`${c.seed}:${c.fingerprint}`)) dropped.push(c.id); else { seen.add(`${c.seed}:${c.fingerprint}`); kept.push(c.id); } } return { kept, dropped }; }
export function describeCandidateDifference(input: { facts: readonly string[]; assumptions: readonly string[]; unknown: readonly string[]; impacts: readonly string[]; hardValid: boolean }): { facts: string[]; assumptions: string[]; unknown: string[]; impacts: string[]; selectable: boolean } { return { facts: [...input.facts], assumptions: [...input.assumptions], unknown: [...input.unknown], impacts: [...input.impacts], selectable: input.hardValid }; }
export function applyPartialAdoption(input: { accepted: readonly string[]; rejected: readonly string[]; unknown: readonly string[] }): { locked: string[]; excluded: string[]; unknown: string[] } { return { locked: [...input.accepted], excluded: [...input.rejected], unknown: [...input.unknown] }; }
export function recompileAffected(input: { affected: readonly string[]; unrelated: readonly string[] }): { recompiled: string[]; untouched: string[] } { return { recompiled: [...input.affected], untouched: [...input.unrelated] }; }
export function separateProjectState(input: { projectCreated: boolean; interpreting: boolean; hasCanon: boolean }): { label: string; canGenerateCanonOutline: boolean } { return { label: input.interpreting ? "saved-understanding-in-progress" : "saved", canGenerateCanonOutline: input.hasCanon }; }
export function preserveCompileFailure(input: { previousStable: string; repairFailed: boolean }): { state: "repair_required" | "stable"; readiness: false } { return { state: input.repairFailed ? "repair_required" : "stable", readiness: false }; }
export function shadowLegacyCompile(input: { importedIdea: string; bodyEvidence: string; authorConfirmed: boolean }): { authority: string; writesLegacy: false } { return { authority: input.authorConfirmed ? input.bodyEvidence : "shadow-candidate", writesLegacy: false }; }
export function deterministicCompile(input: { inputFingerprint: string; outputFingerprint: string; seed: string }): { reproducible: boolean; seed: string } { return { reproducible: input.inputFingerprint === input.outputFingerprint, seed: input.seed }; }
export function authorizeReadinessScope(input: { scope: string; endUnknown: boolean }): { authorizedScope: string; fullBook: false } { return { authorizedScope: input.scope, fullBook: false }; }
