import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { resolveInside } from "./pathSafety.js";

export type SemanticNodeKind = "story" | "arc" | "volume" | "chapter" | "scene" | "milestone";
export interface SemanticNode { schemaVersion: "semantic-node.v1"; semanticId: string; projectSlug: string; kind: SemanticNodeKind; label: string; displayChapter: string; displayOrder: number | null; parentId: string | null; sourceRefs: string[]; createdAt: string; updatedAt: string; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function nodePath(root: string, id: string) { return resolveInside(root, `sessions/semantic-nodes/${id}.json`); }
async function read<T>(file: string): Promise<T | null> { try { return JSON.parse(await fs.readFile(file, "utf8")) as T; } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return null; throw e; } }
async function write(file: string, value: unknown) { await fs.mkdir(path.dirname(file), { recursive: true }); const tmp = `${file}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await fs.rename(tmp, file); }
export async function readSemanticNode(root: string, semanticId: string) { return read<SemanticNode>(nodePath(root, semanticId)); }
export async function listSemanticNodes(root: string, projectSlug: string): Promise<SemanticNode[]> { let names: string[]; try { names = await fs.readdir(resolveInside(root, "sessions/semantic-nodes")); } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return []; throw e; } const records = await Promise.all(names.filter((n) => n.endsWith(".json")).map((n) => read<SemanticNode>(path.join(resolveInside(root, "sessions/semantic-nodes"), n)))); return records.filter((n): n is SemanticNode => Boolean(n && n.projectSlug === projectSlug)).sort((a, b) => a.semanticId.localeCompare(b.semanticId)); }
export async function createSemanticNode(input: { root: string; projectSlug: string; semanticId: string; kind: SemanticNodeKind; label: string; displayChapter: string; parentId?: string | null; sourceRefs: readonly string[] }): Promise<SemanticNode> { if (![input.projectSlug, input.semanticId, input.label, input.displayChapter].every((v) => v.trim())) throw new Error("SEMANTIC_NODE_FIELDS_REQUIRED"); if (!input.sourceRefs.length) throw new Error("SEMANTIC_NODE_SOURCE_REQUIRED"); const existing = await readSemanticNode(input.root, input.semanticId); if (existing) return existing; const base = { schemaVersion: "semantic-node.v1" as const, semanticId: input.semanticId, projectSlug: input.projectSlug, kind: input.kind, label: input.label, displayChapter: input.displayChapter, displayOrder: null, parentId: input.parentId ?? null, sourceRefs: [...input.sourceRefs], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; const node = { ...base, fingerprint: hash(base) }; await write(nodePath(input.root, input.semanticId), node); return node; }
export async function projectSemanticNodeOrder(root: string, projectSlug: string, orderedSemanticIds: readonly string[]): Promise<Array<SemanticNode & { displayOrder: number }>> { const nodes = await listSemanticNodes(root, projectSlug); const byId = new Map(nodes.map((n) => [n.semanticId, n])); const result: Array<SemanticNode & { displayOrder: number }> = []; for (const [index, id] of orderedSemanticIds.entries()) { const node = byId.get(id); if (!node) throw new Error("SEMANTIC_NODE_NOT_FOUND"); const projected = { ...node, displayOrder: index + 1 }; await write(nodePath(root, id), { ...projected, updatedAt: new Date().toISOString() }); result.push(projected); } return result; }
