import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { resolveInside } from "./pathSafety.js";
export type SourceAccessClass = "public" | "private" | "restricted" | "unknown";
export type SourceEligibility = "default_allowed" | "analysis_only" | "blocked";
export interface SourceMaterialRecord { schemaVersion: "source-material-record.v1"; recordId: string; projectSlug: string; platform: string; stableLocator: string; capturedAt: string; contentFingerprint: string; sourceFamily: string; accessClass: SourceAccessClass; processingPurpose: string; retainableEvidenceScope: string; projectScope: string; platformScope: string; refreshPolicy: string; expiresAt: string; deletionPolicy: string; eligibility: SourceEligibility; sourceRefs: string[]; createdAt: string; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function file(root: string, id: string) { return resolveInside(root, `sessions/source-material/${id}.json`); }
async function read<T>(target: string): Promise<T | null> { try { return JSON.parse(await fs.readFile(target, "utf8")) as T; } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return null; throw e; } }
async function write(target: string, value: unknown) { await fs.mkdir(path.dirname(target), { recursive: true }); const tmp = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await fs.rename(tmp, target); }
export function classifySourceEligibility(input: { accessClass: SourceAccessClass; retainableEvidenceScope: string }): SourceEligibility { if (input.accessClass === "public" && input.retainableEvidenceScope.trim()) return "default_allowed"; if (input.accessClass === "unknown" || input.accessClass === "private" || input.accessClass === "restricted") return "analysis_only"; return "blocked"; }
export async function readSourceMaterialRecord(root: string, recordId: string) { return read<SourceMaterialRecord>(file(root, recordId)); }
export async function createSourceMaterialRecord(input: { root: string; projectSlug: string; platform: string; stableLocator: string; capturedAt: string; contentFingerprint: string; sourceFamily: string; accessClass: SourceAccessClass; processingPurpose: string; retainableEvidenceScope: string; projectScope: string; platformScope: string; refreshPolicy: string; expiresAt: string; deletionPolicy: string; sourceRefs: readonly string[] }): Promise<SourceMaterialRecord> { if (!input.projectSlug.trim() || !input.platform.trim() || !input.sourceFamily.trim()) throw new Error("SOURCE_FIELDS_REQUIRED"); if (!input.stableLocator.trim()) throw new Error("SOURCE_LOCATOR_REQUIRED"); if (!/^[a-f0-9]{64}$/i.test(input.contentFingerprint)) throw new Error("SOURCE_FINGERPRINT_REQUIRED"); if (!input.processingPurpose.trim() || !input.projectScope.trim() || !input.platformScope.trim() || !input.refreshPolicy.trim() || !input.expiresAt.trim() || !input.deletionPolicy.trim()) throw new Error("SOURCE_LIFECYCLE_REQUIRED"); if (!input.sourceRefs.length) throw new Error("SOURCE_EVIDENCE_REQUIRED"); const recordId = `source-${hash({ projectSlug: input.projectSlug, stableLocator: input.stableLocator }).slice(0, 20)}`; const existing = await readSourceMaterialRecord(input.root, recordId); if (existing) return existing; const base = { schemaVersion: "source-material-record.v1" as const, recordId, projectSlug: input.projectSlug, platform: input.platform, stableLocator: input.stableLocator, capturedAt: input.capturedAt, contentFingerprint: input.contentFingerprint, sourceFamily: input.sourceFamily, accessClass: input.accessClass, processingPurpose: input.processingPurpose, retainableEvidenceScope: input.retainableEvidenceScope, projectScope: input.projectScope, platformScope: input.platformScope, refreshPolicy: input.refreshPolicy, expiresAt: input.expiresAt, deletionPolicy: input.deletionPolicy, eligibility: classifySourceEligibility(input), sourceRefs: [...input.sourceRefs], createdAt: new Date().toISOString() }; const record = { ...base, fingerprint: hash(base) }; await write(file(input.root, recordId), record); return record; }
