import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { resolveInside } from "./pathSafety.js";
export type SourceAccessClass = "public" | "private" | "restricted" | "unknown";
export type SourceEligibility = "default_allowed" | "analysis_only" | "blocked";
export interface SourceMaterialRecord { schemaVersion: "source-material-record.v1"; recordId: string; projectSlug: string; platform: string; stableLocator: string; capturedAt: string; contentFingerprint: string; sourceFamily: string; accessClass: SourceAccessClass; processingPurpose: string; retainableEvidenceScope: string; projectScope: string; platformScope: string; refreshPolicy: string; expiresAt: string; deletionPolicy: string; eligibility: SourceEligibility; sourceRefs: string[]; createdAt: string; fingerprint: string; }
function hash(value: unknown) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function file(root: string, id: string) { return resolveInside(root, `sessions/source-material/${id}.json`); }
async function read<T>(target: string): Promise<T | null> { try { return JSON.parse(await fs.readFile(target, "utf8")) as T; } catch (e) { if (e instanceof Error && "code" in e && (e as { code?: string }).code === "ENOENT") return null; throw e; } }
async function write(target: string, value: unknown) { await fs.mkdir(path.dirname(target), { recursive: true }); const tmp = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; await fs.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await fs.rename(tmp, target); }
export function classifySourceEligibility(input: { accessClass: SourceAccessClass; retainableEvidenceScope: string }): SourceEligibility { if (input.accessClass === "public" && input.retainableEvidenceScope.trim()) return "default_allowed"; if (input.accessClass === "unknown" || input.accessClass === "private" || input.accessClass === "restricted") return "analysis_only"; return "blocked"; }
function assertRecordIntegrity(record: SourceMaterialRecord, expectedId?: string): SourceMaterialRecord { const { fingerprint: _fingerprint, ...base } = record; const capturedAt = Date.parse(record.capturedAt); const expiresAt = Date.parse(record.expiresAt); const valid = record.schemaVersion === "source-material-record.v1" && (!expectedId || record.recordId === expectedId) && [record.recordId, record.projectSlug, record.platform, record.stableLocator, record.capturedAt, record.sourceFamily, record.processingPurpose, record.retainableEvidenceScope, record.projectScope, record.platformScope, record.refreshPolicy, record.expiresAt, record.deletionPolicy, record.createdAt].every((value) => typeof value === "string" && value.trim()) && /^[a-f0-9]{64}$/i.test(record.contentFingerprint) && ["public", "private", "restricted", "unknown"].includes(record.accessClass) && ["default_allowed", "analysis_only", "blocked"].includes(record.eligibility) && classifySourceEligibility(record) === record.eligibility && Array.isArray(record.sourceRefs) && record.sourceRefs.length > 0 && record.sourceRefs.every((ref) => typeof ref === "string" && ref.trim()) && Number.isFinite(capturedAt) && Number.isFinite(expiresAt) && expiresAt > capturedAt && Number.isFinite(Date.parse(record.createdAt)) && /^[a-f0-9]{64}$/i.test(record.fingerprint) && hash(base) === record.fingerprint; if (!valid) throw new Error("SOURCE_RECORD_INTEGRITY_FAILED"); return record; }
export async function readSourceMaterialRecord(root: string, recordId: string) { const record = await read<SourceMaterialRecord>(file(root, recordId)); return record ? assertRecordIntegrity(record, recordId) : null; }
export async function createSourceMaterialRecord(input: { root: string; projectSlug: string; platform: string; stableLocator: string; capturedAt: string; contentFingerprint: string; sourceFamily: string; accessClass: SourceAccessClass; processingPurpose: string; retainableEvidenceScope: string; projectScope: string; platformScope: string; refreshPolicy: string; expiresAt: string; deletionPolicy: string; sourceRefs: readonly string[] }): Promise<SourceMaterialRecord> { if (!input.projectSlug.trim() || !input.platform.trim() || !input.sourceFamily.trim()) throw new Error("SOURCE_FIELDS_REQUIRED"); if (!input.stableLocator.trim()) throw new Error("SOURCE_LOCATOR_REQUIRED"); if (!/^[a-f0-9]{64}$/i.test(input.contentFingerprint)) throw new Error("SOURCE_FINGERPRINT_REQUIRED"); if (!input.processingPurpose.trim() || !input.projectScope.trim() || !input.platformScope.trim() || !input.refreshPolicy.trim() || !input.expiresAt.trim() || !input.deletionPolicy.trim()) throw new Error("SOURCE_LIFECYCLE_REQUIRED"); if (!input.sourceRefs.length || input.sourceRefs.some((ref) => !ref.trim())) throw new Error("SOURCE_EVIDENCE_REQUIRED"); const capturedAt = Date.parse(input.capturedAt); const expiresAt = Date.parse(input.expiresAt); if (!Number.isFinite(capturedAt)) throw new Error("SOURCE_CAPTURED_AT_INVALID"); if (!Number.isFinite(expiresAt) || expiresAt <= capturedAt) throw new Error("SOURCE_EXPIRY_INVALID"); const recordId = `source-${hash({ projectSlug: input.projectSlug, stableLocator: input.stableLocator }).slice(0, 20)}`; const existing = await readSourceMaterialRecord(input.root, recordId); if (existing) return existing; const base = { schemaVersion: "source-material-record.v1" as const, recordId, projectSlug: input.projectSlug, platform: input.platform, stableLocator: input.stableLocator, capturedAt: input.capturedAt, contentFingerprint: input.contentFingerprint, sourceFamily: input.sourceFamily, accessClass: input.accessClass, processingPurpose: input.processingPurpose, retainableEvidenceScope: input.retainableEvidenceScope, projectScope: input.projectScope, platformScope: input.platformScope, refreshPolicy: input.refreshPolicy, expiresAt: input.expiresAt, deletionPolicy: input.deletionPolicy, eligibility: classifySourceEligibility(input), sourceRefs: [...input.sourceRefs], createdAt: new Date().toISOString() }; const record = { ...base, fingerprint: hash(base) }; await write(file(input.root, recordId), record); return record; }
