import crypto from "node:crypto";

export interface TextProfile { schemaVersion: "text-profile.v1"; profileId: string; locale: string; allowedScripts: string[]; unicodeNormalization: string; encoding: string; newline: string; paragraphSeparator: string; quoteStyle: string; exceptions: string[]; fingerprint: string; }
export interface TextStructure { schemaVersion: "text-structure-snapshot.v1"; profile: string; version: string; blocks: Array<{ kind: "heading" | "paragraph" | "pollution-candidate"; start: number; end: number; text: string }>; canonText: string; fingerprint: string; }
export interface TextDiagnostic { schemaVersion: "text-diagnostic.v1"; diagnosticId: string; profileVersion: string; severity: string; start: number; end: number; rule: string; reason: string; counterExample: string; repairBoundary: string; authorApproved: boolean; repairAllowed: boolean; fingerprint: string; }
export interface TextSettlement { schemaVersion: "text-settlement.v1"; status: "settled" | "blocked"; profileVersion: string; originalHash: string; normalizedHash: string; structureHashBefore: string; structureHashAfter: string; sourceMapStable: boolean; diagnosticsResolved: boolean; exportRegressionPassed: boolean; approvedExceptions: string[]; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
export function createTextProfile(input: Omit<TextProfile, "schemaVersion" | "fingerprint">): TextProfile { if (!input.profileId.trim() || !input.locale.trim() || !input.allowedScripts.length || !input.encoding.trim()) throw new Error("TEXT_PROFILE_FIELDS_REQUIRED"); const base = { schemaVersion: "text-profile.v1" as const, ...input, allowedScripts: [...input.allowedScripts], exceptions: [...input.exceptions] }; return { ...base, fingerprint: hash(base) }; }
export function parseTextStructure(input: { profile: string; version: string; text: string }): TextStructure { if (!input.profile.trim() || !input.version.trim()) throw new Error("TEXT_STRUCTURE_FIELDS_REQUIRED"); const blocks: TextStructure["blocks"] = []; let canonText = input.text; const pollution = /```[\s\S]*?```/g; let match: RegExpExecArray | null; while ((match = pollution.exec(input.text))) { blocks.push({ kind: "pollution-candidate", start: match.index, end: match.index + match[0].length, text: match[0] }); } canonText = input.text.replace(pollution, ""); for (const match of input.text.matchAll(/^# .+$/gm)) blocks.push({ kind: "heading", start: match.index ?? 0, end: (match.index ?? 0) + match[0].length, text: match[0] }); const base = { schemaVersion: "text-structure-snapshot.v1" as const, profile: input.profile, version: input.version, blocks: blocks.sort((a, b) => a.start - b.start), canonText }; return { ...base, fingerprint: hash(base) }; }
export function createTextDiagnostic(input: Omit<TextDiagnostic, "schemaVersion" | "repairAllowed" | "fingerprint">): TextDiagnostic { if (!input.diagnosticId.trim() || !input.profileVersion.trim() || input.start < 0 || input.end <= input.start || !input.rule.trim()) throw new Error("TEXT_DIAGNOSTIC_FIELDS_REQUIRED"); const base = { schemaVersion: "text-diagnostic.v1" as const, ...input, repairAllowed: input.authorApproved && input.repairBoundary === "local-only" }; return { ...base, fingerprint: hash(base) }; }
export function settleTextRoundTrip(input: Omit<TextSettlement, "schemaVersion" | "status" | "fingerprint">): TextSettlement { const status = input.originalHash === input.normalizedHash && input.structureHashBefore === input.structureHashAfter && input.sourceMapStable && input.diagnosticsResolved && input.exportRegressionPassed ? "settled" as const : "blocked" as const; const base = { schemaVersion: "text-settlement.v1" as const, ...input, approvedExceptions: [...input.approvedExceptions], status }; return { ...base, fingerprint: hash(base) }; }
