import crypto from "node:crypto";

export interface LegacyWorldCompileResult { schemaVersion: "legacy-world-compile.v1"; status: "compiled" | "unhealthy"; scannedPaths: string[]; coverage: Record<string, string[]>; candidates: Array<{ candidateId: string; kind: "rule" | "ability" | "timeline" | "continuity"; sourceRefs: string[]; excerpt: string }>; conflicts: Array<{ conflictId: string; candidateIds: string[]; status: "unresolved"; reason: string }>; unresolvedRegions: string[]; scanWarnings: string[]; fingerprint: string; }
const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
const required = { world: ["bible/world.md"], power: ["bible/power-system.md"], timeline: ["timeline/"], "story-control": ["story-control/story-control.json"], "power-progression": ["ledger/power-progression.md"], continuity: ["ledger/continuity.md"], prose: ["chapters/"] };
export function compileLegacyWorldMaterials(sources: readonly { path: string; content: string; sourceVersion: string }[]): LegacyWorldCompileResult {
  const scannedPaths = sources.map((source) => source.path); const unresolvedRegions: string[] = []; const coverage: Record<string, string[]> = {};
  for (const [region, patterns] of Object.entries(required)) { coverage[region] = sources.filter((source) => patterns.some((pattern) => pattern.endsWith("/") ? source.path.startsWith(pattern) : source.path === pattern)).map((source) => source.path); if (!coverage[region].length) unresolvedRegions.push(region); }
  const scanWarnings = sources.filter((source) => /TRUNCATED|截断|拼接失败|\[\.\.\.\]/iu.test(source.content)).map((source) => `TRUNCATED_SOURCE:${source.path}`); for (const warning of scanWarnings) if (!unresolvedRegions.includes("truncated")) unresolvedRegions.push("truncated");
  const candidates = sources.flatMap((source) => { const kind = source.path === "bible/power-system.md" ? "ability" as const : source.path.includes("world") ? "rule" as const : source.path.includes("timeline") ? "timeline" as const : source.path.includes("continuity") ? "continuity" as const : undefined; return kind && source.content.trim() ? [{ candidateId: `legacy-${hash({ path: source.path, content: source.content }).slice(0, 16)}`, kind, sourceRefs: [`legacy://${source.path}@${source.sourceVersion}`], excerpt: source.content.slice(0, 240) }] : []; });
  const conflicts: LegacyWorldCompileResult["conflicts"] = []; const byKind = new Map<string, typeof candidates>(); for (const candidate of candidates) byKind.set(candidate.kind, [...(byKind.get(candidate.kind) ?? []), candidate]); for (const [kind, items] of byKind) if (items.length > 1) conflicts.push({ conflictId: `conflict-${kind}-${hash(items.map((item) => item.candidateId)).slice(0, 10)}`, candidateIds: items.map((item) => item.candidateId), status: "unresolved", reason: `multiple ${kind} candidates require author adjudication` });
  const base = { schemaVersion: "legacy-world-compile.v1" as const, status: unresolvedRegions.length || conflicts.length ? "unhealthy" as const : "compiled" as const, scannedPaths, coverage, candidates, conflicts, unresolvedRegions, scanWarnings };
  return { ...base, fingerprint: hash(base) };
}
