export function scanWorldDocument(input: { characters: number; headings: number; sourceVersion: string; unresolved: number }): { scanned: boolean; headings: number; sourceVersion: string; unresolved: number; truncated: false } { return { scanned: input.characters > 0, headings: input.headings, sourceVersion: input.sourceVersion, unresolved: input.unresolved, truncated: false }; }
export function enforceRuleBoundary(input: { actor: string; anchor: string; distance: number; energy: number; cooldown: number; blocked: boolean; failure: string; hasAnchor: boolean }): { allowed: boolean; reason: string } { const allowed = input.hasAnchor && !input.blocked && input.energy > 0 && input.distance >= 0; return { allowed, reason: allowed ? "within-rule" : "rule-boundary" }; }
export function preserveInstitutionBelief(input: { claims: readonly { owner: string; claim: string }[]; authorTruth?: string }): { claims: Array<{ owner: string; claim: string }>; objective: string | null } { return { claims: input.claims.map((claim) => ({ ...claim })), objective: input.authorTruth ?? null }; }
export function applyRegionalRule(input: { rule: string; origin: string; target: string; modifier: number; newCost: string }): { modifier: number; cost: string; retroactive: false } { return { modifier: input.origin === input.target ? input.modifier : 0, cost: input.origin === input.target ? "none" : input.newCost, retroactive: false }; }
export function checkTravelFeasibility(input: { requiredDays: number; elapsedDays: number; transportProof: boolean; departureProof: boolean; timeJump: boolean }): { feasible: boolean; conflict: boolean } { const feasible = input.elapsedDays >= input.requiredDays || input.transportProof || input.departureProof || input.timeJump; return { feasible, conflict: !feasible }; }
export function projectStoryClock(input: { eventTimes: readonly number[]; chapter: number }): { now: number; chapter: number } { return { now: Math.max(...input.eventTimes, 0), chapter: input.chapter }; }
export function enforceAbilityPrerequisites(input: { required: readonly string[]; present: readonly string[]; fallbackCost?: string }): { allowed: boolean; missing: string[]; fallback: string | null } { const missing = input.required.filter((item) => !input.present.includes(item)); return { allowed: missing.length === 0 || Boolean(input.fallbackCost), missing, fallback: input.fallbackCost ?? null }; }
export function settleTemporaryBoost(input: { source: string; temporary: boolean; expiresAt: number; now: number; progressionEvent: boolean }): { status: "borrowed" | "expired" | "progressed"; permanent: boolean } { if (input.progressionEvent) return { status: "progressed", permanent: true }; return { status: input.now >= input.expiresAt ? "expired" : "borrowed", permanent: false }; }
export function assessContextualVictory(input: { powerDelta: number; terrain: boolean; counterKnowledge: boolean; opponentError: boolean; preparation: boolean; cost: boolean }): { proven: boolean; evidence: string[] } { const evidence = [input.terrain ? "terrain" : "", input.counterKnowledge ? "counter" : "", input.opponentError ? "error" : "", input.preparation ? "preparation" : "", input.cost ? "cost" : ""].filter(Boolean); return { proven: evidence.length >= 2 && input.powerDelta <= 0, evidence }; }
export function conserveResource(input: { balance: number; spend: number; acquisition: number }): { balance: number; valid: boolean } { const next = input.balance - input.spend + input.acquisition; return { balance: next, valid: next >= 0 }; }
export function enforceBodyAndCooldown(input: { injuryUntil: number; cooldownUntil: number; now: number; treatment: boolean }): { injured: boolean; cooling: boolean } { const injured = input.now < input.injuryUntil && !input.treatment; const cooling = input.now < input.cooldownUntil; return { injured, cooling }; }
export function scheduleInstitutionResponse(input: { intelDay: number; verifyDays: number; mobilizeDays: number; encounterDay: number }): { ready: boolean; earliest: number } { const earliest = input.intelDay + input.verifyDays + input.mobilizeDays; return { ready: input.encounterDay >= earliest, earliest }; }
export function assessRuleConsequences(input: { rule: string; professions: number; price: number; war: number; lifespan: number; explanation: string }): { covered: boolean; gaps: string[] } { const gaps = [input.professions ? "" : "professions", input.price ? "" : "price", input.war ? "" : "war", input.lifespan ? "" : "lifespan", input.explanation ? "" : "explanation"].filter(Boolean); return { covered: gaps.length === 0, gaps }; }
export function gateDeusExRule(input: { priorHints: number; boundary: boolean; irreversibleCost: boolean }): { status: "allowed" | "deus_ex_rule"; blocked: boolean } { const allowed = input.priorHints > 0 && input.boundary && input.irreversibleCost; return { status: allowed ? "allowed" : "deus_ex_rule", blocked: !allowed }; }
export function recordRuleException(input: { rule: string; reason: string; knowledgeScope: string; recoveryWindow: string }): { debt: true; fields: string[] } { return { debt: true, fields: [input.rule, input.reason, input.knowledgeScope, input.recoveryWindow] }; }
export function preserveRuleInteractionCandidates(input: { candidates: readonly string[]; selected?: string; version: string }): { candidates: string[]; replayKey: string } { return { candidates: [...input.candidates], replayKey: input.selected ? `${input.version}:${input.selected}` : input.version }; }
export function minimizeRuleExposition(input: { observableCost: string; fullRuleAvailable: boolean; encyclopediaParagraphs: number }): { sufficient: boolean; paragraphs: number } { return { sufficient: Boolean(input.observableCost && input.fullRuleAvailable), paragraphs: input.encyclopediaParagraphs }; }
export function scopeRuleChange(input: { changed: readonly string[]; affected: readonly string[]; unrelated: readonly string[]; confirmed: boolean }): { recompute: string[]; protected: string[]; writes: boolean } { return { recompute: input.confirmed ? [...new Set([...input.changed, ...input.affected])] : [], protected: [...input.unrelated], writes: input.confirmed }; }
export function assessWorldHealth(input: { ledgerCoverage: number; sourceCandidates: number; ruleConflicts: number; continuityEvidence: number }): { status: "coverage_missing" | "healthy"; risks: string[] } { const risks = [input.ledgerCoverage < 1 ? "coverage_missing" : "", input.sourceCandidates ? "source-candidates" : "", input.ruleConflicts ? "rule-conflicts" : "", input.continuityEvidence < 1 ? "continuity-missing" : ""].filter(Boolean); return { status: risks.length ? "coverage_missing" : "healthy", risks }; }
export function issueWorldCertificate(input: { scope: string; unknown: readonly string[]; keyExceptions: number; scanFailures: number; resourceConflicts: number }): { status: "audited_consistent_for_scope" | "blocked"; unknown: string[] } { const blocked = input.keyExceptions > 0 || input.scanFailures > 0 || input.resourceConflicts > 0; return { status: blocked ? "blocked" : "audited_consistent_for_scope", unknown: [...input.unknown] }; }
